### ISSUE TITLE
Printf-style formatting

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1007]
## Feature

`str % tuple` formatting, e.g.
```python
"%s: %d" % ("abc", 123) == "abc: 123"
```
This is used in `collections` from the CPython standard library (among probably other modules), which is in turn depended on by `functools` and `unittest`.

## Python Documentation

https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting

**Comment by windelbouwman** [comment]
This can be implemented by implementing `__mod__` into the `objstr.rs` file.

**Comment by michelhe** [comment]
I've started to work on it.
