### ISSUE TITLE
[RFC] Split off bytecode compilation into a separate crate

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1023]
## Summary

Make a new crate, `rustpython_bytecode`, that holds the bytecode data structures and does the compilation from the AST from `rustpython_parser` to bytecode.

## Detailed Explanation

This would likely be easy to implement, just move `bytecode.rs` and `compile.rs` into a separate crate. This would allow us to let `rustpython_derive` depend on `rustpython_bytecode` and we would be able to compile Python to bytecode at compile time. Then we would be able to create frozen modules more efficiently: just run the bytecode, no need to parse the source code at runtime.

## Drawbacks, Rationale, and Alternatives

I believe @windelbouwman said that it would be nice to not fragment RustPython into too many crates, citing npm and `left-pad` as an argument against doing so. I believe that this is a fairly logical place to split up RustPython, allowing us separation of concerns. In addition, Rust's crate system and cargo allow many crates to be depended upon easily, and many large players in Rust's ecosystem have modularized, allowing consumers to only depend on what they need (see: tokio, actix, amethyst, wasmer, etc). We're not in that exact situation, but still.

An alternative to this would just be a `build.rs` file for `rustpython` that depends on `rustpython_vm` and compiles source code there, but that feels less elegant and would have to be copied for `rustpython_wasm` or anyone that wants to embed RustPython into their app.

## Unresolved Questions

There may be some other solution to this compile-time compilation I haven't thought of, if anyone could think of something else I'd be interested to hear it.

**Comment by palaviv** [comment]
> There may be some other solution to this compile-time compilation I haven't thought of, if anyone could think of something else I'd be interested to hear it.

CPython has the [`make regen-importlib`](https://github.com/python/cpython/blob/45a14942c969ed508b35abd5e116cb18f84ce5b4/Makefile.pre.in#L698) that created a small executable that compiles the code and write it to file.

I think you solution is probably better as you will not need to run a special command every time you will change the bytecode. Is your plan to compile the frozen modules every time we build rustpython?

**Comment by windelbouwman** [comment]
I like this idea! I would suggest to create two extra crates next to `rustpython_vm` and `rustpython_parser`. I would call it `rustpython_compiler` and `rustpython_bytecode`.

My main problem with leftpad is that this was also a seperate git repository with all the branching, pull requests overhead etc. I believe having more smaller crates in a single repository is pretty okay.
