### ISSUE TITLE
unicode literals not work 

### ISSUE THREAD

**Issue by yanganto** [RustPython/RustPython#1025]
## Feature
In Python source code, specific Unicode code points can be written using the `\u` escape sequence, which is followed by four hex digits giving the code point. The `\U` escape sequence is similar but expects eight hex digits, not four.

cpython
```python
Python 3.7.3 (default, Mar 26 2019, 21:43:19)
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "\u0037"
'7'
>>> "\xac"
'¬'
```
RustPython
```python
Welcome to the magnificent Rust Python 0.0.1 interpreter 😱 🖖
>>>>> "\u0037"
'\\u0037'
>>>>> "\xac"
'\\xac'
```

## Python Documentation
https://docs.python.org/3/howto/unicode.html#unicode-literals-in-python-source-code

**Comment by windelbouwman** [comment]
This is a lexer issue. I think the lexer only takes ascii into account at this point for strings, or it does not replace escape code properly.

**Comment by yanganto** [comment]
May I implement this feature?  It is essential if I want to implement some the test for `str.isprintable` #1024

**Comment by windelbouwman** [comment]
Sure! Give it your best shot :)

**Comment by ProgVal** [comment]
Hi, I don't really know how RustPython works, but unicode literals are tricky to get right (if your goal is to be fully compatible with CPython).

CPython supports unpaired surrogate code points in unicode literals, which are invalid UTF-8.

In the toy rust interpreter I wrote a while ago, I use the `wtf8` crate to store this ill-formed UTF-8: https://github.com/ProgVal/rust-python-parser/commit/cd6159b70a546a0f4780a295d74c27e640319765

See also: https://simonsapin.github.io/wtf-8/

Have fun! :)

**Comment by michelhe** [comment]
> This is a lexer issue. I think the lexer only takes ascii into account at this point for strings, or it does not replace escape code properly.

True, note that other types of escaping like `\x` are not implemented.

**Comment by yanganto** [comment]
@ProgVal  Thank you,  I almost there.
