### ISSUE TITLE
_codecs module

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1040]
## Feature

The _codecs builtin module is required for using `codecs.py` and therefore `pickle.py` wholesale from CPython.

## Python Documentation

Documentation: https://docs.python.org/3/library/codecs.html

C module: https://github.com/python/cpython/blob/3.7/Modules/_codecsmodule.c

**Comment by youknowone** [comment]
```
>>>>> import _codecs
>>>>> 
```
