### ISSUE TITLE
re module

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1058]
## Feature

The `re` module, for regex. Necessary for unittest, as I discuessed in #1057. It would be nice if we could just implement the `_re` module and let the python modules from CPython take over the rest.

## Python Documentation

https://docs.python.org/3.5/library/re.html

**Comment by seeeturtle** [comment]
Anybody working on it?

**Comment by coolreader18** [comment]
We do have a `re` module, but it uses the Rust `regex` crate to do Regex and is incompatible with Python's Regex engine, `sre`. There is a branch `coolreader18/sre`  where I began to translate the C code to Rust, but it's not at all close to done yet. If you'd like, you could contribute to translating there, or if you have your own idea or method of translating CPython's `_sre.c` then you could do that.

**Comment by JimJeon** [comment]
I think PR #1455 fixes this issue.
