### ISSUE TITLE
Investigate the size of the binary

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#1060]
Our builds are rather large at this point. The release build is 18MB, the debug build is 89MB. This is rather big, and slows things down. What is the cause of this code size?

**Comment by windelbouwman** [comment]
Does anyone have good resources / online manuals on how to investigate code size?

**Comment by coolreader18** [comment]
I know of [`cargo-bloat`](https://github.com/RazrFalcon/cargo-bloat)

**Comment by apatrushev** [comment]
> Does anyone have good resources / online manuals on how to investigate code size?

https://github.com/johnthagen/min-sized-rust
https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html
https://github.com/RazrFalcon/cargo-bloat

**Comment by windelbouwman** [comment]
Okay, I did some measurements.

rustpython commit: 9e194b390484b1d28c938493197077567be979d6
Date: 2019-06-26
cargo version: 1.35.0
rustc version: 1.35.0
toolchain: stable-x86_64-unknown-linux-gnu
os: archlinux

First build in release mode:

    cargo --release
    target/release/rustpython = 11236832 bytes (11 MB)

Enable LTO (link time optimization) in Cargo.toml

    # Cargo.toml
    [profile.release]
    lto = true

    cargo --release
    target/release/rustpython = 9387840 bytes (9 MB)

Run strip on the lto build:

    target/release/rustpython = 7678664 bytes (7.6 MB)

**Comment by coolreader18** [comment]
Oh wow, that's a lot better!

**Comment by pwnorbitals** [comment]
Probably this issue can be closed now ;) @windelbouwman

**Comment by youknowone** [comment]
For now,
- linux:  11MB
- macos: 14MB
- windows: 16MB

**Comment by lastmjs** [comment]
The size is still too large for our use case, I suppose we can continue the discussion in this issue: https://github.com/RustPython/RustPython/issues/4203
