### ISSUE TITLE
[RFC] reduce the number of CI builds

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#1066]
## Summary

In order to save time for pull request builds and save travis resources, I suggest to reduce the number of builds on travis and azure.

## Detailed Explanation

At this point we have 9 different travis configuration build for each pull request. This appears to me as overkill. We just want to know if there was nothing obviously broken. More thorough testing will occur on the master branch.

## Drawbacks, Rationale, and Alternatives

Occasionally a build on master will fail, so this is a drawback, but I think the time / electrical energy saved is worth it.

## Unresolved Questions

- Which builds to keep, which to delete?
- Should we use only azure with macOS/windows/linux builds?

**Comment by coolreader18** [comment]
I think that we could definitely limit codecov to a maybe once a week cron job, and that's usually the longest build and the one most prone to failure.

**Comment by palaviv** [comment]
How about moving some of the builds to be `allow_failures`? I would suggest keeping the following builds as must pass for each PR:

- Rust stable - run snippets
- Rust stable - cargo test
- rustfmt
- test WASM

**Comment by windelbouwman** [comment]
Agreed with @palaviv . 

How about rust nightly? Should we stick to that?

**Comment by windelbouwman** [comment]
See #1081

**Comment by windelbouwman** [comment]
I suggest to keep rust stable as only officially supported version in travis. What is your opinion?

**Comment by coolreader18** [comment]
Sounds good to me.

**Comment by windelbouwman** [comment]
Closing this, since we now have something usable.
