### ISSUE TITLE
exceptions.py tests failing on >= 3.7 because repr changed

### ISSUE THREAD

**Issue by silmeth** [RustPython/RustPython#1088]
CPython 3.7 [changed exception’s `repr`](https://docs.python.org/3.7/whatsnew/3.7.html) implementation to get rid of a trailing comma:

> `repr` for [`BaseException`](https://docs.python.org/3.7/library/exceptions.html#BaseException) has changed to not include the trailing comma. Most exceptions are affected by this change. (Contributed by Serhiy Storchaka in [bpo-30399](https://bugs.python.org/issue30399).)

This makes the test case from `exceptions.py` fail on CPython 3.7 and later.

Should we get rid of the tests for repr, or perhaps just test substrings (that `repr` string contains both the type and the message)?

**Comment by windelbouwman** [comment]
Should we aim for python3.7 compatibility? I think removing the trailing comma is good.

We could test for python version number in the test, but this might not be a good thing to start with. It feels like a rabbit hole.

**Comment by silmeth** [comment]
I don’t think this behaviour is well documented anywhere in the official docs (or that built-in exceptions `repr` is documented at all, at least I cannot find it easily), so perhaps aiming at exact reproduction of any CPython’s behaviour isn’t necessary?

I’d myself restrict the tests to checking some minimal requirements that any sane Python3 (including both CPython 3.6 and CPython 3.7) meet. Eg. that the `repr` string contains the exception type first and then later it contains the message – but disregard punctuation entirely. Or just check that the message is enclosed in parentheses.

Since this is a detail that CPython changed from version to version, the client code shouldn’t rely on it anyway.

**Comment by silmeth** [comment]
Or since `repr` should give a proper working Python representation – perhaps doing a round-trip test: checking whether `eval()` on the `repr(exception)` gives the same exception would be a good solution that all good Python implementation should pass?

**Comment by windelbouwman** [comment]
That sounds fair. Then we can add an additional function:
```python
def round_trip(ex):
    assert exceptions_eq(ex, eval(repr(ex)))
```
