### ISSUE TITLE
.pyc files and bytecode changes

### ISSUE THREAD

**Issue by palaviv** [RustPython/RustPython#1090]
As [mentioned](https://github.com/RustPython/RustPython/pull/1068#issue-292730561) .pyc are working now when `sys.dont_write_bytecode` is set to `False`.
I would like to make the use of `.pyc` files the default but I am not sure how should we follow changes in the bytecode. CPython has a magic number defined in `_bootstrap_external.py` that changes every time the bytecode is changed. RustPython is changing rapidly and I don't think we would like to update a magic number every change in the bytecode.

I have a few suggestion:

- Use the git commit as the magic: Would allow multiple runs with same `.pyc` without code changes.
- Use a random number on main start: Would allow only the same run of main to use the same `.pyc`.

**Comment by coolreader18** [comment]
I think the commit hash sounds good, once we settle on a consistent bytecode format we can do something else.

**Comment by coolreader18** [comment]
Acutally, it might be good to use the hash of the contents of the `bytecode` directory, since we know that if any of that changes then the bytecode format would likely change.

**Comment by coolreader18** [comment]
Yeah, here's some quick and dirty code that'll hash the `rustpython_bytecode` crate:

```rust
use std::collections::hash_map::DefaultHasher;
use std::fs::File;
use std::hash::Hasher;
use std::io::{self, Read};
use walkdir::WalkDir;

fn main() -> io::Result<()> {
    let mut hasher = DefaultHasher::new();
    for entry in WalkDir::new("../RustPython/bytecode/")
        .into_iter()
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_file())
    {
        for byte in File::open(entry.path())?.bytes() {
            hasher.write_u8(byte?);
        }
    }
    let hash = hasher.finish();
    println!("{}", hash);
    Ok(())
}
```
It's pretty quick, and could probably be put into a `build.rs` file pretty easily.

**Comment by windelbouwman** [comment]
I like the idea of the commit hash only on the rustpython-bytecode crate. Since this is the code being serialized. Instead of hashing the directory ourselves, is there some flag in the rust compiler which maintains a hash of the sourcecode? Cargo will also hash the sourcecode, so there should be a hash of the code somewhere in the rustcompiler we could use.

**Comment by windelbouwman** [comment]
Maybe something like this would be good: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/fingerprint/struct.Fingerprint.html

**Comment by windelbouwman** [comment]
If you take a look in the `target/debug/build` folder, you will find folders with a crate name and a magic hash. It would be good if we could use that hash somehow.
