### ISSUE TITLE
How should we list contributors in Cargo.toml(s)?

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1094]
Now that we're going to start publishing our crates (#838), how what should we put for `authors`  in the `Cargo`s`.toml`? All the crates have different authors listed, usually just whoever first created that package. What should we change them to to keep them consistent across everything? [Relevant section in cargo docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-authors-field-optional)

**Comment by windelbouwman** [comment]
As I wrote a fairly large portion of the code, I don't mind being put as author. I prefer however something like rustpython team or something like that. Is this possible?

**Comment by windelbouwman** [comment]
As package names I would prefer this:
- `rustpython-parser`
- `rustpython-compiler`
- `rustpython-bytecode`
- `rustpython-vm`

**Comment by windelbouwman** [comment]
I propose to release rustpython-parser as the first package, since this is the least changing one.

**Comment by coolreader18** [comment]
I think we could, maybe something like:
```toml
authors = ["RustPython contributors <github.com/RustPython/RustPython/contributors>"]
```

**Comment by windelbouwman** [comment]
I propose:
```toml
authors = ["RustPython Team"]
```

**Comment by coolreader18** [comment]
Sounds good to me!

**Comment by windelbouwman** [comment]
I'll make a PR for this.

**Comment by hung44zzz** [comment]
Unscribe me
