### ISSUE TITLE
f-string with bool expression and if-expression inside

### ISSUE THREAD

**Issue by mkurnikov** [RustPython/RustPython#1099]
All these fail to parse
```
f'{True or True}'
f'{1 == 1}'
f'{"0" if True else "1"}'
```

**Comment by windelbouwman** [comment]
This is strange. Any clue why this is the case?

**Comment by windelbouwman** [comment]
Pull request #1112 improves diagnostics on f-strings a bit. That might help.

**Comment by windelbouwman** [comment]
I found the reason, and fixed it. Thanks for reporting!

**Comment by windelbouwman** [comment]
Will be fixed when #1115 is merged. Please take a look at the change if you wish.
