### ISSUE TITLE
`obj*::get_value` functions have unexpectedly differing signatures

### ISSUE THREAD

**Issue by OddBloke** [RustPython/RustPython#110]
In `objint.rs` we have:

```rust
pub fn get_value(obj: PyObjectRef) -> i32 {
```

but in `objstr.rs` we have:

```rust
pub fn get_value(obj: &PyObjectRef) -> String {
```

Obviously return types are going to be different, but having the same calling convention would be good.

**Comment by OddBloke** [comment]
Perhaps something like:

```rust
trait FromPyObject {
    fn from_pyobject(obj: &PyObjectRef) -> Self;
}

impl FromPyObject for i32 {
    fn from_pyobject(obj: &PyObjectRef) -> i32 {
        ...
    }
}
```

might do the trick; then:

```rust
let x = objint::getvalue(obj);
```

would become something like:

```rust
let x = i32::from_pyobject(obj)
```

**Comment by OddBloke** [comment]
Once TryFrom is stabilised (https://github.com/rust-lang/rust/issues/33417) we may also want to look at implementing that, so we can report errors out more nicely.

**Comment by windelbouwman** [comment]
Okay, I'll go for FromPyObject trait!

**Comment by windelbouwman** [comment]
I came across this when I realized that sometimes cloning a python object ref if overkill, and passing a reference is enough. This is such an example!

**Comment by OddBloke** [comment]
I stopped because I thought I was running in to problems with subclasses of types, but I think those problems were actually caused by #112 and I failed to appropriately diagnose them.

**Comment by youknowone** [comment]
Now every `get_value` has same input signature using `&PyObjectRef`. How about change thi s issue to `TryFrom` or `FromPyObject` one or close this one and create a new one?

**Comment by youknowone** [comment]
I also fixed get_value signature problem several weeks ago
