### ISSUE TITLE
Implement `defaultdict`

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#1133]
Implement `defaultdict` in vm/src/stdlib/collections.rs

This should be a subclass of dict, implementing the `__missing__` method.

**Comment by coolreader18** [comment]
I've started working on this, before I even saw this issue!

**Comment by windelbouwman** [comment]
How could we improve the situation such that we can implement defaultdict in rust by inheriting dict?

I was thinking something like this could be good:
```rust
struct PyDefaultDict {
   normal_dict: PyDictRef,
   factory_func: PyObjectRef,
}

impl PyDefaultDict {
    #pymethod(name="__missing__")
    fn missing() {
        // implement __missing__
    }
}

fn mk_module() {
   let default_dict_type = ?;
   PyDict::extend_class(default_dict_type);
   PyDefaultDict::extend_class(default_dict_type);
}

```

**Comment by coolreader18** [comment]
Maybe we could have the self parameter accept a type that implements `Into<PyRef<Self>>`?

**Comment by windelbouwman** [comment]
@coolreader18 should we close this for now, since we have a python version of the defaultdict?
