### ISSUE TITLE
A Rust class can't detect methods on a Rust subclass of itself.

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1138]
e.g. when trying to implement `collections.defaultdict` defining `__missing__` on `defaultdict` doesn't get detected from `dict.__getitem__`.

**Comment by coolreader18** [comment]
Can't imagine this still happens, though who knows...

**Comment by coolreader18** [comment]
I'll test it sometime soon

**Comment by fanninpm** [comment]
Any progress on this?

**Comment by youknowone** [comment]
I have no idea what it is. Let's open it again once we reveal what it is.
