### ISSUE TITLE
Duplicate keyword arguments should be a SyntaxError

### ISSUE THREAD

**Issue by OddBloke** [RustPython/RustPython#116]
We currently treat them as a TypeError, but CPython rejects them as invalid syntax.

(This issue will be introduced in #115, but is small enough for me to come back and fix it after that has landed.)

**Comment by windelbouwman** [comment]
@OddBloke did you find some time to look into this? Is this issue still relevant?

**Comment by apatrushev** [comment]
Looks like it is still relevant:
```bash
$ rustpython -c 'x=lambda a: None; x(a=1,a=2)'
[no output]
$ python -c 'x=lambda a: None; x(a=1,a=2)'
  File "<string>", line 1
SyntaxError: keyword argument repeated
```

**Comment by xarus01** [comment]
I'd like to give a try on this issue.
I guess constructor for PyFuncArgs needs to check if the key already exists and raise SyntaxError

**Comment by coolreader18** [comment]
I think because it's a syntax error, you should do it in the compiler.
