### ISSUE TITLE
sitecustomize.py is a symlink 

### ISSUE THREAD

**Issue by andrew-ld** [RustPython/RustPython#1164]
https://github.com/RustPython/RustPython/blob/master/Lib/sitecustomize.py

**Comment by coolreader18** [comment]
Woops, that was my bad, when I copied the file over it probably didn't copy the file contents but rather just the link.

**Comment by coolreader18** [comment]
Actually wait no that's probably configuration specific to my system, the best course of action is probably to remove it.
