### ISSUE TITLE
Extend the socket module

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#1176]
The `socket` module is still incomplete. Many methods and types are missing. To add methods to this module, edit the file `vm/src/stdlib/socket.rs` accordingly.

**Comment by mpajkowski** [comment]
Ok, I'm working on {{get/set} gid,uid,egid and related stuff.

**Comment by posutsai** [comment]
Hi, I would like to contribute to extending the socket module. Are there any remaining methods which are not assigned to anybody? Should I open another issue and specify which method I want, preventing others from doing the same thing? Or which method is the first priority?

**Comment by windelbouwman** [comment]
@posutsai you could add a series of checkboxes in this issue, and mention what you implement. There is not a fixed list, but there is a helper script to determine the missing methods, called [`whats_left.sh`](https://github.com/RustPython/RustPython/blob/master/whats_left.sh)

I think it is good to mention here what you will start on.

**Comment by palaviv** [comment]
> Hi, I would like to contribute to extending the socket module. Are there any remaining methods which are not assigned to anybody? Should I open another issue and specify which method I want, preventing others from doing the same thing? Or which method is the first priority?

I would recommend trying to implement the methods needed by `socketserver` as it is something that would be great to add. From a quick look we should add:

- [ ] gettimeout
- [ ] setsockopt
- [ ] shutdown

**Comment by posutsai** [comment]
@palaviv 
I start with `setsockopt` function. However, I meet issues at the beginning and I can't find a great existing solution on google. I would like to hear your comment or any suggestion.

According to the document on the official [Python website](https://docs.python.org/3/library/socket.html#socket.socket.setsockopt), `setsockopt` takes three or four arguments. However, as I know, Rust doesn't provide function overloading. It is possible to do it with trait if it takes three arguments in each implementation.

I have referred to the [implementation](https://github.com/RustPython/RustPython/blob/master/vm/src/stdlib/socket.rs#L305) of `sendto` and there is also an optional argument `flag` on the [document](https://docs.python.org/3/library/socket.html#socket.socket.sendto). Seems like current implementation simply ignores the optional argument.

Could you give me some hint to implement the function? Sorry for asking such an elementary question, since I just start to learn rust and try to understand it deeper by solving a real problem.

**Comment by windelbouwman** [comment]
Hi @posutsai ,

Your best option at this point would be to use `OptionalArg` in some way like this:

```rust
fn setsockopt(level: PyIntRef, optname: PyObjectRef, value: OptionalArg<PyObjectRef>, optlen: OptionalArg<PyObjectRef, vm: &VirtualMachine) {
    // handle value and optlen combinations here:
    if value.is(vm.get_none()) {
          if let Present = oplen {
          } else {
              return Err(vm.new_type_error("optlen must be supplied when value is None"));
          }
    } else {
          if let Present = oplen {
              return Err(vm.new_type_error("optlen must not be supplied when value is not None"));
          }
    }
}
```

We did not yet build function polymorphism macros into rustpython, and rust does not support it, so this is currently the way to go forwards.

**Comment by rodrigocam** [comment]
Hello, may I implement `sendfile` method?

**Comment by coolreader18** [comment]
@rodrigocam Yeah, feel free to take a shot at it!

**Comment by rodrigocam** [comment]
What do you think of this implementation? I'm using the algorithm `os::read` uses to fill the byte buffer that we are going to send.

```
    #[pymethod]
    fn sendfile(&self, fd: i64, offset: OptionalArg<u64>, count: OptionalArg<u64>, vm: &VirtualMachine) -> PyResult<usize> {
        let mut file = rust_file(fd);
        let mut bufsize: u64 = 0;

        if let Ok(metadata) = file.metadata() {
            bufsize = metadata.len();
        }

        if let OptionalArg::Present(c) = count {
            bufsize = c;
        }

        let mut buffer = vec![0u8; bufsize as usize];

        let n = file
            .read(&mut buffer)
            .map_err(|err| err.into_pyexception(vm))?;

        buffer.truncate(n);

        let bytes = PyBytesLike::try_from_object(vm, vm.ctx.new_bytes(buffer))?;
        self.send(bytes, vm)
    }

```

**Comment by coolreader18** [comment]
@rodrigocam looks pretty good! Do you wanna make a PR for that?

**Comment by rodrigocam** [comment]
@coolreader18 done! https://github.com/RustPython/RustPython/pull/2311

**Comment by hk1997** [comment]
Hi, I would like to contribute to this.
Is it still open?
Are there some methods which need to be implemented?

**Comment by DimitrisJim** [comment]
From a quick comparison I see `gethostbyname_ex` missing and a good number of the constants that are exported.

**Comment by nbykovsky** [comment]
Hi there, I want to start contributing with something. Are here any methods which needs to be implemented?

**Comment by DimitrisJim** [comment]
my previous comment still stands, (also, try running `whats_left` and seeing what it reports for socket).

**Comment by varun-krishnan** [comment]
if no one has taken gethostbyname_ex, can I take a crack at it?

**Comment by InfRandomness** [comment]
Hi, I want to take a shot at something(s) from it, 
I tried running `./whats_left | grep socket`
is everything appearing in the stdout missing?

**Comment by youknowone** [comment]
yes, exactly

**Comment by youknowone** [comment]
it seems most of features are done but many properties left
