### ISSUE TITLE
Implement the 'ascii' method

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#1179]
Currently we are lacking the [ascii builtin method](https://docs.python.org/3/library/functions.html?highlight=ascii#ascii).

This is a good starting issue. Go ahead, and try to modify `vm/src/builtins.rs` as you see fit!

**Comment by corona10** [comment]
@windelbouwman 
Looks like it's essentially implementing PyObject_ASCII.
Can I take a look?

**Comment by windelbouwman** [comment]
Sure! Good luck! May the source be with you ;)
