### ISSUE TITLE
os.getppid() < os.getpid()

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#1214]
In the [file `tests/sniptters/stdlib_os.py` on line 269](https://github.com/RustPython/RustPython/blob/master/tests/snippets/stdlib_os.py#L269), this comparison is made:

`assert os.getppid() < os.getpid()`

Is this always true? The test failed once, but when I re-run, it passed?

**Comment by mpajkowski** [comment]
resolves #1240
