### ISSUE TITLE
import with submodules doesn't work properly

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1216]
## Feature

e.g., `import os.path`. What this should do is import os with a fromlist of `('path',)`. Or, `import unittest.util`. However, what this actually does is load `'os.path'` or `'unittest.util'` into `locals` as a string with the dot in it:

```py
>>>>> import os.path
>>>>> os
Traceback (most recent call last):
  File "<stdin>", line 0, in <module>
NameError: "name 'os' is not defined"
>>>>> import unittest.util
>>>>> unittest
Traceback (most recent call last):
  File "<stdin>", line 0, in <module>
NameError: "name 'unittest' is not defined"
>>>>> locals()
{'os.path': <module object at 0x560d41584960>, 'unittest.util': <module object at 0x560d4157cd70>}
```

## Python Documentation

n/a

**Comment by windelbouwman** [comment]
Is this related to the fact that `import os` does not work on the demo site?

**Comment by yjhmelody** [comment]
I even can't load `os` module in my win10 and ubuntu. Ah, though not the same problem with you.

**Comment by coolreader18** [comment]
Have you set `RUSTPYTHONPATH=.../RustPython/Lib`?

**Comment by palaviv** [comment]
@coolreader18 I think this was fixed. Can we close this?

**Comment by coolreader18** [comment]
Yeah, this was fixed a while ago.
