### ISSUE TITLE
RustPython object truth value not compact for Cpython

### ISSUE THREAD

**Issue by Lynskylate** [RustPython/RustPython#1218]
RustPython judgment doesn't use \_\_len\_\_.
```python
class Test:
   def __len__(self):
       return False

test = Test()
if test:
    print("Shouldn't print")
# CPython output:
# >>>
# RustPython output: 
# >>> Shouldn't print

```

[Cpython Document](https://docs.python.org/3/library/stdtypes.html#truth-value-testing),
>By default, an object is considered true unless its class defines either a __bool__() method that returns False or a __len__() method that returns zero, when called with the object. 1 Here are most of the built-in objects considered false.

When VM eval JumpIf, just convert the PyObject to bool,  We need to increase the judgment of the length
```rust
            bytecode::Instruction::JumpIf { target } => {
                let obj = self.pop_value();
                let value = objbool::boolval(vm, obj)?;
                if value {
                    self.jump(*target);
                }
                Ok(None)
            }

            bytecode::Instruction::JumpIfFalse { target } => {
                let obj = self.pop_value();
                let value = objbool::boolval(vm, obj)?;
                if !value {
                    self.jump(*target);
                }
                Ok(None)
            }
```

**Comment by silmeth** [comment]
A very small nitpick – to really test compliance with the documentation in this case I think your `Test` class should rather return `0` and not `False` in its `__len__()`.

But, on the other hand, testing for `__len__()` returning `False` probably is an interesting edge-case test for compatibility with CPython too (even if the docs don’t explicitly mention this case).

**Comment by Lynskylate** [comment]
> A very small nitpick – to really test compliance with the documentation in this case I think your `Test` class should rather return `0` and not `False` in its `__len__()`.
> 
> But, on the other hand, testing for `__len__()` returning `False` probably is an interesting edge-case test for compatibility with CPython too (even if the docs don’t explicitly mention this case).

Sorry, It `s my mistake. CPython's PyObject_IsTrue downcast res to int, so this result can also be reproduced with 0.
