### ISSUE TITLE
Create a demo to run on top of redox os

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#125]
It would be nice if we could run this code somehow on top of redox os (https://www.redox-os.org/)

**Comment by windelbouwman** [comment]
@coolreader18 you actually did this. Could you describe somewhere how to do this? Then we can close this issue.

**Comment by coolreader18** [comment]
Should I put an article in the wiki?

**Comment by windelbouwman** [comment]
Yes, I think that would be good!

**Comment by coolreader18** [comment]
Alright, I published some instructions (https://github.com/RustPython/RustPython/wiki/Redox-OS), let me know if they work.

**Comment by windelbouwman** [comment]
Cool! I did not try, since my laptop has no space left, but it should work!
