### ISSUE TITLE
Can't call __new__ directly to create instances.

### ISSUE THREAD

**Issue by cthulahoops** [RustPython/RustPython#126]
This should work, but doesn't:

```
int.__new__(int, 5)
```

I think ```type.__new__``` gets called instead of ```int.__new__```, given this:

```
>>>>> object.__new__(object) 
<class 'type'>
```

I was pretty sure there was a problem with getattribute, but I've been waiting for a good example to fix.

**Comment by windelbouwman** [comment]
This works now! I do not know what fixed it, but it works :)

**Comment by cthulahoops** [comment]
Uh... no, I'm wrong. That's only during type creation, not object creation.

The correct implementation of type.__getattribute__ fixes this. (And we don't even need another special case.)

**Comment by Mec-iS** [comment]
In theory directly calling `__new__` in Python should never be done to avoid weird side-effects. The constructor to override is always `__init__`.

**Comment by windelbouwman** [comment]
@cthulahoops this issue can now be closed, right?

**Comment by cthulahoops** [comment]
Yes, I think this is all fixed now.
