### ISSUE TITLE
[good first issue] implement os.access

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1263]
## Feature

`os.access` lets you check to see whether a user has access to a file or not. It is used by a few libraries in the standard library, namely `webbrowser`, which is depended on by `antigravity`, which is just a fun one IMO.

## Python Documentation

https://docs.python.org/3/library/os.html#os.access

## Implementation

You can look at using [`std::fs::Permissions`](https://doc.rust-lang.org/std/fs/struct.Permissions.html) to implement this.

**Comment by Nimpruda** [comment]
Hi,
I'd like to try and implement this but i'm not sure how to proceed and where to put it. I guess it's in vm/src/stdlib/os.rs ?

**Comment by Nimpruda** [comment]
https://github.com/Nimpruda/RustPython/commit/6f78bca8ee41e33728ceaa180bb455050931b343 
Would something like that do the trick for the R_OK and F_OK? I'm not sure how I am supposed to use vm tho.

**Comment by kluid** [comment]
@Nimpruda If you feel free, Can I try to implement os.access function roughly?
