### ISSUE TITLE
Sub-classes of `str` appear to just operate as aliases of `str`

### ISSUE THREAD

**Issue by OddBloke** [RustPython/RustPython#130]
```py
>>>>> class String(str):
.....     def foo(self):
.....         return "foo"
..... 
>>>>> String()
'' 
>>>>> String().foo()
Traceback (most recent call last):
  File <unknown>, line 0, in <module>
AttributeError: RefCell { value: [PyObj class "str"] } object has no attribute foo
>>>>> type(String())
<class 'str'> 
```

**Comment by OddBloke** [comment]
@cthulahoops This seems like something you'd have the best insight on.

**Comment by cthulahoops** [comment]
I fixed this issue for ints yesterday. ```str_new``` ignores the ```cls``` parameter it is passed and always uses ```str_type```. ```str_new``` needs rewriting to look more like ```str_int```.

(I couldn't use arg_check! for int_new because it needs to check issubclass rather than isinstance.)

**Comment by cthulahoops** [comment]
(There's a deeper issue that I'm aware of but avoiding. It is possible to set instance attributes on subclasses of built-in types, but we don't currently have a dictionary to store these in.)

**Comment by windelbouwman** [comment]
I think the solution here might be to get rid of the PyObjectKind::Instance and give each pyobject a dict or `Option<PyObjectRef> dict` member. This way each object can have some extra attributes. In any case, I think Instance pyobjectkind is an obvious kind, since all objects are instances.

**Comment by windelbouwman** [comment]
Yes, this should be exactly the idea!

Using `x.__dict__` will simply return the attributes member as a dict I guess?

**Comment by cthulahoops** [comment]
Yes, that's what I was thinking, though it might be tricky to make sure:

```
x.__dict__ is x.__dict__
```

An issue we already have in this case:

```
>>>>> bool.__mro__ is bool.__mro__
False
```
