### ISSUE TITLE
try-else without except clause is illegal

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#1300]
## Feature

The code is SyntaxError in cpython, but legal in RustPython

```python
try:
    pass
else:
    pass
```

## Python Documentation

https://docs.python.org/3/tutorial/errors.html#handling-exceptions

```
The try … except statement has an *optional* else clause,
```

**Comment by windelbouwman** [comment]
Nicely spotted! I fixed it in the grammar file.
