### ISSUE TITLE
Suggestion: Look at Beeware's Ouroboros

### ISSUE THREAD

**Issue by pradyunsg** [RustPython/RustPython#1317]
https://beeware.org/project/projects/libraries/ouroboros/ is an implementation of a substantial portion of the Python standard library, in Python.

**Comment by windelbouwman** [comment]
Hi @pradyunsg ,

Thank you for this suggestion! We already have a reference to this project in the readme file. For now, we take the approach of copy paste from the cpython library.

I will close this issue for now, thanks for your suggestion! Feel free to re-open if you think this needs to be discussed further.
