### ISSUE TITLE
rustpython-vm compile failed with cursive

### ISSUE THREAD

**Issue by Riey** [RustPython/RustPython#1335]
![Screenshot_20190901_005242](https://user-images.githubusercontent.com/14910534/64066310-f5848c80-cc52-11e9-80d5-e3d12e8c80dd.png)

Is it possible to raise the chrono version to 0.4.7?

**Comment by Tom1380** [comment]
What reasons might stop us from raising it?

**Comment by Tom1380** [comment]
I ran the tests with crono set to 0.4.7 and they pass.

**Comment by coolreader18** [comment]
Sorry for not looking into this issue earlier; you should be able to bump the chrono version. Feel free to make a PR for it if you want, otherwise I could do it in a bit.

**Comment by Tom1380** [comment]
This should be closed @coolreader18.
