### ISSUE TITLE
'is' keyword not working

### ISSUE THREAD

**Issue by Riey** [RustPython/RustPython#1345]
## Feature

```python
'123' is '123'
```

In CPython this is True but I get False in RustPython

**Comment by coolreader18** [comment]
This is because we don't have [string interning](https://docs.python.org/3/library/sys.html#sys.intern), which is done by default for string less than 20 characters in length, I believe.

**Comment by cthulahoops** [comment]
I'd add that this is an implementation detail, so there's no requirement that we match CPython behaviour here. We probably will want string interning, but we don't have to.
