### ISSUE TITLE
When call global twice for the same variable, SyntaxError occurs.

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#1353]
## Feature

```python
a = []
def f(b):
    global a
    global a  # Generate error only in RustPython
    a.append(b)
    print(a)

f(3)
print(a)
```
The code above generates the following error:
(when call global twice for the same variable, an error occurs.)
### Actual result
```bash
Hyeockz:RustPython hyeockjinkim$ cargo run e.py 
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/rustpython e.py`
SyntaxError: name 'a' is used prior to global declaration at line 0 column 0
```
### Expected result
```bash
[3]
[3]
```

**Comment by HyeockJinKim** [comment]
If this issue is valid, can I take it?

**Comment by coolreader18** [comment]
Yup!

**Comment by corona10** [comment]
@coolreader18, @windelbouwman  cc @youknowone 

FYI, @HyeockJinKim is a mentee of OSS program named `Contributhon` of Korea government.
It's a similar program like GSoC.
I am mentoring @HyeockJinKim for a month.

There are also some people(6-10) who want to contribute RustPython project for the first time.
so they need our help too.

If the members of RustPython project members are okay
Can we add a tag to assign issues to them which can specify `Contributhon 2019` like for sprint tag? 
we are now doing for gpython project but I don't have a permission for RustPython :)
(e.g https://github.com/go-python/gpython/issues/72 )

**Comment by coolreader18** [comment]
That sounds great, I'll add it right now.
