### ISSUE TITLE
[Contributhon2019] Implement sys._git

### ISSUE THREAD

**Issue by corona10** [RustPython/RustPython#1358]
sys._git is not implemented yet.
This feature can be easily implemented by using
`option_env!("RUSTPYTHON_GIT_HASH")``

```python
>>> sys._git
('CPython', 'v3.7.2', '9a3ffc0492')
```

p.s  @coolreader18 @youknowone 
This issue needs a `contributhon 2019` label.

**Comment by ChJR** [comment]
May I take this issue?

**Comment by corona10** [comment]
@ChJR Please go a head

**Comment by coolreader18** [comment]
You could also use the [`version`](https://github.com/RustPython/RustPython/blob/master/vm/src/version.rs) module in `rustpython_vm`.

**Comment by Writtic** [comment]
@ChJR 
How is it going? I suppose this issue is little bit dragged, So may I take this issue?

**Comment by ChJR** [comment]
The PR of this issue will be added today. I am working on some minor issues of this.
