### ISSUE TITLE
nonlocal declaration doesn't generate syntax error

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#1360]
## Feature
```python
def a():
    nonlocal a
```
This code generate syntax error, but RustPython doesn't.
(nonlocal declaration for variable in upper scope problem)

### Expected Result
```bash
File "c.py", line 2
    nonlocal a
SyntaxError: no binding for nonlocal 'a' found
```
### Actual Result
```bash
Finished dev [unoptimized + debuginfo] target(s) in 0.12s
Running `target/debug/rustpython c.py` # No Error
```

**Comment by HyeockJinKim** [comment]
If this issue is valid, can I take this?

**Comment by coolreader18** [comment]
Yep!

**Comment by coolreader18** [comment]
Nevermind, it should be as simple as moving the name registration for functions to after processing the body
