### ISSUE TITLE
Implement rest of itertools API

### ISSUE THREAD

**Issue by corona10** [RustPython/RustPython#1361]
## Feature
There are some APIs does not implement yet.
Let's implement them

## Python Documentation
https://docs.python.org/3/library/itertools.html

**Comment by seeeturtle** [comment]
can i try it?

**Comment by corona10** [comment]
@seeeturtle 
Sure go ahead.
But please leave a comment which API you will work with so that rest of APIs can be implemented by other Contributhon2019 participants.

**Comment by corona10** [comment]
@coolreader18
 Can you assign this issue to @seeeturtle ? 
(There may be additional mentees who want to work with)

**Comment by seeeturtle** [comment]
> Sure go ahead.
> But please leave a comment which API you will work with so that rest of APIs can be implemented by other Contributhon2019 participants.

sure, i'll try to implement `Combinatoric iterators`.

**Comment by Thrimbda** [comment]
hello, can I try `itertools.groupby`?

**Comment by coolreader18** [comment]
Yep, go ahead!

**Comment by corona10** [comment]
I am working on `itertools.cycle` :)

**Comment by pitachips** [comment]
I am working on `itertools.compress`

**Comment by dralley** [comment]
What is "taken" and who it is assigned to.  I will try to keep this updated including what gets completed.

## Infinite Iterators

- [ ] ```itertools.count()```
- [x] ```itertools.cycle()``` @corona10 
- [x] ```itertools.repeat()``` @dralley

## Iterators terminating on the shortest input sequence

- [x] ```itertools.accumulate()``` @j30ng 
- [ ] ```itertools.chain()```
- [ ] ```itertools.chain.from_iterable()```
- [x] ```itertools.compress()``` @pitachips 
- [ ] ```itertools.dropwhile()```
- [ ] ```itertools.filterfalse()```
- [x] ```itertools.groupby()``` @Thrimbda 
- [ ] ```itertools.isslice()```
- [ ] ```itertools.starmap()```
- [x] ```itertools.takewhile()``` @dralley
- [x] ```itertools.tee()``` @j30ng 
- [ ] ```itertools.zip_longest()```

## Combinatoric iterators

- [x] ```itertools.product()``` @seeeturtle 
- [x] ```itertools.permutations()``` @seeeturtle 
- [x] ```itertools.combinations()``` @seeeturtle 
- [x] ```itertools.combinations_with_replacement()``` @seeeturtle

**Comment by Space0726** [comment]
Hello, Can I try itertools.zip_longest()?

**Comment by dralley** [comment]
No need to ask, just say you're working on it so that others know and don't duplicate work

**Comment by yashaslokesh** [comment]
I'll work on `itertools.count()`

**Comment by yashaslokesh** [comment]
I’ll work on `itertools.chain.from_iterable()` then

**Comment by seeeturtle** [comment]
@dralley , can you remove me from taking combinatoric iterators except `product`?

**Comment by dralley** [comment]
@corona10 Are you still working on ```itertools.cycle()```?

@Thrimbda Are you still working on ```itertools.groupby()```?

@Space0726 Are you still working on ```itertools.zip_longest()```?

**Comment by Space0726** [comment]
> @Space0726 Are you still working on `itertools.zip_longest()`?

Yes, I still working on `itertools.zip_longest()` and I had finished it once.
It works fine but it was working a bit differently than CPython's `itertools.zip_longest()`, so I was thinking about it. Should I send a PR first?

**Comment by dralley** [comment]
@Space0726 Yeah, probably just put a PR up, and maybe the issues can be found during review.  If it's got test snippets for the ways in which it isn't working properly, then it won't be merged until it passes the CI anyways.

**Comment by dralley** [comment]
I'll take ```cycle``` and ```groupby``` unless someone else wants to (re)claim them. @corona10 @Thrimbda

**Comment by corona10** [comment]
@dralley Please go a head :)

**Comment by dralley** [comment]
The last one remaining is ```itertools.groupby()``` and it's pretty nasty.  I've had it on the backburner for a while and haven't made much progress.  If anyone else comes along and wants to tackle it, feel free to do so.

**Comment by Space0726** [comment]
> The last one remaining is `itertools.groupby()` and it's pretty nasty. I've had it on the backburner for a while and haven't made much progress. If anyone else comes along and wants to tackle it, feel free to do so.

It might be take some time, but I'll try it.

**Comment by skinny121** [comment]
I'm currently looking at implementing `itertools.groupby` for #1983.
