### ISSUE TITLE
[::-1] returns wrong index for 'range' type

### ISSUE THREAD

**Issue by xarus01** [RustPython/RustPython#1373]
## Code
```
a = range(10)
a = a[::-1]
print(a)
```

## Expected
```
range(9, -1, -1)
```

## Result
```
range(0, 10, -1)
```

**Comment by dralley** [comment]
Another slightly more complicated example:

RustPython

```
>>>>> range(0, 10, -1)[::-1]
range(0, 10)
```

CPython

```
>>> range(0, 10, -1)[::-1]
range(1, 1)
```

I'd love to work on this as a first issue, if others wouldn't mind.

**Comment by vazrupe** [comment]
can I take this?

**Comment by dralley** [comment]
I've already started but if I'll let you know if I give up on it.  I know where the problem is, though - ```PyRange::getitem```

**Comment by dralley** [comment]
Making progress.  Found another range slicing bug which I will also try to fix.

RustPython

```
>>>>> range(0, -10)[::0]
range(0, -10, 0)
```

CPython

```
>>> range(0, -10)[::0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: slice step cannot be zero
```

**Comment by dralley** [comment]
@vazrupe Sorry!  But, I would love for you to review my PR :)
