### ISSUE TITLE
str.format() error with iterable object

### ISSUE THREAD

**Issue by lntuition** [RustPython/RustPython#1382]
# Feature
``` python3
a = (10, 20);
print("a[0] : {0[0]}, a[1] : {0[1]}".format(a))
```

str.format is not working with iterable object.

# Actual result
```
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    print("a[0] : {0[0]}, a[1] : {0[1]}".format(a))
KeyError: 0[0]
```

# Expected result
```
a[0] : 10, a[1] : 20
```

**Comment by kluid** [comment]
Here.
https://github.com/RustPython/RustPython/blob/8ac743dd6ecc3bedcbf44cab4289583e3187ddde/vm/src/format.rs#L514-L546

Literlal `0[0]` and `0[1]` retruned as `FormatPart::KeywordSpec("0[0]", "")` and `FormatPart::KeywordSpec("0[1]", "")`.

**Comment by kluid** [comment]
Here.
https://github.com/RustPython/RustPython/blob/af10174cf8ae66ccd7704f295247261268a5c38e/vm/src/format.rs#L514-L546

format expr `{0[0]}` is passed as parameter, this function returns `Ok(FormatSpec::KeywordSpec("0[0]", ""))`.
I think `{0[0]}` should be parsed to IndexSpec, and `[0]` is evaluated by '__getitem__'.

**Comment by lntuition** [comment]
thank you for your comment :) I was considered that we need to make another spec...
I will resolve this issue after resolving other issue from `objint`

**Comment by lntuition** [comment]
I found this is fixed on master !
