### ISSUE TITLE
Indentation Error does not occur when no value is entered after for

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#1385]
### Expected Result
```python
>>> for i in range(10):
... 
  File "<stdin>", line 2
    
    ^
IndentationError: expected an indented block
```

### Actual Result
```python
>>>>> for i in range(10):
..... 
..... 
..... 
..... 
..... 
..... 
..... 
```

In the python3 shell, if no value is entered when `Indentation` is required, (such as for: or if: or def, etc...), an `IndentationError` should be raised.

**Comment by coolreader18** [comment]
Hmm, maybe we could check if the previous syntax error was in the same place as the current one, and if it was then give an error?

**Comment by dralley** [comment]
Right now it looks like there is no ```IndentationError``` at all.  Likewise, ```TabError``` doesn't exist.

**Comment by dralley** [comment]
Using the following input from StackOverflow

```
command = "IDENTIFY"

if command == 'HOWMANY':
    opcodegroupr = "A0"
    opcoder = "85"
elif command == 'IDENTIFY':
opcodegroupr = "A0"
opcoder = "81"
```

### Expected

```
  File "test2.py", line 7
    opcodegroupr = "A0"
               ^
IndentationError: expected an indented block
```

### Actual

```
SyntaxError: Got unexpected token 'opcodegroupr' at line 7 column 1
```

**Comment by sanxiyn** [comment]
I implemented IndentationError, but it does not resolve the original issue.
