### ISSUE TITLE
Display issue of Unsupported Characters in chr()

### ISSUE THREAD

**Issue by rls1004** [RustPython/RustPython#1390]
### Expected Result
```
>>> chr(999999)
'\U000f423f'
```

### Actual Result
```
>>>>> chr(999999)
'󴈿'
```

In Python 3, unsupported characters are output as hexadecimal values.

**Comment by makarchuk** [comment]
So the actual problem is `__repr__` implementation for `str`, which is different.
`chr` behaves the same, but charachter is represented in shell differently in `cpython` and `Rustpython
cpython: 
```
In [1]: c = chr(999999)

In [2]: c
Out[2]: '\U000f423f'

In [3]: print(c)
󴈿
```
RustPython: 
```
>>>>> c = chr(999999)
>>>>> c
'󴈿'
>>>>> print(c)
󴈿
```

**Comment by makarchuk** [comment]
So, the actual implementation of `__repr__` in `cpython` is pretty convoluted: [/Objects/unicodeobject.c#L12701](https://github.com/python/cpython/blob/c02b41b1fb115c87693530ea6a480b2e15460424/Objects/unicodeobject.c#L12701), but I think I will try and make somewhat compatible implementation.

**Comment by makarchuk** [comment]
I submited a PR (#1470). That was pretty easy thanks to Rust awesomeness in strings manipulation and nice unicode libs
