### ISSUE TITLE
"entry level" contributor issues?

### ISSUE THREAD

**Issue by immersinn** [RustPython/RustPython#1395]
Saw the project and wanted to contribute. Was wondering if there were some easier issues in the tracker that a new contributor could work on to become familiar with the project. Perhaps an issue label for these types of issues?

**Comment by dralley** [comment]
Yes, please.  This is something that the Servo project does extremely well.  It's a great way to draw in new contributors.

**Comment by palaviv** [comment]
Hi @immersinn and @dralley, We have a few issue tagged with the ["good first issue"](https://github.com/RustPython/RustPython/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) tag. In case you would like some more guidance please join the gitter channel and we would gladly help :smiley:

**Comment by immersinn** [comment]
Awesome, thanks for the pointer!
