### ISSUE TITLE
Replace uses of mem::uninitialized() with MaybeUninit<T>

### ISSUE THREAD

**Issue by dralley** [RustPython/RustPython#1411]
```mem::uninitialized()``` is being deprecated in Rust 1.38 for being able to cause undefined behavior

https://doc.rust-lang.org/std/mem/fn.uninitialized.html

**Comment by coolreader18** [comment]
This is difficult, because we're using `mem::uninitialized` in a place where it can't easily be replaced with `MaybeUninit`, and the benefits we'd gain from maybe figuring out some way around it (a duplicate PyObject type but with `MaybeUninit` for fields?) wouldn't necessarily be worth it.

**Comment by dralley** [comment]
Fixed by https://github.com/RustPython/RustPython/pull/1591

**Comment by silmeth** [comment]
I still am very unsure about the fix, it effectively just replaced `mem::uninitialized()` with `MaybeUninit::uninit().assume_init()` which doesn’t remove any possible previous undefined behaviour.

As I commented on that PR:

> @coolreader18 An uninitialized `PyRef` is created, which holds an uninitialized `Rc<_>`, which then holds an unitialized [`NonNull<RcBox<T>>`](https://doc.rust-lang.org/src/alloc/rc.rs.html#279) – which, by the virtue of being uninitialized, might actually be `null`. That is UB (even if you don’t dereference it). And that is the reason why Rust team changed `mem::uninitialized()` into `mem::MaybeUninit` in the first place.
> 
> If it works now, it might not work in the future. To actually do it safely, you need to first do `prt::write` on `MaybeUninit`, and only then (when you know what bit pattern is at the given pointer), `assume_init()`. At least that’s my understanding.

**Comment by coolreader18** [comment]
I've been thinking about this recently, and I agree with you @silmeth that this isn't ideal. Do you know if it would be undefined behavior if we initialized `Rc<MaybeUninit<PyObject>>`s, `ptr::write` the type and mro, and then casted them to `PyObjectRef`s?

**Comment by silmeth** [comment]
@coolreader18 Not sure, when I was replying to that PR back then I was thinking about something like that:
1. create **`mut`** (?) `Rc<MeybeUninit<PyObject<…>>>`,
2. clone it as `cloned`,
3. create a `PyObject` with `typ` initialized to `PyRef { obj: cloned as Rc<PyObject<…>> }`,
4. `ptr_write` that py object as the content of the `mut Rc` from 1. and call it a day.

But point 3 still smells a bit fishy  – we need to cast `Rc<MaybeUninit<T>>` to `Rc<T>` / `assume_init()` it before anything is written as the value of `Rc`… it might be OK – the `Rc` itself has been initialized, it has a proper pointer (to uninitialized value but still) and a proper ref-count, only the value referenced in it still remains uninitialized – and that still might be UB (?).

You’d need to ask someone with more experience in unsafe.

Also, I think `mut Rc<…>` is needed to safely initialize it  through a `*mut T` (cf. nightly API [`get_mut_unchecked()`](https://doc.rust-lang.org/std/rc/struct.Rc.html#method.get_mut_unchecked) which needs a mutable `Rc`).

As for creating `Rc<MaybeUninit<…>>` first and casting to `Rc<…>` later, that looks like a generally right direction, `Rc` even has (nightly only for now) [`new_uninit()`](https://doc.rust-lang.org/std/rc/struct.Rc.html#method.new_uninit) and [`assume_init()`](https://doc.rust-lang.org/std/rc/struct.Rc.html#method.assume_init) helper methods for creating `Rc<MemUninit<T>>` and then casting it to `Rc<T>`. But I still don’t see how to solve the chicken-and-egg problem.

**Comment by coolreader18** [comment]
I've been playing around in the playground with this and I think I've figured it out. [Here's](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=1f790814f660859c8e87c58f80e8eb97) a basic recreation of what we have now, and `miri` does indeed fail if you try to run it. [Here's](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c92c36bda23469500451b9cf080f7494) what I was sort of thinking about, which `miri` shows only leaks memory which we knew already. I'm not sure if `miri` has any false negatives, but if not I think that this version works pretty well.

**Comment by silmeth** [comment]
Looks good. Clever, you cast pointer to `typ` to `*mut Rc<MaybeUninit<…>>` before writing to it, that should work – an obvious solution to initialize that value I didn’t think of.

As for leaking memory – you create a cycle of ref-counts here, leak is the expected and *intended* behaviour.

I am only unsure about the casts between mutable and immutable pointers from immutable `Rc`.

**Comment by coolreader18** [comment]
> I am only unsure about the casts between mutable and immutable pointers from immutable Rc .

That is slightly violating Rust's safety rules, but I don't think it's that bad. We know that `type_type` and `object_type` are only used here and that there are no immutable references to it that are being read from. We actually might want to put a `Cell` in there though, as just the existence of immutable references to the value you're writing to might be sorta undefined behavior.

**Comment by silmeth** [comment]
@coolreader18 by the way, you don’t need to clone the `object_type` on line 24 in your solution in the playground, as you use it only once. The last `type_type` clone on line 37 is also unnecessary.

The `ptr::write()` on line 43 could also hypothetically unnecessarily leak memory from never-dropped `Vec` that has been used to initialize `type_type`’s `mro` – but since that vec is empty it doesn’t allocate anything, so probably there is no need to worry about dropping it.
