### ISSUE TITLE
Use string internment for constant strings

### ISSUE THREAD

**Issue by dralley** [RustPython/RustPython#1412]
CPython and many other VMs do this, as it can save memory.  Mostly it is a feature, but it results in slightly different behavior of the ```is``` keyword between RustPython and CPython.  Theoretically if someone were relying on that behavior (not terribly common I would imagine, but I'm sure some people do) then their would not work the same on RustPython.

https://medium.com/@bdov_/https-medium-com-bdov-python-objects-part-iii-string-interning-625d3c7319de

**Comment by windelbouwman** [comment]
In general I think this is a good idea. Both for performance reasons as well as for CPython compliance. Is there any limit to the amount of strings which are interned?

**Comment by dralley** [comment]
I don't think so.  I have not looked deeply at the CPython implementation yet, but it seems like the vast majority of compile-time constants (apart from some exceptions) are interned.  I'm not sure if *any* strings are interned at runtime.

https://rushter.com/blog/python-strings-and-memory/

> function and class names
> variable names
> argument names
> constants (all strings that are defined in the code)
> keys of dictionaries
> names of attributes

**Comment by coolreader18** [comment]
Strings passed to `sys.intern()` are, but the VM doesn't decide to intern any strings other than constants.

**Comment by dralley** [comment]
Good point https://docs.python.org/3/library/sys.html#sys.intern

**Comment by youknowone** [comment]
@coolreader18 implemented it
