### ISSUE TITLE
Unicode string indexing differences

### ISSUE THREAD

**Issue by dralley** [RustPython/RustPython#1417]
Courtesy of the ["big list of naughty strings"](https://github.com/minimaxir/big-list-of-naughty-strings/):

CPython

```
>>> t = "Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣"
>>> t[0]
'Ṱ'
>>> t[1]
'̺'
>>> t[2]
'̺'
>>> t[3]
'̕'
>>> t[4]
'o'
>>> t[5]
'͞'
>>> t[6]
' '
>>> t[7]
'̷'
>>> t[8]
'i'
```

RustPython

```
>>>>> t = "Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣"
>>>>> t[0]
'Ṱ̺̺̕'
>>>>> t[1]
'o͞'
>>>>> t[2]
' ̷'
>>>>> t[3]
'i̲̬͇̪͙'
>>>>> t[4]
'n̝̗͕'
>>>>> t[5]
'v̟̜̘̦͟'
>>>>> t[6]
'o̶̙̰̠'
>>>>> 

```

**Comment by dralley** [comment]
Courtesy of the ["big list of naughty strings"](https://github.com/minimaxir/big-list-of-naughty-strings/):

CPython

```
>>> t = "בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ"
>>> t[0]
'ב'
>>> t[1]
'ְ'
>>> t[2]
'ּ'
>>> t[3]
'ר'
>>> t[4]
'ֵ'
>>> t[5]
'א'
>>> t[6]
'ש'
>>> t[7]
'ִ'
```

RustPython

```
>>>>> t = "בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ"
>>>>> t[0]
'בְּ'
>>>>> t[1]
'רֵ'
>>>>> t[2]
'א'
>>>>> t[3]
'שִׁ'
```

**Comment by coolreader18** [comment]
I think the issue is that we're slicing at graphemes instead of `char`s, e.g. the Hebrew vowels and consonants are separate chars but a consonant with a vowel is a single grapheme.

**Comment by coolreader18** [comment]
e.g. `len(str[n])` should always be `0`.

**Comment by dralley** [comment]
@coolreader18 I'm going to start working on this.  It's more than just indexing, it's slicing too.  Could you validate my approach before I use it in more places?

https://github.com/RustPython/RustPython/compare/master...dralley:fix-strings

**Comment by coolreader18** [comment]
Yep, LGTM, I was thinking `.chars()` as well.
