### ISSUE TITLE
No argument with float function do not return 0.0

### ISSUE THREAD

**Issue by lntuition** [RustPython/RustPython#1421]
# Feature
``` python3
print(float())
```

If no argument is given, float function have to return 0.0

# Actual result
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected at least 2 arguments (1 given)
```

# Expected result
```
0.0
```

**Comment by lntuition** [comment]
Wrong label, but i do not have auth. If someone who can change label see this issue, please change label `RFC` to `feat`. thank you

**Comment by dralley** [comment]
Addressed in PR

**Comment by lntuition** [comment]
Oh, I was going to start now. But someone take this issue :)
