### ISSUE TITLE
Integer problem starting with 0

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#1422]
## Feature
```python
0123
```

Integer starting with 0 should raise SyntaxError.
I think it should be fixed in lexer.rs

### Expected Result
```python
>>> 0123
  File "<stdin>", line 1
    0123
       ^
SyntaxError: invalid token
```
### Actual Result
```python
>>>>> 0123
123
```

**Comment by dralley** [comment]
lexer.rs sounds right.

Here is the CPython code that handles it https://github.com/python/cpython/blob/master/Parser/tokenizer.c#L1441
