### ISSUE TITLE
Many objects do not implement `__ne__`.

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#1442]
## Feature
Many objects implement `__eq__` but do not implement `__ne__`.

### Expected result
```python
>>> ''.__ne__('')
False
>>> ''.__ne__('e')
True
>>> [].__ne__([])
False
>>> [].__ne__([32])
True
>>> (1,).__ne__((2,))
True
>>> (1,).__ne__((1,))
False
>>> {}.__ne__({})
False
>>> {}.__ne__({'a':'b'})
True
```

### Actual result
```python
>>>>> ''.__ne__('')
<NotImplementedType object at 0x7ff64ec12000>
>>>>> [].__ne__([])
<NotImplementedType object at 0x7ff64ec12000>
>>>>> (1,).__ne__((2,))
<NotImplementedType object at 0x7ff64ec12000>
>>>>> {}.__ne__({})
<NotImplementedType object at 0x7ff64ec12000>
```

**Comment by makarchuk** [comment]
Should this be closed?

**Comment by HyeockJinKim** [comment]
In addition to the objects mentioned above, there are some objects that __ne__ is not yet implemented. (such as float, complex, ...)

**Comment by youknowone** [comment]
we'd better to have a checklist to make this done.

**Comment by youknowone** [comment]
Once #1642 is done, implementing `__ne__` will be a lot easier than now.

**Comment by felippemr** [comment]
👋 , is this issue still relevant?

**Comment by youknowone** [comment]
I think this is now done. (whats_left.sh doesn't have any `__ne__` in the entry)
thanks!
