### ISSUE TITLE
Implement a better __repr__ in impl_pystruct_sequence

### ISSUE THREAD

**Issue by dralley** [RustPython/RustPython#1448]
The ```impl_pystruct_sequence``` proc macro needs to implement a custom ```__repr__``` to match CPython.

### Expected
```
>>> sys.version_info
sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

### Actual
```
>>>>> sys.version_info
(3, 5, 0, 'alpha', 0)
```

**Comment by tekknolagi** [comment]
I'd like to work on this. Where can I find info on defining methods without `pymethod`? It looks like that's not available in the proc macro.
