### ISSUE TITLE
Code coverage is not being updated

### ISSUE THREAD

**Issue by sanxiyn** [RustPython/RustPython#1472]
#1081 disabled per-PR code coverage job, but it seems the intent was to continue to run it, "maybe once a week cron job". But such cron job was never set up and there was no coverage run since, see https://codecov.io/gh/RustPython/RustPython.

cc @coolreader18 @windelbouwman

**Comment by coolreader18** [comment]
I noticed that recently as well, I could set up a cron job right now to run every week; I was thinking that the beginning of the weekend would be good for Redox tests (#1208) and for this as well.

**Comment by coolreader18** [comment]
Alright, the cron job should run right now every week (~02:30 Saturday UTC).

**Comment by coolreader18** [comment]
I'll close this once codecov is updated.

**Comment by coolreader18** [comment]
Alright, [codecov](https://codecov.io/gh/RustPython/RustPython) is updated to the latest commit!
