### ISSUE TITLE
[RFC] Add wiki on how to analyze rustpython using uftrace

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#1481]
## Summary
I would like to write a way to analyze Rustpython using uftrace.
Where can I write it?

## Detailed Explanation
uftrace is a tool for tracing and analyzing the execution of programs written in C / C ++. 

However, it currently support these features for Rust.

We can use uftrace to analyze the execution of RustPython.
https://github.com/namhyung/uftrace/wiki/uftrace-for-RustPython

I would like to write a way to analyze Rustpython using uftrace. Where can I write it? (Readme or wiki?)

**Comment by coolreader18** [comment]
I think the wiki would be a good place for it.

**Comment by HyeockJinKim** [comment]
Do I have permission to write to the wiki? I can't find the new page button on the wiki.

How can I write a wiki?

**Comment by HyeockJinKim** [comment]
I have written a wiki like this.
https://github.com/RustPython/RustPython/wiki/uftrace

**Comment by coolreader18** [comment]
This is really useful, thanks!

**Comment by HyeockJinKim** [comment]
I will close this issue. Thanks!
