### ISSUE TITLE
Objects inherit docstring from object if not overwritten

### ISSUE THREAD

**Issue by janrg** [RustPython/RustPython#1523]
in CPython, if an object doesn't have a docstring assigned, its `__doc__` is set to `None`, in RustPython, it inherits `the most base type` from `object`

**Comment by seeeturtle** [comment]
I'll try it.

**Comment by seeeturtle** [comment]
the same problem in function should be fixed too.

**Comment by seeeturtle** [comment]
It seems the problem of function and the problem of class is a bit different.
Function doesn’t have doc attribute at all but class inherits the doc attribute of object
