### ISSUE TITLE
float('0_0') raise ValueError

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#1527]
## Feature
float('0_0') should return 0.0, but it raise ValueError

### Expected result
```python
>>> float('0_0')
0.0
```

### Actual result
```python
>>>>> float('0_0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: could not convert string to float: '0_0'
```

https://github.com/RustPython/RustPython/blob/d42d422566f64f48311cc7e7efb4d0ffcefb0297/vm/src/obj/objfloat.rs#L588-L599

In my opinion, `lexical :: try_parse` does not handle` _` properly.

**Comment by emmanuelantony2000** [comment]
Should I just remove the `_` and then try to parse?

**Comment by HyeockJinKim** [comment]
It doesn't seem to simply remove `_`.

```python
float('0__0')  # Two or more consecutive '_'
float('_0')  # A string beginning with '_'.
float('0._0')  # '_' after '.'
```

The above code should raise ValueError.
However, using the `replace` or `retain` function to remove all `_` will not raise ValueError in the above situation.

**Comment by emmanuelantony2000** [comment]
So I can think of a 'not so good' solution.
Split the string by `.`
If there are more than two substrings throw an error
If there are two substrings then each of those substrings should not

1. Start with an `_`
2. End with an `_`
3. Iterate through the string, if we find an `_` then that `_` should not succeed or precede by an `_`

Please tell me a better solution.

**Comment by HyeockJinKim** [comment]
https://github.com/RustPython/RustPython/blob/67f005e9f78075bffb5787b3dd622f3e235e6b85/vm/src/obj/objint.rs#L791-L837

I don't know if it's a better way, but in `objint.rs`, `str_to_int` is implemented as above.
See `validate_literal`.

https://github.com/RustPython/RustPython/blob/67f005e9f78075bffb5787b3dd622f3e235e6b85/vm/src/obj/objint.rs#L839-L860

**Comment by HyeockJinKim** [comment]
Can I take over this issue?

**Comment by emmanuelantony2000** [comment]
Yeah sure..
