### ISSUE TITLE
Port implementations of math functions from cpython

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#153]
There are four math functions which are pretty complex.

- `math.erf`
- `math.erfc`
- `math.gamma`
- `math.lgamma`

They are implemented in cpython, as can be seen here:
https://github.com/python/cpython/blob/master/Modules/mathmodule.c#L113

The documentation is listed here:
https://docs.python.org/3/library/math.html#special-functions

In rust python, they must be implemented in `vm/src/stdlib/math.rs`.

**Comment by yodalee** [comment]
Can we use Rust FFI to call C function to simplify the implementation?

**Comment by windelbouwman** [comment]
That would be possible, but even in CPython no library is used, but a hand crafted implementation. If there is a rust library implementing these functions, that would be preferred.

**Comment by yodalee** [comment]
I think we can use this: https://docs.rs/statrs/0.9.0/statrs/index.html

**Comment by windelbouwman** [comment]
Okay, that looks indeed like it provides the right functions! Nice find!

**Comment by windelbouwman** [comment]
@yodalee is this issue now completed, or do we require more actions?

**Comment by yodalee** [comment]
I think this one is complete. If you want to add more function implementation, I think open another issue is better.

**Comment by alanjds** [comment]
Is this able to be closed? Can someone please close it?

(I am trying to find `good first issue`s for myself)

**Comment by coolreader18** [comment]
Yes, it can be, thanks for the reminder. Have you tried running `whats_left.sh` in the root of the repo? It'll list a bunch of methods left to be implemented on builtin types.
