### ISSUE TITLE
The deletion of the dict does not affect the size of the vector

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#1531]
## Feature
https://github.com/RustPython/RustPython/blob/d42d422566f64f48311cc7e7efb4d0ffcefb0297/vm/src/dictdatatype.rs#L21-L25

As you can see in the code above, Dict stores the values ​​in a Vector.
However, when deleting a value, dict simply decrease size, but the size of the vector continues to grow.

```python
>>>>> for i in range(100000):
.....     a[0] = 1
.....     del a[0]
..... 
```
If running the code above, the vector will continue to grow in size and take longer than python3.6.

So `dict` seems to need the `resize` function.

But I'm not sure when to call `resize` function.
Should it be the same as calling `dictresize` in` cpython`?

In cpython `dictresize`:
https://github.com/python/cpython/blob/8a6cbf8adb68aa2c43a48769af92e50d5ca1539d/Objects/dictobject.c#L1177

**Comment by ashermancinelli** [comment]
https://github.com/RustPython/RustPython/blob/a1e3fe4e63cc21fb60093c0d43dd2cd8f56b09b6/vm/src/dictdatatype.rs#L69-L72
Could we free some memory here?
