### ISSUE TITLE
Explicitly mention Version of CPython Syntax supported

### ISSUE THREAD

**Issue by gabhijit** [RustPython/RustPython#155]
Right now, while it is implicitly understood we are targeting Python-3, it's a good idea to be explicit about it. At-least README.md should be updated to mention this. 

This should also help us target compliance, Python's Test suits etc.

**Comment by windelbouwman** [comment]
Can we close this issue after your change was merged?

**Comment by gabhijit** [comment]
Yes! Closing this .
