### ISSUE TITLE
Cargo run failure

### ISSUE THREAD

**Issue by vishalsodani** [RustPython/RustPython#157]
`cargo run` is failing on my windows 7 machine. 
I am using rust 1.26. I am getting this error 
```
error[E0658]: use of unstable library feature 'iterator_step_by': unstable replacement of Range::step_by (see issue #27741)
  --> vm\src\obj\objsequence.rs:56:34
   |
56 |         self[start..stop].iter().step_by(step).cloned().collect()
   |                                  ^^^^^^^

error[E0658]: use of unstable library feature 'iterator_step_by': unstable replacement of Range::step_by (see issue #27741)
   --> vm\src\obj\objstr.rs:220:35
    |
220 |         self[start..stop].chars().step_by(step).collect()
    |                                   ^^^^^^^

error: aborting due to 2 previous errors. 
```
The active toolchain is stable-x86_64-pc-windows-msvc (default).

**Comment by windelbouwman** [comment]
@vishalsodani were you able to fix this by using a different rust version? If so, please close this issue. If you like, please add a proper description to the readme file explaining the issues you encountered.

**Comment by windelbouwman** [comment]
Okay, thanks for reporting this issue, I think we should setup CI services on appveyor as well to detect this.

**Comment by windelbouwman** [comment]
@vishalsodani This might actually be a rust issue, could you try to contact the rust developers by probably raising the issue there? I assume that these math functions should be available on all platforms.

**Comment by Tom1380** [comment]
@vishalsodani can you still reproduce the issue if you use Rust 1.32 and the latest master code?

**Comment by windelbouwman** [comment]
@vishalsodani I closed this issue, if you still face this issue, please re-open.
