### ISSUE TITLE
str.isupper and str.islower are not implemented properly

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1575]
## Feature

`str.isupper` should return `True` if all the characters that *can* be multiple cases in a string *are* uppercase. However, the current implementation just uses Rust's `char::is_uppercase`, which does not distinguish between 'cased' and 'non-cased' characters. The same goes for `str.islower`.

## Python Documentation

https://docs.python.org/3/library/stdtypes.html#str.isupper

## Implementation

This can be implemented by modifying the `isupper` and `islower` functions in `vm/src/obj/objstr.rs`.

**Comment by Regexp96** [comment]
can I contribute this issue?
it's my first issue and I think I can do this

**Comment by Regexp96** [comment]
that commit is my mistake sorry

**Comment by coolreader18** [comment]
Yep, go ahead!
