### ISSUE TITLE
fetch snippet broken in wasm demo: '_browsers' is not a built-in module

### ISSUE THREAD

**Issue by silmeth** [RustPython/RustPython#1588]
On the [wasm demo](https://rustpython.github.io/demo/) the `fetch` snippet currently errors with the `Error: "'_browser' is not a built-in module"` message.

At least on Firefox 70.0.1 on Linux, but I guess it’s not a browser-related issue but rather some regression related to built-in modules changes.

**Comment by yanganto** [comment]
There is a hacky way to work around on this issue.

Before import `browser`, fix the the tuple of builtin module first.
```
import sys
sys.builtin_module_names = ('_js', '_window', '_browser', *sys.builtin_module_names)
```

This may be close to the root cause, it will be fixed when the processes of injecting the browser module and the js module are corrected.

**Comment by coolreader18** [comment]
Yeah, rustpython-wasm can definitely use a lot of work. I had plans to flesh out a lot of the Python/JS interop, but I never got around to it. There's still a lot more work to be done on the `JsValue` class (first and foremost that it should probably be called `JSValue`, looking back on it), including formalizing how security/sandboxing should work: right now, if you have access to just one `JSValue`, it's possible to get access to the `Object` prototype and define new methods on it, which is a security problem for someone who might want to use rustpython-wasm to run completely untrusted Python code:
```py
from _window import window
object_proto = window.new_object().get_prop('__proto__')
object_proto.set_prop('property', window.new_from_float(12.0))
```
and now in JS:
```js
({}).property // 12.0
```
Or, you could get access to the function constructor, which would allow you to get the window object and make a `fetch` request:
```py
from _window import window
# I know we already have `window` here, but imagine we just get some random object
js_obj = window.new_object()
del window
object_proto = js_obj.new_object().get_prop('__proto__')
Function = object_proto.get_prop("toString").get_prop("constructor")
window = Function.call(js_obj.new_from_str("return this")).call()
```

I also wanted to make a proxy class for `JSValue`s to make it easier to work with them, e.g. `__getattr__` would call `get_prop`, `__call__` would call `call`, etc.

If you @yanganto (or anyone else) wanted to work on any of this stuff, feel free to.

**Comment by yanganto** [comment]
This may not easy to implement perfectly at once, but sounds interesting.  I am willing to try and may ask some questions on Gitter when running into problems. Thank @coolreader18 .

**Comment by yanganto** [comment]
I got an idea of sandboxing.
Maybe we can construct an option to decide python code to access the javascript object

In the following option provided, the VM will allow Python code to access the javascript obj, and the flag is true by default.
```js
rp.pyEval("python code", {unsafe: true})
````

**Comment by silmeth** [comment]
This seems to be now fixed, closing.
