### ISSUE TITLE
[RFC] Use a pure-Python implementation of the `io` module

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1600]
## Summary

Replace, to some extent, the built-in Rust `io` module with a Python implementation taken mostly from CPython's `_pyio.py`

## Detailed Explanation

I already have a working implementation locally and the explanation is pretty much the summary. It requires a few changes to builtin types and modules, but not *that* many. It'd be possible to use a Python `io` in `importlib._bootstrap_external`, although I haven't tried that yet.

## Drawbacks, Rationale, and Alternatives

We already have put a fair amount of effort into the `io.rs` module, but it still lacks is not fully compliant to CPython's version. Meanwhile, I was able to get `io.py` backing the `http.client` module with very few edits to its actual source.

An alternative is to keep working on the `io.rs` module, but it still has a way to go with compatibility, and I feel like it would be best to get a fully compatible/compliant version of the module and then use that as a base to make sure that the Rust implementation is compatible as well.

Also, and this may be just my perception, but the code in `io.rs` is pretty messy, and I think that it could benefit from being rewritten/reworked based off of a pre-existing Python implementation. Again, that's just my perception, and that might just be how the code has to look for it to act like CPython's `_io`, but it does seem like it could be cleaner.

## Unresolved Questions

- How much should we keep the `io.rs` module around?

- Is this even a good idea?
    - Again, `io.rs` has had a lot of work put into it, and there's not necessarily a burning reason to replace it.

- Should we prioritize the Python implementation over the Rust implementation? I've experimented in my implementation with overwriting built-in `_io`'s attributes with the Python versions so that `importlib._bootstrap_external` can use it, and it works, but I'm not sure if we want to put *more* Python code into that performance-sensitive module.

**Comment by windelbouwman** [comment]
I'm in favor of implementing all of the `io` module in rust. Reasoning points:

- The rust version might be more performing (okay, it's IO, so not a big deal, but still)
- The bootstrapping of rust modules is easier, no hassle with importlib bootstrap etc..
- The rust variant is type checked, so potentially contains less bugs than the python version

**Comment by youknowone** [comment]
if `_pyio.py` is working right now, I believe we just can work on `_io.rs` for future replacement when it becomes mature.
We just need a test suite to test if `_pyio` and `_io` is equivalent for the progress.
For more, I am pretty sure that It must be easier than working on only `_io` itself.

**Comment by youknowone** [comment]
our _io seems working enough well now.
