### ISSUE TITLE
automatic integer to floating point conversion in format strings

### ISSUE THREAD

**Issue by lovasoa** [RustPython/RustPython#1613]
## Feature

Format codes such as 'e', 'f', and 'g' are supported in format strings for integers in CPython, but not in RustPython

### in cpython

```py
>>> f'{5:f}'
'5.000000'
```

### in RustPython

```py
>>>>> f'{5:f}'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Unknown format code 'f' for object of type 'int'
```

## Python Documentation

https://docs.python.org/3/library/string.html#formatspec

**Comment by doyshinda** [comment]
Issue update:

`:f` is now supported for integers:
```Python
Welcome to the magnificent Rust Python 0.1.1 interpreter 😱 🖖
>>>>> f'{5:f}'
'5.000000'
>>>>> f'{5:.2f}'
'5.00'
```

Remaining work is to implement `e` and `g` format codes.

**Comment by doyshinda** [comment]
Issue update:

`:e` is now supported for integers:
```Python
Welcome to the magnificent Rust Python 0.1.1 interpreter 😱 🖖
>>>>> f'{5:e}'
'5.000000e+00'
>>>>> f'{5:.2e}'
'5.00e+00'
```

**Comment by youknowone** [comment]
not sure when its fixed, but now it works

```
>>>>> f'{5:f}'
'5.000000'
```
