### ISSUE TITLE
[RFC] Rename LineContinationHandler to LineContinuationHandler

### ISSUE THREAD

**Issue by brettcannon** [RustPython/RustPython#1622]
## Summary

I believe `LineContinationHandler` is misspelled and meant to be `LineContinuationHandler` (notice the `u`).

## Drawbacks, Rationale, and Alternatives

Would break backwards-compatibility for anyone using the `rustpython-parser` crate.

**Comment by coolreader18** [comment]
This sounds good! We aren't really too concerned with a stable API for our crates yet, so there shouldn't be a problem with changing the name.
