### ISSUE TITLE
MRO computation in RustPython doesn't seem to implement C3 correctly

### ISSUE THREAD

**Issue by cfbolz** [RustPython/RustPython#1659]
## Feature

I was experimenting with RustPython's implementation of multiple inheritance and it doesn't seem to implement the C3 method resolution order algorithm correctly.

Example 1:

```python
class A:
    pass

class B(A):
    pass

class C(A, B):
    pass
```

This should give an error, but doesn't in RustPython.

Example 2:

```python
class A:
    def f(self):
        print("A")

class B(A):
    def f(self):
        super().f()
        print("B")

class C(A):
    def f(self):
        super().f()
        print("C")

class D(B, C):
    def f(self):
        super().f()
        print("D")

D().f()
```

This should print "A, C, B, D" but prints instead "A, B, D", missing C completely in the mro.

## Python Documentation

There seems to be no great description of the C3 algorithm as part of the docs, but it's described as part of the 2.3 release notes here: https://www.python.org/download/releases/2.3/mro/

**Comment by IdanDor** [comment]
This is now fixed and can be closed.
