### ISSUE TITLE
ImportError when running whats_left.sh

### ISSUE THREAD

**Issue by metaphorshear** [RustPython/RustPython#1661]
I'm running into this issue building on a Kali Linux VM.  (I've also tried on Windows with Git Bash and am getting the same error.) Methods are listed fine, but this is what I get for modules:
<pre><font color="#8AE234"><b>===== MODULES =====</b></font>
Traceback (most recent call last):
  File &quot;tests/snippets/whats_left_modules.py&quot;, line 33, in &lt;module&gt;
    rustpymods
  File &quot;tests/snippets/whats_left_modules.py&quot;, line 29, in &lt;lambda&gt;
    set(dir(__import__(mod)))
  File &quot;_frozen_importlib&quot;, line 1093, in __import__
  File &quot;_frozen_importlib&quot;, line 1014, in _gcd_import
  File &quot;_frozen_importlib&quot;, line 991, in _find_and_load
  File &quot;_frozen_importlib&quot;, line 991, in _find_and_load
  File &quot;_frozen_importlib&quot;, line 975, in _find_and_load_unlocked
  File &quot;_frozen_importlib&quot;, line 686, in _load_unlocked
  File &quot;_frozen_importlib&quot;, line 684, in _load_unlocked
  File &quot;_frozen_importlib&quot;, line 677, in _load_unlocked
  File &quot;_frozen_importlib&quot;, line 671, in _load_unlocked
  File &quot;_frozen_importlib_external&quot;, line 788, in exec_module
  File &quot;_frozen_importlib&quot;, line 219, in _call_with_frames_removed
  File &quot;/root/RustPython/Lib/stringprep.py&quot;, line 8, in &lt;module&gt;
    from unicodedata import ucd_3_2_0 as unicodedata
ImportError: cannot import name &apos;ucd_3_2_0&apos;</pre>

If it helps, I'm running Python 3.7 and the latest stable Rust.

**Comment by coolreader18** [comment]
Oh, that should be fixed soon with #1658. You could either `rm Lib/stringprep.py` temporarily or switch to the `coolreader18/unicode-stuff` branch to fix it.

**Comment by youknowone** [comment]
The referenced PR is merged. is this closed now?

**Comment by metaphorshear** [comment]
Yeah, good point
