### ISSUE TITLE
exit(), panic if code >= 2**31

### ISSUE THREAD

**Issue by andrew-ld** [RustPython/RustPython#1742]
## code
`exit(2**31)`

## result
```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libcore/macros/mod.rs:15:40```

## expected result
in cpython if exit code overflow fallback to 0

**Comment by coolreader18** [comment]
Well that's one way to exit :smile:. This is probably an easy fix, though.

**Comment by arnavb** [comment]
@coolreader18 Can I take up this issue?
