### ISSUE TITLE
Positional only parameters PEP 570

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#1755]
## Feature

Positional-only parameters

## Python Documentation

https://www.python.org/dev/peps/pep-0570/

**Comment by palaviv** [comment]
@youknowone I am not sure about the purpose of the issue? Do you wish to discuss if we should implement it? (I am pretty sure the answer is yes as it is part of python). Are you looking for help with implementing this?

**Comment by youknowone** [comment]
I am sorry, it must be compatibility issue.

**Comment by zetwhite** [comment]
Is there something left to do in this issue? 
I'm interested in it, but it looks almost everything is done.

**Comment by youknowone** [comment]
@zetwhite by the comment on #1787, positional only error is not implemented. would you check `Lib/test/test_positional_only_arg.py`

**Comment by zetwhite** [comment]
okay. I'll check it. 
thank you 😄

**Comment by youknowone** [comment]
done by #3420
