### ISSUE TITLE
Built in classes receive args from subclass despite empty __init__()

### ISSUE THREAD

**Issue by philippeitis** [RustPython/RustPython#1782]
This is related to #1672 - Counter inherits from dict and calls its base constructor, which receives all arguments, despite them not being passed through the `super(...)__init__()` constructor.

I've included two examples below:

```
class ListSubClass(list):
    def __init__(self, *args):
        super(ListSubClass, self).__init__()
        print(args)

x = ListSubClass(1)
```
Expected:
```
(1, )
```
Got:
```
TypeError: Cannot iterate over int
```

Additionally, for dict:
```
class DictSubClass(dict):
    def __init__(self, *args):
        super(DictSubClass, self).__init__()
        print(args)

x = DictSubClass("1")
```
Expected
```
('1', )
```
Got
```
TypeError: Iterator must have exactly two elements
```

I was not able to reproduce this for classes defined within Python itself, but was able to reproduce this with sets as well. However, this does not apply for the tuple type, as it also raises a TypeError in CPython.

This goes away when we override `__new__` to pass no arguments or keyword arguments, but is not required in CPython - eg:
```
def __new__(cls, *args, **kwargs):
      super(ClassName, cls).__new__(cls)
```

**Comment by youknowone** [comment]
closed by #2792
