### ISSUE TITLE
[RFC] Threading

### ISSUE THREAD

**Issue by palaviv** [RustPython/RustPython#1831]
## Summary

I think we have got to the stage we should support threading in RustPython.

## Detailed Explanation

There was already some discussion on threading but I wanted to start a dedicated issue as it is a big decision. I will try to break the issue in order to make some order:

### Definition of done
We need a user to be able to create a new thread in python and execute code on the same Python object from multiple threads:
```py
import threading

def worker(num):
    """thread worker function"""
    print 'Worker: %s' % num
    return

threads = []
for i in range(5):
    t = threading.Thread(target=worker, args=(i,))
    threads.append(t)
    t.start()
```

### GIL
I think that one of the biggest discussion is the [GIL](https://wiki.python.org/moin/GlobalInterpreterLock). Should we add a GIL to RustPython? Should we allow only one thread to use each object at a time?

### Suggested approach
I suggest the following changes in order to reach the ability to spawn a new thread:

- I suggest we will create a new VirtualMachine for each thread. Thus making VirtualMachine `!sync` and `!Send`.
- Use `Arc` instead of `Rc` in `PyObjectRef`. `pub type PyObjectRef = Arc<PyObject<dyn PyObjectPayload>>`
- `PyValue` and `PyObjectPayload` traits will implement `Sync` and `Send`. Thus forcing us to make all Py* structs sync as well.
- We will need to convert most of the code `Rc`, `Cell` and `RefCell` use to thread safe options. For example `Arc`, `Mutex` and `Atomic*`.
- When accessing data of an Object wrapped in `Mutex` we will lock the mutex for our use. This will require careful handling when using internal objects to avoid deadlocks when used between threads. 

A simple example of the `start_new_thread` method in `_thread` will look something like:
```rust
fn start_new_thread(func: PyFunctionRef, args: PyFuncArgs, vm: &VirtualMachine) -> u64 {
    let handle = thread::spawn(move || {
        let thread_vm = VirtualMachine::new(PySettings::default()); // Should get some params from original VM
        thread_vm.invoke(func.as_object(), args).unwrap();
    });
    get_id(handle.thread())
}
```
## Drawbacks, Rationale, and Alternatives

- I suggest that we will ignore the GIL and allow multiple threads to execute python code simultaneously. This can be a big advantage of RustPython on CPython. The user will be expected to make his own code thread safe. This might prove problematic to code that rely on the GIL.

- What about third party library's? We do not yet have an API but would we force them to implement `Sync` and `Send` as well?

- There was a lot of talk about alternatives and I cannot find all so please fill free to add in the comments. One alternatives that was suggested is [Crossbream](https://docs.rs/crossbeam/0.7.3/crossbeam/).
 
## Unresolved Questions

- How can we do this change in small steps?
- How to test for deadlocks?
- Is this the right time to do this?

**Comment by coolreader18** [comment]
I think your idea of making a new vm per-thread is a good idea, we could probably clone the `PyContext`, `builtins` and `sysmodule` (and some other stuff) to the new vm but create a new e.g. exception stack. Maybe we could split off some of the fields that are `RefCell`s into a separate `VMState` struct in order to make it easier to clone them/wrap them in `Mutex`s.

**Comment by coolreader18** [comment]
This is pretty interesting/exciting, I think I might work on preparing the vm for this.

**Comment by coolreader18** [comment]
Well, just with this change:
```diff
diff --git a/vm/src/pyobject.rs b/vm/src/pyobject.rs
index f0265d1c..929ffab6 100644
--- a/vm/src/pyobject.rs
+++ b/vm/src/pyobject.rs
@@ -1177,11 +1177,11 @@ pub trait PyValue: fmt::Debug + Sized + 'static {
     }
 }
 
-pub trait PyObjectPayload: Any + fmt::Debug + 'static {
+pub trait PyObjectPayload: Send + Sync + Any + fmt::Debug + 'static {
     fn as_any(&self) -> &dyn Any;
 }
 
-impl<T: PyValue + 'static> PyObjectPayload for T {
+impl<T: Send + Sync + PyValue + 'static> PyObjectPayload for T {
     #[inline]
     fn as_any(&self) -> &dyn Any {
         self
```
cargo gives 716 errors in the codebase, so I think this will have to be a gradual process of converting our types to be `Send + Sync`, similar to migrating from `enum PyObjectPayload` -> `trait PyObjectPayload` a year ago.

**Comment by palaviv** [comment]
Yes. This is going to take some time converting all objects to be `Send + Sync`. In order to help with the tracking our progress and making sure objects that have already been converted will not regress. I suggest adding a new temporary trait:
```rust
// Temporary trait to follow the progress of threading conversion
pub trait ThreadSafe: Send + Sync {}
```
And we will implement the `ThreadSafe` trait for each object that is `ThreadSafe`. Once all objects are `ThreadSafe` we will remove this trait and mark `PyObjectPayload` with `Send + Sync`.

**Comment by coolreader18** [comment]
Unfortunately, that won't necessarily work, since a lot of the built-in types store other `PyObjectRef`s inside, and until `PyObjectRef` is made `Send + Sync` itself, those can't be marked `ThreadSafe`.

**Comment by palaviv** [comment]
The problem is that this is a circular dependency. I would like to be able to work on this in small steps. We can go in two ways here:
1. Use `Mutex` in every object that contains `PyObjectRef`. Once `PyObjectRef` is `Send+Sync` remove the `Mutex` or change to `RWlock`. 
2. Make `PyObjectRef` `Send+Sync` by wrapping everything inside in `Mutex`. After making all object `ThreadSafe` remove the `Mutex`.

What do you think? Any other suggestions?

**Comment by palaviv** [comment]
> The problem is that this is a circular dependency. I would like to be able to work on this in small steps. We can go in two ways here:
> 
> 1. Use `Mutex` in every object that contains `PyObjectRef`. Once `PyObjectRef` is `Send+Sync` remove the `Mutex` or change to `RWlock`.
> 2. Make `PyObjectRef` `Send+Sync` by wrapping everything inside in `Mutex`. After making all object `ThreadSafe` remove the `Mutex`.
> 
> What do you think? Any other suggestions?

After looking more into this my suggestion would not actually work as `Mutex<T>` implements `Sync` only when T implements `Send`.
Another way to go is to declare temporarily:
```rust
unsafe impl<T: PyValue> Send for PyObject<T> {}
unsafe impl<T: PyValue> Sync for PyObject<T> {}
```
This should not affect the current implementation as we do not support threading yet but will allow us to change most object to `ThreadSafe`.
@coolreader18 what do you think?

**Comment by coolreader18** [comment]
Technically that would be unsound, but as its only temporary and we wouldn't actually be using it I think it might be fine. Also, have you tried adding just a `Send` bound to `PyObjectPayload`? I'd think there's be a lot more payload types that already implement that.

**Comment by coolreader18** [comment]
Dang, just ran into a problem with using `RwLock`s for `bytearray`: https://github.com/RustPython/RustPython/pull/1821/checks?check_run_id=579689378. According to the [standard library documentation for RwLock](https://doc.rust-lang.org/stable/std/sync/struct.RwLock.html#method.read), calling `read()` might (read: will) panic if the lock is already held by the current thread, which doesn't really fit with our using them to replace `RefCell`s, which are perfectly fine with that usage. I think we have to either use some other RwLock implementation, like [`parking_lots`'s](https://docs.rs/lock_api/0.3.4/lock_api/struct.RwLock.html#method.read_recursive), which allows for recursive/reentrant reads, or figure out some way to structure our code so that we don't try to read() when a lock is already held, e.g. don't call into python code when the lock is held.

**Comment by palaviv** [comment]
Wow that was quick :sweat_smile:
From looking into the error it seems to happen only when running with trace. I am not sure what option is better. I don't see any problem using a reentrant lock but I do think we should try and avoid calling  python code when holding locks.
I will try and look more into the error and update if I understand where is the problem.

**Comment by redradist** [comment]
Guys, I would like to help in supporting threading in RustPython without GIL !!
Is there either a pull-request or branch on which you are working ?

**Comment by palaviv** [comment]
Hi @redradist, That would be great. We have a lot of work to do!!!
You can start converting object to thread safe. You can look at what I did in #1848 and #1860. I would recommend starting with object that don't contain `PyObjectRef` until we make it `Send + Sync`. I would recommend starting with `pystruct`, `io`, `os` just look for anything that implements `PyValue`.

**Comment by redradist** [comment]
@palaviv 
> 
> Hi @redradist, That would be great. We have a lot of work to do!!!
> You can start converting object to thread safe. You can look at what I did in #1848 and #1860. I would recommend starting with object that don't contain `PyObjectRef` until we make it `Send + Sync`. I would recommend starting with `pystruct`, `io`, `os` just look for anything that implements `PyValue`.

I am trying to make first contribution, but by some reason cannot build the RustPython:

   Compiling openssl-sys v0.9.55
error: failed to run custom build command for `openssl-sys v0.9.55`

Caused by:
  process didn't exit successfully: `G:\Projects\Programing\RustPython\target\debug\build\openssl-sys-ab409795ee307816\b
uild-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset
running "perl" "./Configure" "--prefix=G:\\Projects\\Programing\\RustPython\\target\\debug\\build\\openssl-sys-c96bb7186
66a35bf\\out\\openssl-build\\install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-engine
" "no-async" "no-asm" "VC-WIN64A"

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The syst
em cannot find the file specified." }', C:\Users\RedRa\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.8
.1+1.1.1f\src\lib.rs:377:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Could you support with it ?

**Comment by palaviv** [comment]
Hi @redradist, I am realy not sure about openssl. Can you make sure your code is reabsed on the current master as the change in #1841 might solve this. @coolreader18 can you have a look?

**Comment by redradist** [comment]
@palaviv 
> 
> Hi @redradist, I am realy not sure about openssl. Can you make sure your code is reabsed on the current master as the change in #1841 might solve this. @coolreader18 can you have a look?

I have checked on my side, I am on master branch ...
The interesting thing that on Ubuntu RustPython compiles without any issues !!
Issue reproducible only on Windows !!

**Comment by coolreader18** [comment]
Ah, yeah, try installing [Strawberry Perl](https://strawberryperl.com), OpenSSL needs it in order to run the build script.

**Comment by redradist** [comment]
@coolreader18 
> 
> Ah, yeah, try installing [Strawberry Perl](https://strawberryperl.com), OpenSSL needs it in order to run the build script.

Thanks a lot !!
Seems like it has been compiled successfully, but still some error occurs:
```
Finished dev [unoptimized + debuginfo] target(s) in 3m 56s
     Running `target\debug\rustpython.exe`
error: process didn't exit successfully: `target\debug\rustpython.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
```

**Comment by redradist** [comment]
> 
> 
> @coolreader18
> 
> > Ah, yeah, try installing [Strawberry Perl](https://strawberryperl.com), OpenSSL needs it in order to run the build script.
> 
> Thanks a lot !!
> Seems like it has been compiled successfully, but still some error occurs:
> 
> ```
> Finished dev [unoptimized + debuginfo] target(s) in 3m 56s
>      Running `target\debug\rustpython.exe`
> error: process didn't exit successfully: `target\debug\rustpython.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
> ```
> 
> I have found that missed libssl1_1 and libcrypto1_1

I have found these libraries, then put the in location of rustpython and rustpython launched, but I did not get why it does not work from cargo run ?

**Comment by coolreader18** [comment]
Hmm, I'm not sure, that's really weird. It should link them statically into the rust binary rather than needing a dll, we configured it to do that.

**Comment by redradist** [comment]
@coolreader18 
> 
> Hmm, I'm not sure, that's really weird. It should link them statically into the rust binary rather than needing a dll, we configured it to do that.

Nut actually on my machine it creates a separate .dll and searching for them, only moving .dll to binary location helps ...
@coolreader18 Could you check proper configuration ?

**Comment by redradist** [comment]
Guys, I have additional issue ...
When I run RustPython on Windows I got the following error:
```powershell
    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
     Running `.\rustpython.exe`
ModuleNotFoundError: No module named 'io'
thread 'main' panicked at 'initializiation failed; exception backtrace above', vm\src\vm.rs:548:13
stack backtrace:
   0:     0x7ff71d67bb9f - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1:     0x7ff71d67bb9f - std::sys_common::backtrace::_print_fmt
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\sys_common\backtrace.rs:78
   2:     0x7ff71d67bb9f - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff71d6979cb - core::fmt::write
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libcore\fmt\mod.rs:1069
   4:     0x7ff71d6736bc - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\io\mod.rs:1532
   5:     0x7ff71d67edbc - std::sys_common::backtrace::_print
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\sys_common\backtrace.rs:62
   6:     0x7ff71d67edbc - std::sys_common::backtrace::print
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\sys_common\backtrace.rs:49
   7:     0x7ff71d67edbc - std::panicking::default_hook::{{closure}}
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\panicking.rs:198
   8:     0x7ff71d67e9ff - std::panicking::default_hook
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\panicking.rs:218
   9:     0x7ff71d67f5a7 - std::panicking::rust_panic_with_hook
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\panicking.rs:477
  10:     0x7ff71d67f12f - std::panicking::begin_panic_handler
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\panicking.rs:385
  11:     0x7ff71d67f09c - std::panicking::begin_panic_fmt
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\panicking.rs:339
  12:     0x7ff71c183ce4 - rustpython_vm::vm::VirtualMachine::_py_panic_failed
                               at G:\Projects\Programing\RustPython\vm\src\vm.rs:548
  13:     0x7ff71c3fadf5 - rustpython_vm::vm::{{impl}}::expect_pyresult::{{closure}}<()>
                               at G:\Projects\Programing\RustPython\vm\src\vm.rs:570
  14:     0x7ff71c39637f - core::result::Result<(), rustpython_vm::pyobject::PyRef<rustpython_vm::exceptions::PyBaseException>>::unwrap_or_else<(),rustpython_vm::pyobject::PyRef<rustpython_vm::exceptions::PyBaseException>,closure-0>
                               at C:\Users\RedRa\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:853
  15:     0x7ff71c3fadb1 - rustpython_vm::vm::VirtualMachine::expect_pyresult<()>
                               at G:\Projects\Programing\RustPython\vm\src\vm.rs:570
  16:     0x7ff71c1812e3 - rustpython_vm::vm::VirtualMachine::initialize
                               at G:\Projects\Programing\RustPython\vm\src\vm.rs:269
  17:     0x7ff71c18009a - rustpython_vm::vm::VirtualMachine::new
                               at G:\Projects\Programing\RustPython\vm\src\vm.rs:218
  18:     0x7ff71c16dc38 - rustpython::main
                               at G:\Projects\Programing\RustPython\src\main.rs:39
  19:     0x7ff71c17dcfb - std::rt::lang_start::{{closure}}<()>
                               at C:\Users\RedRa\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  20:     0x7ff71d67f8ca - std::rt::lang_start_internal::{{closure}}
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\rt.rs:52
  21:     0x7ff71d67f8ca - std::panicking::try::do_call
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\panicking.rs:297
  22:     0x7ff71d67f8ca - std::panicking::try
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\panicking.rs:274
  23:     0x7ff71d67f8ca - std::panic::catch_unwind
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\panic.rs:394
  24:     0x7ff71d67f8ca - std::rt::lang_start_internal
                               at /rustc/f05a5240440b3eaef1684a7965860fab40301947\/src\libstd\rt.rs:51
  25:     0x7ff71c17dcd3 - std::rt::lang_start<()>
                               at C:\Users\RedRa\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  26:     0x7ff71c173030 - main
  27:     0x7ff71d6b2ea4 - invoke_main
                               at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  28:     0x7ff71d6b2ea4 - __scrt_common_main_seh
                               at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  29:     0x7ffb008d7bd4 - BaseThreadInitThunk
  30:     0x7ffb0274ce51 - RtlUserThreadStart
error: process didn't exit successfully: `.\rustpython.exe` (exit code: 101)
PS G:\Projects\Programing\RustPython\target\debug>
```

**Comment by coolreader18** [comment]
Have you set your `RUSTPYTHONPATH` environment variable to point to the Lib directory?

**Comment by redradist** [comment]
> 
> 
> Have you set your `RUSTPYTHONPATH` environment variable to point to the Lib directory?

Yes, I have set it:
```
$env:RUSTPYTHONPATH = 'Lib'
```

**Comment by redradist** [comment]
Also I have some such error:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.86s
     Running `target\debug\rustpython.exe`

thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\debug\rustpython.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
```

**Comment by coolreader18** [comment]
Oh, make sure you're running in release mode

**Comment by coolreader18** [comment]
@redradist if you have any more problems with running on windows, could you open a separate issue for it?

**Comment by redradist** [comment]
Guys, is there anything left to mark ThreadSafe ?
I searching in repo and seems like all classes marked as ThreadSafe ... ?!

**Comment by palaviv** [comment]
Sorry @redradist I have already finished that. There are many other things we need help with. Please look at the [contribution](https://github.com/RustPython/RustPython#contributing) guide.

**Comment by palaviv** [comment]
I think we can close this issue. RustPython supports threads without the GIL. You can test this with this example:
```python
# single_threaded.py
import time
from threading import Thread

COUNT = 500000

def countdown(n):
    while n>0:
        n -= 1

start = time.time()
countdown(COUNT)
end = time.time()

print('Time taken in seconds -', end - start)
```
```python
# multi_threaded.py
import time
from threading import Thread

COUNT = 500000

def countdown(n):
    while n>0:
        n -= 1

t1 = Thread(target=countdown, args=(COUNT//2,))
t2 = Thread(target=countdown, args=(COUNT//2,))

start = time.time()
t1.start()
t2.start()
t1.join()
t2.join()
end = time.time()

print('Time taken in seconds -', end - start)
```
When running with CPython I get:
```bash
> python3 single_threaded.py
Time taken in seconds - 0.023739099502563477
> python3  multi_threaded.py
Time taken in seconds - 0.023739099502563477
```
While in RustPython:
```bash
> target/release/rustpython single_threaded.py
Time taken in seconds - 2.0910146236419678
> target/release/rustpython  multi_threaded.py
Time taken in seconds - 1.4379611015319824
```
As you can see we are slow but we are slow on multiple threads concurrently :smile:

**Comment by redradist** [comment]
@palaviv 
> 
> I think we can close this issue. RustPython supports threads without the GIL. You can test this with this example:
> 
> ```python
> # single_threaded.py
> import time
> from threading import Thread
> 
> COUNT = 500000
> 
> def countdown(n):
>     while n>0:
>         n -= 1
> 
> start = time.time()
> countdown(COUNT)
> end = time.time()
> 
> print('Time taken in seconds -', end - start)
> ```
> 
> ```python
> # multi_threaded.py
> import time
> from threading import Thread
> 
> COUNT = 500000
> 
> def countdown(n):
>     while n>0:
>         n -= 1
> 
> t1 = Thread(target=countdown, args=(COUNT//2,))
> t2 = Thread(target=countdown, args=(COUNT//2,))
> 
> start = time.time()
> t1.start()
> t2.start()
> t1.join()
> t2.join()
> end = time.time()
> 
> print('Time taken in seconds -', end - start)
> ```
> 
> When running with CPython I get:
> 
> ```shell
> > python3 single_threaded.py
> Time taken in seconds - 0.023739099502563477
> > python3  multi_threaded.py
> Time taken in seconds - 0.023739099502563477
> ```
> 
> While in RustPython:
> 
> ```shell
> > target/release/rustpython single_threaded.py
> Time taken in seconds - 2.0910146236419678
> > target/release/rustpython  multi_threaded.py
> Time taken in seconds - 1.4379611015319824
> ```
> 
> As you can see we are slow but we are slow on multiple threads concurrently 😄

Is there tests with RustPython when you have Rc instead of Arc for single threaded implementation ?

**Comment by redradist** [comment]
@palaviv
> 
> @redradist we currently don't support this but that sounds like a nice feature if you want to try and take it.

No, I've just would like to see benchmarks before and after ... )
