### ISSUE TITLE
Add missing methods to `str` class.

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#190]
The `str` class is still missing several methods. In CPython there exist a lot of handy methods you can use on strings. To fix this issue, head over to the file `vm/src/obj/objstr.rs` and add a method you found was missing.

This is a good first issue. If you completed your mission, please create another good starter issue for others to get their hands dirty with the sourcecode!

**Comment by mcon** [comment]
Looks like `string_expected_methods` includes everything that `dir('foobar')` contains in cpython, and `objstr.rs` has an implementation of each of those - think this ticket can be closed.

**Comment by ZapAnton** [comment]
I would disagree.

`isdecimal` is not explicitly implemented, and `''.isdecimal()` returns `True`, which is not correct
`maketrans` is also not implemented

**Comment by mcon** [comment]
My mistake, you're correct - misinterpreted `whats_left_to_implement` - looks like the following all need doing:
```
string . __dir__
string . __doc__
string . __format__
string . __ge__
string . __getnewargs__
string . __init_subclass__
string . __iter__
string . __le__
string . __mod__
string . __reduce__
string . __reduce_ex__
string . __rmod__
string . __rmul__
string . __setattr__
string . __sizeof__
string . __subclasshook__
string . encode
string . format_map
string . isdecimal
string . isprintable
string . maketrans
string . translate
```

**Comment by epellis** [comment]
Looks like the following (maybe more) have already been implemented:
```
string . isdecimal
string . __ge__
string . __doc__
string . __format__
```

**Comment by yanganto** [comment]
implement str.isprintable[#1024](https://github.com/RustPython/RustPython/pull/1024)

**Comment by longwusha** [comment]
@windelbouwman  What other work remains waiting for completion and implementation under this question? I am happy to contribute my spare time to this issue.

**Comment by windelbouwman** [comment]
@longwusha did you run the what is left script to check missing methods on the str type?

**Comment by longwusha** [comment]
@windelbouwman 

When I run the what is left script, I got these missing methods on the str type:

    str.__getnewargs__
    str.__init_subclass__
    str.__iter__
    str.__rmod__
    str.__sizeof__
    str.__subclasshook__
    str.format_map

I am not sure is any other people are working on these.

**Comment by longwusha** [comment]
@windelbouwman 

As we can see, some one was trying to implement str.__iter__ in #593 . But it seems that he has no interest or time to continue this work, so I want to start to implement other missing methods on the str type based on his work.

It seems that since his last commit (four months ago) the code has undergone a lot of changes, I hope that you can provide some suggestions to help me get started. I will be very grateful for your suggestion.

**Comment by windelbouwman** [comment]
@longwusha I think string iteration already works, at least I can use `x = iter("fu")`. You might want to try and import a module you would like to use, and see what problem you hit. That's at least a good way to start working on something.

If you like you can pickup the work from #593, since this work was abandoned. Adding a method to an object is a very good way to get yourself up and running with the codebase. Make sure to create a test snippet in the `tests/snippets` directory for the function you add.

**Comment by windelbouwman** [comment]
Another method which might be a good starter is the `int.__rdivmod__` method. Try to create some testcases for this, and then implement the method.

**Comment by longwusha** [comment]
Thank you very much for your good advice, I will try to start with str.format_map.

**Comment by youknowone** [comment]
`str` class is now practically done.
