### ISSUE TITLE
[RFC] need virtual env for import modules easily

### ISSUE THREAD

**Issue by laticoda** [RustPython/RustPython#1956]
I'd like to import pyglet or arcade.They are game engine 100% python written.
I dont know how to create a kind of **pipenv --python 3.7 install pyglet arcade**.

i tried other very simple scripts and i get :
_AttributeError: module 'random' has no attribute 'randint'
ModuleNotFoundError: No module named 'os'_

thanks for your job, rustpython is a great concept.

**Comment by youknowone** [comment]
`rustpython -m venv` is now working
