### ISSUE TITLE
Support and enable LTO by default

### ISSUE THREAD

**Issue by Keithcat1** [RustPython/RustPython#1978]
In order to reduce size and maybe increase performance, link-time-optimization could be enabled.
I tried these commands:
set RUSTFLAGS=-Clto
cargo install rustpython

I got this error:
error: cannot prefer dynamic linking when performing LTO

note: only 'staticlib', 'bin', and 'cdylib' outputs are supported with LTO

error: aborting due to previous error

error: could not compile `proc-macro-hack`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rustpython v0.1.2`, intermediate artifacts can be found at `C:\Users\Keith\AppData\Local\Temp\cargo-installbvSdKc`

Caused by:
  build failed
I'm on windows. This problem seems to be with both theh Mingw and MSVC toolchains.

**Comment by coolreader18** [comment]
Try just adding the following to Cargo.toml:
```toml
[profile.release]
lto = true
```
That's how you generally add lto to a cargo project, I think.

**Comment by Keithcat1** [comment]
Forgot about this one. I n the meantime I elarned that you can also set the environment variable "CARGO_PROFILE_RELEASE_LTO" to "on" and that also enables LTO. Doing it with RUSTFLAGS as I did above is probably not a good idea.
