### ISSUE TITLE
Support pip

### ISSUE THREAD

**Issue by skinny121** [RustPython/RustPython#1983]
To support pip the following are required:

- [x]  `__class__` assignment(#1981)
- [ ]  `plistlib` which requires `xml.parsers.expat`
- [x]  Fix `shutil.get_terminal_size`
- [x]  `itertools.groupby`
- [x]  Fix `str.__add__` raising `TypeError` instead of returning `NotImplemented`
- [x]  Fix `"{x.attr}".format(...)`

If the above issues are worked/hacked around, then the pip help text is successfully displayed :tada::
```
ben@BenLinux:~/Hobby/RustPython$ RUSTPYTHONPATH=Lib:local_packages/ cargo run --release local_packages/pip 
    Finished release [optimized] target(s) in 0.12s
     Running `target/release/rustpython local_packages/pip`

Usage:   
  pip <command> [options]

Commands:
     install Install packages.
    download Download packages.
   uninstall Uninstall packages.
...
```

**Comment by coolreader18** [comment]
The thing about `str.__add__` is that it's actually the slot `sq_concat`, that gets mapped to the wrapper method `__add__`. When we do `a + b`, what needs to happen is:

1. Check if a has the slot `nb_add`/magic method `__add__`
1. Check if b has `nb_add` (I think?) or `__radd__`
1.  Then, look at sq_concat for a (and maybe b if it doesn't have it, but I don't think so).

**Comment by coolreader18** [comment]
Also, I've looked into binding to expat, and it might be easier to just skip importing plistlib for the time being, since I think it's used in a very niche way in pip.

**Comment by jamestwebber** [comment]
Whoa is this all? I was checking the dependencies as described in [this post](https://doughellmann.com/blog/2019/06/29/dependencies-between-python-standard-library-modules/) and it seemed a lot hairier. I would guess that to actually `pip install` will require many more things working.

**Comment by skinny121** [comment]
Yes that everything(I think), we have got most of core standard library importable at this point. I'm also expecting `pip install` to require more changes than this.

**Comment by mireille-raad** [comment]
is this done?

**Comment by infopensource** [comment]
How can i install this fucking pip!!!!!!!!!!

**Comment by mireille-raad** [comment]
@infopensource  does this help? https://asciinema.org/a/3pAZSfrFeIbEUzpPyXtvYZCeN
