### ISSUE TITLE
(-2) ** 0.5 yields NaN

### ISSUE THREAD

**Issue by lilydjwg** [RustPython/RustPython#1986]
## Feature

non-integer power of negative numbers.

## Python Documentation

* https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex

**Comment by youknowone** [comment]
CPython:
```
>>> float.__rpow__(0.5, -2)
(8.659560562354934e-17+1.4142135623730951j)
```

RustPython:
```
>>>>> float.__rpow__(0.5, -2)
NaN
```

**Comment by minoring** [comment]
I am handling this issue :)
