### ISSUE TITLE
module 'sys' has no attribute 'getwindowsversion'

### ISSUE THREAD

**Issue by BasixKOR** [RustPython/RustPython#1996]
## Feature
`getwindowsversion` is Windows-specific Python function which returns the Windows version currently running.

### Note
```
Traceback (most recent call last):
  File ".\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File ".\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".\Lib\test\__main__.py", line 1, in <module>
    from test.libregrtest import main
  File ".\Lib\test\libregrtest\__init__.py", line 4, in <module>
    from test.libregrtest.cmdline import _parse_args, RESOURCE_NAMES, ALL_RESOURCES
  File ".\Lib\test\libregrtest\cmdline.py", line 4, in <module>
    from test import support
  File ".\Lib\test\support\__init__.py", line 942, in <module>
    if sys.getwindowsversion().platform >= 2:
AttributeError: module 'sys' has no attribute 'getwindowsversion'
```

This error was found while running the CPython unit tests via `cargo run --release -- -m test`.

## Python Documentation
https://docs.python.org/3.8/library/sys.html#sys.getwindowsversion

**Comment by BasixKOR** [comment]
Related to #1754

**Comment by youknowone** [comment]
For now, RustPython doesn't have `sys.getwindowsversion` function.

New function is preferred to be added in `vm/src/sysmodule.rs`. See `extend_module!` part around line 400 to see how to add a new function to a module. This function exists only in windows. Search for `#[cfg(windows)]` in the same file to check other use case.

Here is corresponding CPython implementation. https://github.com/python/cpython/blob/v3.8.3/Python/sysmodule.c#L1447-L1515 

`PyStructSequence` in CPython is handled with `#[pystruct_sequence]` in RustPython. This commit will be a good example:
https://github.com/RustPython/RustPython/pull/1990/commits/cd64884180ea82e02ea70e8dab2d59b735dcc6fe

**Comment by BasixKOR** [comment]
Thanks for tip! I'll open a PR with basic implementation for this (without `platform_version`).
