### ISSUE TITLE
could not compile `rustpython-vm`.

### ISSUE THREAD

**Issue by KnightBlood** [RustPython/RustPython#2014]
E:\RustPython>cargo run
   Compiling rustpython-vm v0.1.2 (E:\RustPython\vm)
error: Python compile error from Lib/python_builtins/_frozen_importlib.py: Got unexpected token '.' at line 1 column 1
  --> vm\src\frozen.rs:21:18
   |
21 |     ext_modules!(dir = "Lib/python_builtins/");
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: Python compile error from Lib/core_modules/copyreg.py: Got unexpected token '.' at line 1 column 1
  --> vm\src\frozen.rs:27:22
   |
27 |         ext_modules!(dir = "Lib/core_modules/");
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

error: could not compile `rustpython-vm`.

To learn more, run the command again with --verbose.

E:\RustPython>

**Comment by KnightBlood** [comment]
E:\RustPython>powershell scripts/symlinks-to-hardlinks.ps1
scripts/symlinks-to-hardlinks.ps1 : 无法加载文件 E:\RustPython\scripts\symlinks-to-hardlinks.ps1，因为在此系统上禁止运
行脚本。有关详细信息，请参阅 https:/go.microsoft.com/fwlink/?LinkID=135170 中的 about_Execution_Policies。
所在位置 行:1 字符: 1
+ scripts/symlinks-to-hardlinks.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

E:\RustPython>

**Comment by KnightBlood** [comment]
= note: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\RustPython\target\debug\deps\librustpython_vm-04a67d35d5f9b68d.rlib(rustpython_vm-04a67d35d5f9b68d.45bioiq4ejafbtot.rcgu.o): in function `rustpython_vm::stdlib::os::os_isatty':
          E:\RustPython/vm\src\stdlib/os.rs:1463: undefined reference to `_set_thread_local_invalid_parameter_handler'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\RustPython/vm\src\stdlib/os.rs:1463: undefined reference to `_set_thread_local_invalid_parameter_handler'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\RustPython\target\debug\deps\librustpython_vm-04a67d35d5f9b68d.rlib(rustpython_vm-04a67d35d5f9b68d.4kdrn674cfzoic2u.rcgu.o): in function `rustpython_vm::stdlib::msvcrt::msvcrt_putch':
          E:\RustPython/vm\src\stdlib/msvcrt.rs:38: undefined reference to `_set_thread_local_invalid_parameter_handler'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\RustPython/vm\src\stdlib/msvcrt.rs:38: undefined reference to `_set_thread_local_invalid_parameter_handler'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\RustPython\target\debug\deps\librustpython_vm-04a67d35d5f9b68d.rlib(rustpython_vm-04a67d35d5f9b68d.4kdrn674cfzoic2u.rcgu.o): in function `rustpython_vm::stdlib::msvcrt::msvcrt_putwch':
          E:\RustPython/vm\src\stdlib/msvcrt.rs:45: undefined reference to `_set_thread_local_invalid_parameter_handler'
          C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\RustPython\target\debug\deps\librustpython_vm-04a67d35d5f9b68d.rlib(rustpython_vm-04a67d35d5f9b68d.4kdrn674cfzoic2u.rcgu.o):E:\RustPython/vm\src\stdlib/msvcrt.rs:45: more undefined references to `_set_thread_local_invalid_parameter_handler' follow
          collect2.exe: error: ld returned 1 exit status


error: aborting due to previous error

error: could not compile `rustpython`.

To learn more, run the command again with --verbose.

**Comment by coolreader18** [comment]
Oh, I think the last one is a bug specifically for msys/mingw. I just pushed the branch `fix-mingw`, try checking that out and building it?

**Comment by KnightBlood** [comment]
> Oh, I think the last one is a bug specifically for msys/mingw. I just pushed the branch `fix-mingw`, try checking that out and building it?

 I have try it 

E:\RustPython>cargo run
   Compiling rustpython-vm v0.1.2 (E:\RustPython\vm)
error[E0308]: mismatched types
    --> vm\src\stdlib\os.rs:1458:49
     |
1458 |     unsafe { suppress_iph!(libc::isatty(fd)) != 0 }
     |                                                 ^ expected `()`, found integer

error[E0308]: mismatched types
  --> vm\src\stdlib\msvcrt.rs:55:17
   |
55 |     if flags == -1 {
   |                 ^^ expected `()`, found integer

error[E0308]: mismatched types
  --> vm\src\stdlib\msvcrt.rs:58:12
   |
58 |         Ok(flags)
   |            ^^^^^ expected `i32`, found `()`

error[E0308]: mismatched types
  --> vm\src\stdlib\msvcrt.rs:68:15
   |
68 |     if ret == -1 {
   |               ^^ expected `()`, found integer

error[E0308]: mismatched types
  --> vm\src\stdlib\msvcrt.rs:71:12
   |
71 |         Ok(ret)
   |            ^^^ expected `i32`, found `()`

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rustpython-vm`.

To learn more, run the command again with --verbose.

E:\RustPython>git branch -a
* fix-mingw
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/coolreader18/_pyio-_io
  remotes/origin/coolreader18/buildtime-sys-path
  remotes/origin/coolreader18/common-crate
  remotes/origin/coolreader18/constant-strings
  remotes/origin/coolreader18/ctx-rust-classes
  remotes/origin/coolreader18/pyimpl-on-trait
  remotes/origin/coolreader18/use-vm_class
  remotes/origin/coolreader18/wasm-_thread
  remotes/origin/coolreader18/wasm-jsvalue
  remotes/origin/cpython-unittest-guideline
  remotes/origin/delete-snippets-pow
  remotes/origin/dev-opt-level
  remotes/origin/fix-deployment-again-test
  remotes/origin/fix-mingw
  remotes/origin/framestack
  remotes/origin/function_attributes
  remotes/origin/master
  remotes/origin/parent_payload
  remotes/origin/readme-stdlib
  remotes/origin/redox-release
  remotes/origin/release
  remotes/origin/stack-size-calculation
  remotes/origin/test-deployment
  remotes/origin/unittest-lib
  remotes/origin/wasm-output

E:\RustPython>

**Comment by coolreader18** [comment]
Oh, whoops, that was my bad. Try pulling and building again.

**Comment by KnightBlood** [comment]
> Oh, whoops, that was my bad. Try pulling and building again.
E:\RustPython>cargo run
   Compiling rustpython-vm v0.1.2 (E:\RustPython\vm)
   Compiling rustpython v0.1.2 (E:\RustPython)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 47s
     Running `target\debug\rustpython.exe`

thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\debug\rustpython.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)

E:\RustPython>

**Comment by coolreader18** [comment]
Oh, try pulling again or just running with `--release`. That's fixed on the current master

**Comment by KnightBlood** [comment]
> Oh, try pulling again or just running with `--release`. That's fixed on the current master

successed

**Comment by coolreader18** [comment]
Thanks for bringing this to my attention and being patient working through this; it's always good to work out kinks the onboarding/new contributor experience :grin:
