### ISSUE TITLE
mmap is not implemented

### ISSUE THREAD

**Issue by tobark** [RustPython/RustPython#2059]
## Feature

Currently, I'm working on adding `test_os.py` test file. Then I met this error.

```
Traceback (most recent call last):
  File "Lib/test/test_os.py", line 15, in <module>
    import mmap
ModuleNotFoundError: No module named 'mmap'
```
[mmap](https://github.com/python/cpython/blob/master/Modules/mmapmodule.c) module in CPython is not implemented on RustPython.

## Python Documentation

https://docs.python.org/3/library/mmap.html

**Comment by coolreader18** [comment]
Hmm, yeah, that would be tricky. For now you can probably just comment out that import line and skip any tests that use `mmap`

**Comment by darleybarreto** [comment]
Perhaps translating [fmmap](https://github.com/friedelwolff/fmmap) and combining with [libffi-rs](https://github.com/tov/libffi-rs) would do the trick for now.

**Comment by youknowone** [comment]
nothing known progress

**Comment by youknowone** [comment]
not working, but #3564

**Comment by killme2008** [comment]
@youknowone  may i try this issue?

**Comment by youknowone** [comment]
@killme2008 sure! you can work on #3564 if you want. If you want to start from zero base, still it will be helpful to understand how you can add a new module.

**Comment by killme2008** [comment]
@youknowone  Great, thank you for the suggestion. I will read it.

**Comment by fanninpm** [comment]
After a significant amount of effort, #3755 has been merged.
