### ISSUE TITLE
%s formatting of byte strings in byte strings difference with CPython

### ISSUE THREAD

**Issue by glandium** [RustPython/RustPython#2121]
The following python code:
```
b"%s" % b"foo"
```

returns
```
b'foo'
```
with python but

```
b'b'foo''
```
with rustpython.

(btw the formatting of the output string in the REPL is not valid python)

**Comment by coolreader18** [comment]
Oh, wow, nice catch!

**Comment by glandium** [comment]
It's not really weird, given that that's the right output if the format string is a string rather than a bytestring. Looking at the code, the problem is that bytestring format strings are not treated differently.

**Comment by ChJR** [comment]
In CPython version 3.7
```
>>> b'%s' % 'a'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
>>> b'%b' % 'a'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
>>> b'%b' % b'a'
b'a'
>>> b'%s' % b'a'
b'a'
```

In RustPython commitID 249f1218
```
>>>>> b'%s' % 'a'
b'a'
>>>>> b'%b' % 'a'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unsupported method: decode
>>>>> b'%b' % b'a'
b'a'
>>>>> b'%s' % b'a'
b'b'a''
```

IMHO, making b'%s' to b'%b' will solve this issue.

**Comment by KipHamiltons** [comment]
This issue appears to have a PR fixing it merged
