### ISSUE TITLE
`bytes(bytes)` is inefficient

### ISSUE THREAD

**Issue by edwardycl** [RustPython/RustPython#2125]
## Feature

`bytes` object is immutable, so constructing a new `bytes` object from another `bytes` object doesn't need copying.
However, `PyBytes` and `PyByteArray` share `PyBytesInner` implementation, causing an unnecessary copying of immutable data.

CPython:
```
>>> b = b'foo'
>>> bytes(b) is b
True
```

RustPython:
```
>>> b = b'foo'
>>> bytes(b) is b
False
```

## Python Documentation

https://docs.python.org/3/library/stdtypes.html#bytes-objects

**Comment by awoimbee** [comment]
Fixed by #2284
@qingshi163 you should use github keywords (`Fixes #<issue number>`) ;)
