### ISSUE TITLE
[WASM] Expose the error message to JS when execution failed

### ISSUE THREAD

**Issue by shinglyu** [RustPython/RustPython#213]

**Comment by shinglyu** [comment]
Partially done with https://github.com/RustPython/RustPython/pull/226

But we still need to expose the error if a Python exception is raised but the interpreter didn't crash. e.g. 
```
x = [1,2,3]
print(x[10])  #IndexError 
```

**Comment by windelbouwman** [comment]
Can you return a rust Result into javascript? This would really be nice. Then we could check in javascript for `Ok` and `Err` cases.

**Comment by shinglyu** [comment]
Aha, `Result` exported to JS will be thow an exception is it's an `Err` https://rustwasm.github.io/wasm-bindgen/reference/types/result.html?highlight=exception#resultt-jsvalue
