### ISSUE TITLE
Add the "file" parameter to builtin "print()"

### ISSUE THREAD

**Issue by shinglyu** [RustPython/RustPython#219]
This is useful is we want to re-map the STDOUT to WASM's console (or something else) in a clean way.

**Comment by apatrushev** [comment]
Looks like this can be closed. Tested with following example on latest master:
```python
class A:
    def write(*args, **kwargs):
        print(args, kwargs)
print('a', file=A())
```
```bash
$ cargo run -- test.py
(<A object at 0x7fa77fcd5eb0>, 'a') {}
(<A object at 0x7fa77fcd5eb0>, '\n') {}
```
Llater found that test case was implemented in PR at `tests/snippets`.
