### ISSUE TITLE
[RFC] Iterator for memoryview

### ISSUE THREAD

**Issue by darleybarreto** [RustPython/RustPython#2195]
## Summary

This [issue](https://bugs.python.org/issue41732) on bugs.python (and [impl](https://github.com/python/cpython/commit/b0ac5d75a59c356c44cfc9b25077da3049dd16e9)) reports a patch to iterate over a memoryview object. 

## Detailed Explanation
I am new to Rust and RustPython project itself so I do not know a fast rusty way of implementing this.

## Drawbacks, Rationale, and Alternatives
I am not providing an implementation, so I cannot argue alternatives. :(

## Unresolved Questions
I don't know.

**Comment by qingshi163** [comment]
@youknowone this issue is fixed by #2226 , can we close it?
