### ISSUE TITLE
[WASM] Expose stdout to JavaScript

### ISSUE THREAD

**Issue by shinglyu** [RustPython/RustPython#221]
This is required to build a completely in-page (without using console) demo.

I'm planning to do this in steps:

1. Create a new `run_code_with_stdout` (better naming suggestion is very welcome) function in WASM, which `print` to a Rust variable. Then after `vm.run_code_obj` finishes, return the Rust variable containing the stdout to JS. This way we can build a editor demo (input python code, run, print to a stdout textarea).

2. Do not return the whole stdout back to JS, which requires memory copying. Instead use `WebAssembly.Memory()` to let JS directly access the WSAM memory space to get the stdout string.

3. Implement the #219 and #220, then we can override the `print` function's output by overriding `sys.stdout` during vm creation, rather then overriding `print`

**Comment by windelbouwman** [comment]
Is it not easier to call a javascript function at this point: https://github.com/RustPython/RustPython/blob/master/wasm/src/wasm_builtins.rs#L25 ?

Then this function that we made ourselves could add the output in the HTML.

**Comment by shinglyu** [comment]
Hmmm, that might be a good alternative for step 1.
For demo purpose maybe the performance difference for 2 is not that significant.
step 3 might still be desirable for code cleanness

**Comment by shinglyu** [comment]
https://github.com/RustPython/RustPython/pull/222
