### ISSUE TITLE
Embedding RustPython

### ISSUE THREAD

**Issue by d00z3l** [RustPython/RustPython#2242]
I have found it difficult to get started with embedding RustPython in my project and thought I could share it here in case anyone else was having the same issues. If I am doing something wrong I welcome any feedback!

The first issue was that crates.io is outdated and the `examples/ ` in the source doesn't work with that version of RustPython. To include the latest in my Cargo.toml I am using the following:
```toml
[dependencies]
rustpython-vm = { git = "https://github.com/RustPython/RustPython" }
rustpython-compiler = { git = "https://github.com/RustPython/RustPython" }
```

Second issue is that I couldn't compile rustpython_vm (I am on Windows). To fix that I needed to (#1624):
1. Locate where cargo stored the rustpython_vm, the default is: `%UserProfile%\.cargo\git\checkouts\rustpython-<ID>`
1. Open a new cmd session in this location.
1. From the command line run: `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`
1. From the command line run: `powershell scripts\symlinks-to-hardlinks.ps1`

Sample code after following these steps to execute a simple python script using a Rust native function:

```rust

use rustpython_vm::{obj::objfloat::PyFloat, pyobject::ItemProtocol};

#[test]
fn test_python_func() {

    // This function will be called from python
    fn add(a: f64, b: f64) -> f64 {
        a + b
    }

    rustpython_vm::Interpreter::default().enter(|vm| {
        
        // Create the scope
        let scope = vm.new_scope_with_builtins();
        // Set the add function in global scope
        scope.globals.set_item("add", vm.ctx.new_function(add), vm).expect("failed");
        scope.get_locals().set_item("a", vm.new_pyobj(40.0), vm).expect("failed");
        scope.get_locals().set_item("b", vm.new_pyobj(2.0), vm).expect("failed");

        // Compile the code using Eval mode so it returns a value
        let code_obj = vm.compile(
                r#"add(a, b)"#,
                rustpython_compiler::compile::Mode::Eval,
                "<embedded>".to_owned(),
            )
            .map_err(|err| vm.new_syntax_error(&err)).expect("failed..");

        // Run the script and get the result
        let result = vm.run_code_obj(code_obj, scope.clone()).expect("failed...");
        let val = result.downcast::<PyFloat>().expect("failed");
        assert_eq!(val.to_f64(), 42.0);

    });

}
```

**Comment by coolreader18** [comment]
This is a great resource! Yeah, using as a dependency isn't great right now; we're hoping to get the project to a stable enough state soon™ so that we can release 0.2 on crates.io, which would fix the windows symlink problem
