### ISSUE TITLE
Embedding and multiple threads

### ISSUE THREAD

**Issue by d00z3l** [RustPython/RustPython#2243]
Hi,

I am interested in how to integrate RustPython so that scripts can be called by multiple threads. Am I right in thinking that each thread would need to run it's own interpreter or can one be shared with each thread having a different scope?

**Comment by coolreader18** [comment]
You can look at `vm/src/stdlib/thread.rs` to see how threads are implemented internally; are you looking to enter into the vm from a thread that you started? e.g.

```rust
let vm = ...;
for i in 0..10 {
    let vm = vm.clone(); // or something
    let userfunc = userfunc.clone();
    thread::spawn(move || vm.invoke(&userfunc, vec![vm.ctx.new_pyobj(i)]));
}
```

Something along those lines? Just trying to figure out how specifically you want to do this, I think we probably could provide a `vm.start_thread(impl FnOnce(&VirtualMachine) -> R) -> JoinHandle<R>`

**Comment by d00z3l** [comment]
I want to use Python scripts as an ETL interface so that users could write scripts and then execute as required. Steps would be:
1. User writes script and compiles it.
1. User or scheduled job executes the script at a later time.

I am not sure an interface is required but I an interested in what can be shared (or NOT). Ideally the compiled scripts and global scope with built-in and custom functions could be created once and shared with locals being set on each execution.

**Comment by coolreader18** [comment]
Yep, it's totally possible to share builtins/modules/globals between threads. What I meant by interface is just a `vm.start_thread()` method with that signature. If that was available to you (with the vm passed to the closure having the same builtins and stuff as the vm on the main thread) do you think that would make your use case possible? You could share globals by just taking a function from the defined scope, e.g.

```py
foo = 1
def bar():
    global foo
    foo += 1
```

If you get the `bar` object from that scope and `vm.invoke()` it will properly have access to the globals it expects to.

**Comment by d00z3l** [comment]
Yep, `start_thread` would work, that make it a very simple process and seams safer than doing it yourself outside of RustPython.

**Comment by d00z3l** [comment]
Hi @coolreader18,

Thanks for being so responsive!

What are the steps to do it with current code base? I am trying to understand how the vm, scope and compiled statements tie together. There is lots of things going on in the code base so it is hard for me to understand. For example the PyNativeFunc is created via vm.ctx.new_function, does that mean that function can only be used with that vm?

In terms of scope, how do load all of my standard stuff into globals and reuse that with locals? The API implies that the scope is tied to the vm. Is below the correct way to reuse the globals (or is the parent scope below mutable):

```rust
// Create the parent scope with globals
let scope = vm.new_scope_with_builtins();
// Set the add function in global scope
scope.globals.set_item("add", vm.ctx.new_function(add), vm).expect("failed");
// Create a child scope with locals
let scope_child = scope.new_child_scope(&vm.ctx);
scope_child.get_locals().set_item("a", vm.new_pyobj(40.0), vm).expect("failed");
scope_child.get_locals().set_item("b", vm.new_pyobj(2.0), vm).expect("failed");
// Run a script with scope_child...
```

Also in terms of overhead what is the cost in creating a vm and scopes?

**Comment by coolreader18** [comment]
Ah, yeah, I can see how that might be confusing. You can think of the vm passed to the function for `start_thread` as the same vm, or rather, the same interpreter; objects can move between them in any way you want and the `builtins`, `sysmodule`, `ctx`, etc fields are all the same as the original vm.

**Comment by coolreader18** [comment]
The scope isn't tied to the vm, we just use the vm as a catch-all for any functions that require access to the vm. The parent scope is mutable, but yeah, that's the correct way to do it. And in terms of overhead, it should be pretty quick; you can see the overhead of the thread vm creation; it's mostly just cloning a few `Arc`s. And dicts are created all the time in python, and that's all a scope is, pretty much.
