### ISSUE TITLE
[CFP] Implement the _sre module in Rust

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#2258]
At the moment, `_sre` is a modified version of `_sre.py` from an old version of PyPy: https://github.com/nikhaldi/_sre.py.

This is **s l o w**. If you ctrl-C rustpython while it's running a decently complex script, there's a good chance that the traceback from the `KeyboardInterrupt` will have originated somewhere in `_sre.py`. While it's definitely possible to implement `_sre` in Rust -- I was able to modify the constant-generation script to output Rust instead of C code -- both the C and Python versions of `_sre` don't really lend well to simple/direct translation to Rust. The C version ([`_sre.c`](https://github.com/python/cpython/blob/master/Modules/_sre.c)/[`sre_lib.h`](https://github.com/python/cpython/blob/master/Modules/sre_lib.h)) uses lots of pointer arithmetic and a kind of "as long as we own an active reference to the str object, we can send pointers anywhere we want" approach that doesn't jive well with Rust's memory-safety rules. The Python version (`Lib/_sre.py` in the RustPython source tree) uses enough nested references (`context.x_stack[n].context is context`), generator functions, and dynamic typing that it's also tricky to translate to Rust.

If anyone wants to take a stab at this, I've left a scaffold of the implementation in the [`_sre-wip`](https://github.com/RustPython/RustPython/tree/_sre-wip) branch, that has the SRE constants available to Rust, and some of my sketches for how it might work, but no real functionality. Be warned, either route you go to emulate is tricky, so feel free to try whichever approach you think would be easier.

**Comment by darleybarreto** [comment]
[pyre2](https://github.com/facebook/pyre2) and Jython's _sre [[1](https://github.com/jython/jython/blob/master/src/org/python/modules/_sre.java),[2](https://github.com/jython/jython/tree/master/src/org/python/modules/sre)] might help on this.

**Comment by qingshi163** [comment]
Should we implement it by follow CPython that compile to bytecode? I did not look deep into the code yet, but can we do like compile to Vec<Enum>? Anything that may tricky?

**Comment by darleybarreto** [comment]
I think that doing something like [pyre2](https://github.com/facebook/pyre2) would be better, but using [regex](https://github.com/rust-lang/regex) in the backend instead of [re2](https://github.com/google/re2/).

**Comment by coolreader18** [comment]
@darleybarreto Unfortunately, we can't use the regex crate, as it doesn't support lookbehinds and all the other fancy features that sre has.

@qingshi163, I'm not sure exactly what you're asking, but Python code in the `sre_compile` module compiles the regex to bytecode, the `_sre` module "just" has to interpret it. I think the scaffold already collects the bytecode into a `Vec<u32>`

**Comment by darleybarreto** [comment]
> @darleybarreto Unfortunately, we can't use the regex crate, as it doesn't support lookbehinds and all the other fancy features that sre has.

Hmm, do you know all the fancy features that it has (and we can't use `regex`)? Depending on what those are, we could simply "avoid" them for as long as we can.

**Comment by darleybarreto** [comment]
Or perhaps [fancy-regex](https://github.com/fancy-regex/fancy-regex).
