### ISSUE TITLE
Implement variable mangling for private fields

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#2296]
## Feature

In cpython
```python
>>> class A:
...  def __init__(self):
...   self.__a = 1
... 
>>> a = A()
>>> a.__a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute '__a'
>>> a._A__a
1
```

In Rustpython
```python
>>>>> class A:
.....  def __init__(self):
.....   self.__a = 1
..... 
>>>>> a = A()
>>>>> a.__a
1
```

In python, the field of the class starting with `__` is a private field,
and mangling is performed to prevent external access to the same variable.

Currently, this has not been done in `Rustpython`.

## Python Documentation
https://github.com/python/cpython/blob/3185267400be853404f22a1e06bb9fe1210735c7/Python/compile.c#L254-L256
In cpython, it is probably mangled using the above function.

**Comment by coolreader18** [comment]
@HyeockJinKim yep, go ahead!

**Comment by aaronclong** [comment]
Is this still open, might take a crack at it?

**Comment by coolreader18** [comment]
@aaronclong oh, sorry, this was fixed a little while ago, I forgot there was an issue for it. If you're interested in bytecode compiler stuff, the main thing I can think of now is `async for` comprehensions (#2510)
