### ISSUE TITLE
Passing complex rust data

### ISSUE THREAD

**Issue by d00z3l** [RustPython/RustPython#2321]
Hello,

I am trying to embed RustPython into my application. I would like to pass a struct with an API and expose it's methods to the Python script. I have looked at the examples but they seem limited to static data and functions. Is there any way to do this at the moment or plans to add it in the future?

**Comment by coolreader18** [comment]
Oh, yes, there's definitely a way to do that, and thanks for asking this cause that would definitely be beneficial to have as an example. You can look at `wasm/lib/src/js_module.rs` to see a fairly simple example of this, wrapping the rust struct `wasm_bindgen::JsValue` in a RustPython class/struct `PyJsValue`. Basically, you just have to have a struct with the `#[pyclass]` attribute on it, impl PyValue like in `js_module.rs`, and then have `#[pyimpl] impl MyPythonClass {}`, where you can optionally have methods tagged as `#[pymethod] fn my_method(&self, foo: i32, vm: &VirtualMachine)`. If you want to create the struct as a Python value, you can return it from a native Python function (`fn make_thing() -> MyPythonClass` or `fn make_thing() -> PyResult<MyPythonClass>`), and to accept it as an argument/extract it from a PyObjectRef you can just have methods on the pyimpl that take `&self` or have a type alias like `type MyPythonClassRef = PyRef<MyPythonClass>;`  and then do either `fn do_thing(x: MyPythonClassRef)` or `let x = MyPythonClassRef::try_from_object(vm, obj);`

**Comment by d00z3l** [comment]
Thanks, I will give it a try and report back.

**Comment by d00z3l** [comment]
Hi @coolreader18,

I have given it a try but I am not sure static_type() does and whether I should be using it and how to create and pass the struct to a script. 

Here is my attempt, that fails with: `static type has not been initialized'. I know how I am passing the struct as global is incorrect but i am not sure how to do it. Any help appreciated.

```rust
#[pyclass(module=false, name = "API")]
#[derive(Debug)]
pub struct PyAPI {
    value: f64,
}

impl PyValue for PyAPI {
    fn class(_vm: &VirtualMachine) -> &PyTypeRef {
        Self::static_type()
    }
}

impl AsRef<PyAPI> for PyAPI {
    fn as_ref(&self) -> &PyAPI {
        &self
    }
}

#[pyimpl]
impl PyAPI {
    #[pymethod]
    pub fn add(&self, val: PyFloatRef) -> PyFloat {
        PyFloat::from(self.value + val.to_f64())
    }
}

#[test]
fn test_python_ab_fn() {

    rustpython_vm::Interpreter::default().enter(|vm| {
        
        let scope = vm.new_scope_with_builtins();
        let a = PyAPI{value: 40.0};
        scope.get_locals().set_item("a", vm.new_pyobj(a), vm).expect("failed");
        scope.get_locals().set_item("b", vm.new_pyobj(2.0), vm).expect("failed");

        let code_obj = vm.compile(
                r#"a.add(b)"#,
                rustpython_compiler::compile::Mode::Eval,
                "<embedded>".to_owned(),
            )
            .map_err(|err| vm.new_syntax_error(&err)).expect("failed..");
        let result = vm.run_code_obj(code_obj, scope.clone()).expect("failed...");
        let val = result.downcast::<PyFloat>().expect("failed");
        assert_eq!(val.to_f64(), 42.0);

    });

}
```

**Comment by coolreader18** [comment]
Ah, yeah, you need to call `PyAPI::make_class(&vm.ctx)` before you call into anything that might call `PyAPI::static_class()` (e.g., before you call any Python code that uses the class)

**Comment by d00z3l** [comment]
Thanks that works! Full code below if anyone else needs to get it working:

```rust

use rustpython_vm::{builtins::*, pyobject::{ItemProtocol}};
use rustpython_derive::{pyimpl, pyclass};
use rustpython_vm::pyobject::{PyValue, StaticType, PyClassImpl};
use rustpython_vm::VirtualMachine;

#[pyclass(module=false, name = "API")]
#[derive(Debug)]
pub struct PyAPI {
    value: f64,
}

impl PyValue for PyAPI {
    fn class(_vm: &VirtualMachine) -> &PyTypeRef {
        Self::static_type()
    }
}

impl AsRef<PyAPI> for PyAPI {
    fn as_ref(&self) -> &PyAPI {
        &self
    }
}

#[pyimpl]
impl PyAPI {
    #[pymethod]
    pub fn add(&self, val: PyFloatRef) -> PyFloat {
        PyFloat::from(self.value + val.to_f64())
    }
}

#[test]
fn test_python_ab_fn() {

    rustpython_vm::Interpreter::default().enter(|vm| {
        
        PyAPI::make_class(&vm.ctx);
        let scope = vm.new_scope_with_builtins();
        let a = PyAPI{value: 40.0};
        scope.get_locals().set_item("a", vm.new_pyobj(a), vm).expect("failed");
        scope.get_locals().set_item("b", vm.new_pyobj(2.0), vm).expect("failed");

        let code_obj = vm.compile(
                r#"a.add(b)"#,
                rustpython_compiler::compile::Mode::Eval,
                "<embedded>".to_owned(),
            )
            .map_err(|err| vm.new_syntax_error(&err)).expect("failed..");
        let result = vm.run_code_obj(code_obj, scope.clone()).expect("failed...");
        let val = result.downcast::<PyFloat>().expect("failed");
        assert_eq!(val.to_f64(), 42.0);

    });

}
```

**Comment by d00z3l** [comment]
Hi @coolreader18,

Follow up question, is there any way to make the methods on the struct global so they can accessed like so:

```python
add(b)
```

**Comment by coolreader18** [comment]
You could probably do that from the Python side, something like

```py
for attr in ('add', etc):
    globals()[attr] = getattr(a, attr)
```

**Comment by d00z3l** [comment]
Thanks!
