### ISSUE TITLE
[RFC] AST Customization

### ISSUE THREAD

**Issue by pca006132** [RustPython/RustPython#2388]
## Summary

Provide means to customize the AST, for including additional data with each node.

## Detailed Explanation

Background: I'm currently developing a compiler for a subset of Python, currently planning to use the RustPython parser to get the AST. The project requires type inference and other processing with the AST. It would be helpful if we can attach data to each node in the AST. 

I think allowing users to store custom data in AST nodes would also help other developers to use the crate for other purposes, like static analysis, or provide better optimization for the RustPython runtime by trying to recover more type information (not sure if this is feasible though, I am not familiar with the project).

I think it would be possible to provide an additional field using generic with a default value. For example:
```rust
pub struct Located<T, U = ()> {
    pub location: Location,
    pub node: T,
    pub custom: Option<U>,
}
```
And add the `U` parameter to all references to `Located` (`Expression`, `Statement`, ... basically all structs in the AST and parser methods)

With the default parameter, I think it would not break the existing code as users can still use `Expression<U>` as `Expression`.
This may also break pattern matching, but that would just require the users to add `..` to the pattern so it should be simple.

## Drawbacks, Rationale, and Alternatives

Drawbacks:
- May break pattern matching in existing code.
- The default type `U = ()` would increase the size of the `Located` struct. One way to prevent the problem would be to use the never type `!`, but this requires nightly. The following code print 16 and 8 in the rust playground.
  ```rust
  #![feature(never_type)]
  struct Test<U = ()> {
      a: usize,
      b: Option<U>
  }
  
  fn main() {
      println!("{}", std::mem::size_of::<Test>());
      println!("{}", std::mem::size_of::<Test<!>>());
  }
  ```

An alternative would simply be not supporting the additional field and require users to store it elsewhere, maybe using HashMap or another tree. That would be harder to use and suffer from performance problems.

**Comment by coolreader18** [comment]
The default could also be `std::convert::Infallible`, which is almost equivalent to the never type and will eventually become a type alias for `!` once the latter is stabilized.

**Comment by coolreader18** [comment]
I think this definitely sounds cool! Would you be interested in implementing it?

**Comment by pca006132** [comment]
> The default could also be `std::convert::Infallible`, which is almost equivalent to the never type and will eventually become a type alias for `!` once the latter is stabilized.

Yes, it seems that the resulting size is the same as `!`.

> I think this definitely sounds cool! Would you be interested in implementing it?

Yes.

**Comment by coolreader18** [comment]
Oh, or maybe the default should be `()` and the field should just be `custom: U`? Cause since we're probably going to be mapping to the custom type after-the-fact, the map function could just return a default value. If you wanted to have it be an `Option<A>`, you could pass a mapping function `|()| None`, and fill the options in manually. But if it's a hashmap or a vec or some other collection, it might also make sense to have the default be a `Collection::new`

**Comment by pca006132** [comment]
> Oh, or maybe the default should be `()` and the field should just be `custom: U`? Cause since we're probably going to be mapping to the custom type after-the-fact, the map function could just return a default value. If you wanted to have it be an `Option<A>`, you could pass a mapping function `|()| None`, and fill the options in manually. But if it's a hashmap or a vec or some other collection, it might also make sense to have the default be a `Collection::new`

What about `U: Default`?

```rust
struct Test<U = ()> {
    custom: U
}

impl<U: Default> Test<U> {
    fn new() -> Test<U> {
        Test {
            custom: Default::default()
        }
    }
}

fn main() {
    let a: Test = Test::new();
    let b: Test<Vec<&str>> = Test::new();
}
```

**Comment by coolreader18** [comment]
I agree, but I don't think it's possible to put generics in the lalrpop file, which is what actually generates the ast
