### ISSUE TITLE
bash script / github workflow to generate csv out of whats_left.sh  

### ISSUE THREAD

**Issue by mireille-raad** [RustPython/RustPython#2400]
In this previous PR https://github.com/RustPython/RustPython/pull/1865 , I made some tweaks to `whats_left.sh` to generate yaml files. The goal is to display some sort of dashboard on the website (rustpython.github.io). Eventually we didn't merge the PR because it meant that we needed to add some more flags or argument for the script (which I never got around to).

Here is a easier suggestion for a new bash script that we can run as a github workflow.   
The script:
- generates csv files
- cleans up some output from the whats_left script that we are not likely to display on the site
- creates two separate files (one for missing entire modules and one for missing functions and classes)

Here is what the script looks like:

``` bash
#!/bin/bash

# run whats_left and save the output to a temp file
# use grep to remove some test output like hello world and constant string
sh ./whats_left.sh | grep -v 'Constant String' | grep -v 'Hello world'  > whats_left.temp

# start a new csv file that has the modules
echo "module" > whats_left_modules.csv
# read the temp file and look for "entire module" 
cat whats_left.temp | grep "entire module"  >> whats_left_modules.csv

# start a new csv file that has just the missing functions and classes
echo "module, partial" > whats_left_partials.csv
# get the diff between the full list and the module list
# remove some keywords like "existing but not importable"
# replace the "." with "," which nicely creates a new column in csv
grep -v -f  whats_left_modules.csv whats_left.temp | grep -v 'existing but not importable' |  tr "." "," >> whats_left_partials.csv
```

I tested that jekyll can actually read and display the data with a simple loop, for example.
```
 {% for item in site.data.whats_left_modules %}
      <li>
        {{ item.module }}  
      </li>
    {% endfor %}
```
For the second file, jekyll layout needs to be more fancy and group by the module name.

Anyway.... this is the whole script that is needed and it re-uses `whats_left.sh`

- is this a better solution than my previous attempt at a PR?
- should I submit this bash script as a PR for a file here? I thought creating a new one like `whats_left_workflow.sh` is just weird and looks like clutter.
- adding those instructions in the github workflow is also weird

any thoughts?

**Comment by coolreader18** [comment]
Oh, nice! I think this looks pretty good, it might be possible to just add as an option to `whats_left.sh`, like `if [[ $1 = --csv ]]; then <your code>; exit 0; fi`

**Comment by mireille-raad** [comment]
The `whats_left.sh` script takes parameters on these lines.

```bash
cargo build --release
if [ $# -eq 0 ]; then
  sections=(${ALL_SECTIONS[@]})
else
  sections=($@)
fi 
```

So if i was to add one more parameter as a csv flag, the order becomes important or we'll have to use named parameters and document 😢 stuff somewhere, no?

I tested your suggestion 
- `./whats_left.sh --csv `works,
-  `./whats_left.sh modules` works,
-  `./whats_left.sh --csv modules` wouldn't.

How about, I just edit `.github/workflows/cron-ci.yaml` here to save whats_left to the rustpython.github.io repo and I add the data cleaning and formatting script there instead. It would be more neat/organized anyway.

**Comment by coolreader18** [comment]
> How about, I just edit .github/workflows/cron-ci.yaml here

Sure, that sounds good :+1:
