### ISSUE TITLE
Implement remaining functions for 'list'

### ISSUE THREAD

**Issue by shinglyu** [RustPython/RustPython#251]
I'm planning to work on this for the new year. :)

**Comment by shinglyu** [comment]
Note to self: sort has a placeholder but it's not implemented

**Comment by shinglyu** [comment]
Just finished `list.index()`, will add more test and refine the `ValueError` description before creating a PR.

**Comment by shinglyu** [comment]
#254

**Comment by makarchuk** [comment]
I've implemented `list.pop`


Python test for error case is a bit weird for now
```
except Exception as e:
    assert(str(e).startswith("IndexError"))
```

It's because `IndexError` is not in global namespace, which seems to be a reason for another issue, don't you think?

**Comment by windelbouwman** [comment]
Okay, IndexError should be placed in the global namespace as well.

**Comment by dralley** [comment]
It looks like, currently, as per the results of ```dir()```:

Python 3.7 ```list()``` has these methods that RustPython does not have or expose:

'__init_subclass__',
 '__reduce__',
 '__reduce_ex__',
 '__sizeof__',

And RustPython ```list()``` has these methods that CPython does not have or expose:

'__bool__',
 '__dict__',

Although, obviously Python 3.7 lists can be interpreted as bools so I'm not sure why it's missing, maybe they take a shortcut.

**Comment by youknowone** [comment]
now the only unimplemented method is `list.__init_subclass__`, so this issue seems practically done.
