### ISSUE TITLE
Cannot build from source on FreeBSD 12.2

### ISSUE THREAD

**Issue by Canvis-Me** [RustPython/RustPython#2511]
I set up a  local rustup environment(stable, 1.50.0) to build it from source, however it failed.

Additional error information was attached.

[error.log](https://github.com/RustPython/RustPython/files/6074344/error.log)

**Comment by coolreader18** [comment]
@Canvis-Me could you try with the `freebsd` branch? I think I fixed most of the errors there.

**Comment by Canvis-Me** [comment]
@coolreader18 Hello, thanks for your help! I checked out the freebsd branch and run 'cargo run --release'. There were still some errors.
[RP_error_fbd.log](https://github.com/RustPython/RustPython/files/6099432/RP_error_fbd.log)

**Comment by coolreader18** [comment]
Alright, could you try again?

**Comment by Canvis-Me** [comment]
It's OK, no error anymore. Thank you!
