### ISSUE TITLE
could not compile `rustpython-vm`

### ISSUE THREAD

**Issue by KnightBlood** [RustPython/RustPython#2616]
OS:Windows 10
Compiler:Msys2 With Rust

error：
` Compiling rustpython-vm v0.1.2 (E:\RustPython\vm)
error[E0432]: unresolved imports `nt::_set_thread_local_invalid_parameter_handler`, `nt::silent_iph_handler`
    --> vm\src\stdlib\os.rs:3124:14
     |
3124 | pub use nt::{_set_thread_local_invalid_parameter_handler, silent_iph_handler};
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^ no `silent_iph_handler` in `stdlib::os::nt`
     |              |
     |              no `_set_thread_local_invalid_parameter_handler` in `stdlib::os::nt`

warning: unused import: `crate::builtins::list::PyListRef`
    --> vm\src\stdlib\os.rs:2767:9
     |
2767 |     use crate::builtins::list::PyListRef;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rustpython-vm`

To learn more, run the command again with --verbose.`

**Comment by KnightBlood** [comment]
Rust Version：1.51.0
LLVM version ：11.0.0

**Comment by coolreader18** [comment]
Huh, I think that's a disconnect between one part of the codebase that has `cfg(all(windows, target_env = "msvc"))` and another that's just `cfg(windows)`. Shouldn't be too hard to fix, I think

**Comment by coolreader18** [comment]
@KnightBlood could you try checking out the `coolreader18/fix-windows-symlinks` branch? I just stuck it in there cause there are already windows-related fixes, but it should work.

**Comment by KnightBlood** [comment]
> @KnightBlood could you try checking out the `coolreader18/fix-windows-symlinks` branch? I just stuck it in there cause there are already windows-related fixes, but it should work.

warning: unused import: `crate::builtins::list::PyListRef`
    --> vm\src\stdlib\os.rs:2767:9
     |
2767 |     use crate::builtins::list::PyListRef;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(unused_imports)]` on by default

   Compiling rustpython v0.1.2 (E:\RustPython)
warning: 1 warning emitted

**Comment by KnightBlood** [comment]
> @KnightBlood could you try checking out the `coolreader18/fix-windows-symlinks` branch? I just stuck it in there cause there are already windows-related fixes, but it should work.

warning: unused import: `crate::builtins::list::PyListRef`
    --> vm\src\stdlib\os.rs:2767:9
     |
2767 |     use crate::builtins::list::PyListRef;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(unused_imports)]` on by default

   Compiling rustpython v0.1.2 (E:\RustPython)
warning: 1 warning emitted

**Comment by coolreader18** [comment]
Right, but it still compiles, that's just a warning.
