### ISSUE TITLE
Missing  typing._SpecialForm

### ISSUE THREAD

**Issue by oroppas** [RustPython/RustPython#2622]
## Feature

typing._SpecialForm

## Python Documentation

https://docs.python.org/3/library/typing.html?highlight=typing#module-typing
https://github.com/python/cpython/blob/3.9/Lib/typing.py#L317

**Comment by fanninpm** [comment]
@coolreader18 `typing.py` [radically changed in Python 3.7 as a result of PEP 560](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep560). However, RustPython currently uses the version from Python 3.6. My attempts to update this module have been unsuccessful - I can try to provide more context later today.

**Comment by oroppas** [comment]
Thank you!
