### ISSUE TITLE
Does the project support using  python module with rust multi-thread project and compile into binary?

### ISSUE THREAD

**Issue by dbsxdbsx** [RustPython/RustPython#2624]
I create this "issue" because I am not quite sure about the features of this project.  
I want to  build a rust-based binary application, but I need to use some tool(module) from python. Then I found "PyO3", the crate can let I use python moduel in rust. But there 2 weaks I faced:
1) I can't take multi-thread feature in Rust if I use python module there, because of GIL;
2) Even with app compiled, I have to install python interpreter in target host with built rust app and used python script.

In a word, I want to code with rust while using python script, and finally output a sole binary app---Can `RustPython` solve these troubles? (I've noticed `RustPython` could support multi-thread in python script)
And Is it essential to install something else like "JIT"machine with my output binary app?

**Comment by pca006132** [comment]
I don't think this fits your usecase, this is a python interpreter.
Also, this does not support all python packages at this moment.

Regarding your problem: What packages do you want to call from Rust? Is there any libraries with that feature in Rust? I don't think calling Python from Rust would be a good idea if you want better performance.

**Comment by dbsxdbsx** [comment]
@pca006132, because of GIL in python, I  would prefer to use rust fo multi-thread project, so I want to calling python from rust. As there is no replaceable crate in rust, so I hope find a way to transfer python code to rust, then I found this project.

**Comment by pca006132** [comment]
> @pca006132, because of GIL in python, I would prefer to use rust fo multi-thread project, so I want to calling python from rust. As there is no replaceable crate in rust, so I hope finding a way to transfer python code to rust, then I found this project.
> 
> At present, it seems that the most constructive way to do so is first making the used python module(library) as a binary library, then it could be used seemlessly in Rust---- But this way requires to modify the python module with some c code type, which would be tedious and fallible for most python user.
> 
> In addition, I thinks it is expected to transpile python code into Rust, like this project:[Pyrs](https://github.com/konchunas/pyrs), though it is far from mature to use.
> Now I would prefer using python to write code for logic, then transfer it to Rust for performance, with witch I think is an almost perfect routine for new project. **(As python is so mature for its ecosystem and Rust lacks ecosystem but good for robust programming, it is wasting time to rebuild wheel in Rust, WHY NOT just transferring libraries from python---to take both advantages from both languages?)**

The problem is that whenever you interact with Python code, you need to acquire the GIL, so it doesn't really work. Also, I don't think most python libraries would expect you to run the code concurrently, as they might have some global state that is not expecting concurrent execution, so even if the interpreter can get rid of the GIL, it might not be a good idea to call into whatever library and make the computation concurrent. I cannot give any suggestions without knowing your usecases.

**Comment by dbsxdbsx** [comment]
@pca006132 ，I agree with what you said. Frankly, I am doing  research on Reinforcement Learning with python module pytorch and OpenAi gym. OpenAi gym is used for simulating environments, and I need to run several different environtment at same time, at present , now I could only work around it using multiProcessing, but it is really memory consuming and it would reduce whole performance sometimes.   (I do found a crate that mimicing OpenAi gym, but still need acquire GIL :( )

**Comment by pca006132** [comment]
> @pca006132 ，I agree with what you said. Frankly, I am doing research on Reinforcement Learning with python module pytorch and OpenAi gym. OpenAi gym is used for simulating environments, and I need to run several different environtments at same time.t At present, I could only work around it using multiProcessing, but it is really memory consuming and it would reduce whole performance sometimes. (I do found a rust crate that mimicing OpenAi gym, but still need acquire GIL unamused )

I think the underlying libraries for these AI frameworks usually have multicore/GPU optimization already. I wonder if calling those APIs from multiple cores would provide any performance improvement. If the bottleneck is your sequential code, I think one way would be to rewrite the computation (avoid calling to python APIs) in Rust and call via pyo3. You really have to check where your bottleneck is.

**Comment by dbsxdbsx** [comment]
@pca006132 ， it is easy to do parallesim for AI framework(python module: pytorch), but it is difficult to do parallelism for simulation of the environment(python module: OpenAi gym). Therefore, I still need to rewrite some moudel in rust.

Anyway, thanks for your advice.
