### ISSUE TITLE
RustPython is not compilling! Why?

### ISSUE THREAD

**Issue by KorobeinikovIgor** [RustPython/RustPython#2673]
![image](https://user-images.githubusercontent.com/73735838/119549936-6dd49f00-bda0-11eb-898e-162382dda4dd.png)

**Comment by coolreader18** [comment]
Could you try running `rustup update`?

**Comment by KorobeinikovIgor** [comment]
![Uploading image.png…]()

**Comment by KorobeinikovIgor** [comment]
![image](https://user-images.githubusercontent.com/73735838/119610172-7dd09b00-be01-11eb-9589-bd54d5d965ef.png)

**Comment by coolreader18** [comment]
What's the output of `cargo -vV`?

**Comment by KorobeinikovIgor** [comment]
![Uploading image.png…]()

**Comment by KorobeinikovIgor** [comment]
![image](https://user-images.githubusercontent.com/73735838/119615087-aeb3ce80-be07-11eb-8424-dcdd49a94f65.png)

**Comment by KorobeinikovIgor** [comment]
![image](https://user-images.githubusercontent.com/73735838/119651128-5394d280-be2d-11eb-8eee-40a119c4f476.png)

**Comment by coolreader18** [comment]
Huh. How did you install Rust? Your toolchain is out of date, it should be like 1.52. Did you use your system package manager? Could you try updating it through that?

**Comment by KorobeinikovIgor** [comment]
i wrote later

**Comment by coolreader18** [comment]
The crates.io stuff doesn't matter, you have to use a newer version of rust to compile rustpython. I'm not sure how exactly your setup is, but we have this in the readme:

> RustPython requires Rust latest stable version (e.g 1.43.0 at May 24th 2020). To check Rust version: rustc --version If you wish to update, rustup update stable.

Latest stable version right now is 1.52.2.
