### ISSUE TITLE
Built-in methods/classes/functions lack documentation.

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#2680]
Most (?) of the built in functionality currently lacks corresponding documentation. The functionality to grab and attach the docs is there, the docs just haven't been added. 

This, I believe, could make a good first issue for many people, it just involves taking the documentation and adding it before (after works too but most current examples add it before) the `#[py(function/method/class)]` attribute. As an example, for `list.append` one could just add:

```rust
/// Append object to the end of the list.
#[pymethod]
pub(crate) fn append(&self, x: PyObjectRef) { ... }
```

The main built-in classes seem to have documentation for the classes but not for the methods. Builtin modules, I'd assume, probably also have many more cases.

**Comment by AthulMuralidhar** [comment]
this seems pretty straightforward. Can i start working on this on? @youknowone @DimitrisJim ?

**Comment by DimitrisJim** [comment]
Go ahead @AthulMuralidhar!

**Comment by nandhinianandj** [comment]
https://github.com/RustPython/RustPython/pull/3435 -- very first commit.. just getting used to process here.

**Comment by youknowone** [comment]
how about closing this issue by preference for #3101?
