### ISSUE TITLE
`Exception.__init__.__qualname__` is incorrectly set to `'BaseException.__init__'`

### ISSUE THREAD

**Issue by sobolevn** [RustPython/RustPython#2771]
## Feature

CPython:

```pycon
Python 3.9.4 (default, Apr  5 2021, 01:47:16) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> Exception.__init__.__qualname__
'Exception.__init__'
```

RustPython:

```
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> Exception.__init__.__qualname__
'BaseException.__init__'
```

**Comment by sobolevn** [comment]
I am working right now on this problem.

I also need to test this case:

```python
>>> class S(str):
...    ...
... 
>>> S.replace
<method 'replace' of 'str' objects>
```

**Comment by sobolevn** [comment]
Currently CPython uses [three macros](https://github.com/python/cpython/blob/ecc3c8e4216958d85385bf2467441c975128f26c/Objects/exceptions.c#L430-L476) to define different Exception types:
- SimpleExtendsException
- MiddlingExtendsException
- ComplexExtendsException

These macros copies different parts of `BaseException` attributes. Like `(initproc)BaseException_init` for `SimpleExtendsException` which is the root cause for this specific bugreport.

I am also planning to write macros to match the CPython implementation.
Does this sound ok?

**Comment by youknowone** [comment]
writing functions to match CPython macros, right?
I think we already have similar functions.

adding a doc parameter to `create_exception_type` will be same as `SimpleExtendsException`.
adding a few more for specific usage will be good.

**Comment by youknowone** [comment]
it seems I didn't catch your idea yet. are you planning to make something like `#[pyexception]` like `#[pyclass]`? or richer version of `extend_class!`?
If we need them to implement things, we need it. `SimpleExtendsException` looked like somewhat we already had to me, but maybe i overlooked the features of them.

**Comment by sobolevn** [comment]
> or richer version of extend_class!?

This looks easier and more flexible to me right now.

I will show you the code soon 🙂
