### ISSUE TITLE
Raising a user-defined class from itself causes interpreter crashing

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#2779]
In the following example, we define a class error, and instance it. When we execute raise e from e, Rust Python crashes.

test.py
```
class Error(Exception):
	pass

e = Error()
raise e from e

```

Actual output:

> Segmentation fault (core dumped)

System:

> Ubuntu 16.04
> Rust Python 0.1.2 interpreter

**Comment by DimitrisJim** [comment]
Another good find. Loops on `write_exception` in `exceptions.rs`. Thanks! Closing in favor of #2796

**Comment by sobolevn** [comment]
@DimitrisJim I don't think that this should raise `RecursionError` as described in #2796 

CPython:

```python
>>> class Error(Exception):
...     pass
... 
>>> e = Error()
>>> raise e from e
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
__main__.Error
```

I guess, this is a different case, where we need to fix `write_exception` implementation.

**Comment by DimitrisJim** [comment]
@sobolevn ah, you're right here. I rushed in triaging this.
