### ISSUE TITLE
panic occurs when a key in the dictionary is unhashable.

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#2799]
## Feature
In cpython, if the key in the dictionary is unhashable, only an error is raised.
```python
>>> {{}:2}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'dict'
```
But in rustpython, a panic is occurring.
```python
>>>>> {{}:2}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: [PyObj PyBaseException]', vm/src/frame.rs:1314:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by moreal** [comment]
Could you assign me for this issue if anyone is not working? I want to try this issue.

**Comment by youknowone** [comment]
Here is another issue with similar reason: https://github.com/RustPython/RustPython/pull/2803#issuecomment-894642909

**Comment by Arnab1181412** [comment]
Hey can this issue be assigned to me

**Comment by youknowone** [comment]
sure :)

**Comment by Arnab1181412** [comment]
Can I get some more context to the problem as I am a new contributor

**Comment by DimitrisJim** [comment]
Hey @Arnab1181412, see the previous pull request made. There's another instance in the same function where an `unwrap` is performed when it should instead propagate the error from `map_obj.set_item`.

**Comment by Arnab1181412** [comment]
Sure sir

**Comment by Arnab1181412** [comment]
Sir I have created a PR https://github.com/RustPython/RustPython/pull/2846#issue-708751648 Please review it
