### ISSUE TITLE
Add missing deque methods

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#2812]
Current basic methods are not implemented on `deque`:

- [x] #2835
- [x] #2837
- [x] #2838
- [x] #2839
- [x] #2834
- [x] #2836

**Comment by OhBonsai** [comment]
Hi, I would like to do some work on this. Could you @DimitrisJim get me up to speed quickly on this? :)

**Comment by DimitrisJim** [comment]
Of course @OhBonsai. You can start by taking a look at the other methods implemented for `deque`, these will give you an idea on how to manipulate the underlying `VecDeque` to get the behavior needed. You can drop in at [gitter](https://gitter.im/rustpython/Lobby) and ask about anything if you get stuck at some point.

**Comment by DimitrisJim** [comment]
Hey @OhBonsai , pick one of the issues linked and I can assign it to you and guide you through anything you need over there.

**Comment by whgusdn321** [comment]
@OhBonsai Hello I'm interested in this issue also. If you don't mind, I would like to contribute some of them. would it be possible? and if it's okay, what are you going to implement among these? I'll implement the ones you don't pick.
 ( collections.deque doesn't have __add__ method #2835
 collections.deque doesn't have a __bool__ method. #2837
 collections.deque doesn't have __iadd__ method. #2838
 collections.deque doesn't have __imul__ method. #2839
 collections.deque does not have __rmul__ method #2834
 collections.deque doesn't have __reversed__ method #2836)

**Comment by OhBonsai** [comment]
@whgusdn321  Wows, It's seem like i can ride your coattails 😄 .

I think i could choose add/bool.  It looks simpler~.

**Comment by youknowone** [comment]
general tip: `list` and `tuple` have similar implementations for similar magic methods.

**Comment by hk1997** [comment]
Hi, 
Is it still open?

**Comment by DimitrisJim** [comment]
Ah, I'm afraid not, the last part of this issue is being worked on by someone atm. 

I'll try and see if I can find any other easy issues soon though, so, be on the look-out for them.

**Comment by DimitrisJim** [comment]
@hk1997 see #3039 for a couple more good first issues you could try and take-up.
