### ISSUE TITLE
Deque instances shouldn't be hashable

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#2813]
Currently, `deque` instances are able to be hashed:

```
>>>>> from collections import deque
>>>>> hash(deque())
94434894504112
```

Expected behavior:

```
>>>>> hash(list())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'deque'
```

**Comment by jamestwebber** [comment]
Decided to try this because it seemed "simple"...

It seems like to implement `Unhashable` you must first implement `Hashable`? Seems a bit weird.

**Comment by youknowone** [comment]
yep, that's a trick for trait/macro generation xD
