### ISSUE TITLE
Incompatibility for builtin special attribute "__dict__" of functools.partial

### ISSUE THREAD

**Issue by Snowapril** [RustPython/RustPython#2825]
## Feature

In CPython, special attribute `__dict__` of `functools.partial` does not have anything, but RustPython's one have all it's variables.

#### CPython-Side work

```python
>>> from functools import partial
>>> def signature(part):
...     """ return the signature of a partial object """
...     return (part.func, part.args, part.keywords, part.__dict__)
... 
>>> f = partial(signature)
>>> f.__dict__
{}
```

#### RustPython-Side work

```python
>>>>> from functools import partial
>>>>> def signature(part):
.....     """ return the signature of a partial object """
.....     return (part.func, part.args, part.keywords, part.__dict__)
..... 
>>>>> f = partial(signature)
>>>>> f.__dict__
{'func': <function signature at 0x556c31c80530>, 'args': (), 'keywords': {}}
```

After call `__setstate__` method, CPython's `__dict__` have only `{attr: []}` which is fourth argument(namespace)  of passed tuple but RustPython's one have all its variables as dictionary in addition to `{attr: []}`.

#### CPython-Side work

```python
>>> f.__setstate__((signature, (1,), dict(a=10), dict(attr=[])))
>>> f.__dict__
{'attr': []}
```

#### RustPython-Side work

```python
>>>>> f.__setstate__((signature, (1,), dict(a=10), dict(attr=[])))
>>>>> f.__dict__
{'attr': [], 'func': <function signature at 0x556c31c80530>, 'args': (1,), 'keywords': {'a': 10}}
```

## Python Documentation

https://docs.python.org/3/library/stdtypes.html#object.__dict__

This incompatibility leads to `test_setstate` failure in [test_functools.py](https://github.com/RustPython/RustPython/blob/master/Lib/test/test_functools.py#L278)

**Comment by youknowone** [comment]
thanks for detailed analysis

**Comment by Snowapril** [comment]
I'm currently working on this issue. Could you assign this issue to me? Thanks!

**Comment by youknowone** [comment]
I have no idea when, but this is fixed!
