### ISSUE TITLE
[RFC] Switch default branch from master to main

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#2829]
## Summary

Let's set `main` as the default branch

## Detailed Explanation

Long in short, this is how others do. And we don't have any reason not do to that.

- Guideline: https://github.com/github/renaming
- CPython: https://github.com/python/cpython/tree/main

**Comment by DimitrisJim** [comment]
Since `master` is insulting to some I see no reason why not. Just a few commands on our part is a *miniscule* price to pay for being more welcoming.

**Comment by sobolevn** [comment]
Moreover, `main` is the new default for new GitHub projects. https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

**Comment by coolreader18** [comment]
I'm also in favor of this change. It's not too hard to switch, should I just do it?

**Comment by coolreader18** [comment]
Ok, renamed master to main! Run `git branch -m master main && git fetch origin && git branch -u origin/main main` to update in your local repo!
