### ISSUE TITLE
dict.{__or__,__ror__,__ior__} with other types should return NotImplemented

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#2832]
## Feature
The union operator of dict should return `NotImplemented` with other types but for now raising exceptions.

- [ ] __or__
- [ ] __ror__
- [ ] __ior__

Test `test_dunion_other_types` in `extra_tests/snippets/dict_union.py` is also wrong.

**Comment by voidsatisfaction** [comment]
May I handle this issue?

**Comment by youknowone** [comment]
for reference: other types, especially numeric types returns `NotImplemented` a lot, e.g. `int`, `float` and `complex`.
