### ISSUE TITLE
`collections.deque` does not have `__rmul__` method

### ISSUE THREAD

**Issue by sobolevn** [RustPython/RustPython#2834]
## Feature

CPython:

```python
>>> from collections import deque
>>> deque((1, 2)).__rmul__(2)
deque([1, 2, 1, 2])
```

RustPython:

```python
>>>>> from collections import deque
>>>>> deque((1, 2)).__rmul__(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'deque' object has no attribute '__rmul__'
```

**Comment by DimitrisJim** [comment]
huh, I missed this in #2812. I'll update the issue there and close this up to keep them all in one spot. Take a look over at it to see I haven't missed anything else (pretty sure I got the rest of them).

**Comment by sobolevn** [comment]
I am working on this issue right now 🙂 
I will submit a PR later tomorrow.
