### ISSUE TITLE
`collections.deque` doesn't have a `__bool__` method.

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#2837]
## Feature

CPython:

```python
>>> from collections import deque
>>> deque().__bool__()
False
```

RustPython:

```python
>>>>> from collections import deque
>>>>> deque().__bool__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'deque' object has no attribute '__bool__'
```

`bool` for `deque`s currently falls back to using `__len__` when it should supply an implementation of `__bool__`.

**Comment by OhBonsai** [comment]
Hi, @DimitrisJim  assign me plz~~

**Comment by DimitrisJim** [comment]
bump, any update on this @OhBonsai ?

**Comment by OhBonsai** [comment]
> bump, any update on this @OhBonsai ?

Hi, @DimitrisJim   I will update in this weekend~
