### ISSUE TITLE
`collections.deque` doesn't have `__imul__` method.

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#2839]
## Feature

CPython:

```python
>>> from collections import deque
>>> d = deque()
>>> d.__imul__(3)
deque([1, 1, 1, 1, 1])
```

RustPython:

```python
>>>>> from collections import deque
>>>>> d = deque()
>>>>> d.__imul__(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'deque' object has no attribute '__imul__'
```

**Comment by architjen** [comment]
Hi @DimitrisJim, I'm new to open-source, can I take up this issue?

**Comment by DimitrisJim** [comment]
@architjen sure! Go for it.

**Comment by ConnorTroy** [comment]
@architjen Are you still working this? If not, @DimitrisJim can I take over?

**Comment by DimitrisJim** [comment]
I last talked with Archit three days or so ago. Maybe give them a day to respond before submitting something just in case.

**Comment by youknowone** [comment]
Ah, got it. I didn't know that.

For everyone: we don't have strict rule for assignment of issues. we do that just for easier communication, not to make duplicated effort for same issues. Please note that assignment doesn't mean the responsibility or permission of the issue is owned by the assignees.

**Comment by DimitrisJim** [comment]
No prob, I'll try and get a hold of them today on gitter today and ask if they can follow through with it.

**Comment by architjen** [comment]
Hii @ConnorTroy, sure you can take over the issue!
