### ISSUE TITLE
please write mrubyc in Rust

### ISSUE THREAD

**Issue by letarg0** [RustPython/RustPython#284]
nobody using python

**Comment by windelbouwman** [comment]
We'll deal with Perl first :)

**Comment by letarg0** [comment]
> We'll deal with Perl first :)
5 or 6 version?

**Comment by cthulahoops** [comment]
Both!

**Comment by letarg0** [comment]
i found small runtime for mruby
https://github.com/mrubyc/mrubyc but not perfect, look nice.

**Comment by windelbouwman** [comment]
Due to lack of time, I'm closing down this issue. Please check back later, if still not implemented.
