### ISSUE TITLE
`id(a) != id(a * 1)` for `tuple`, str and bytes 

### ISSUE THREAD

**Issue by sobolevn** [RustPython/RustPython#2840]
## Feature

CPython:

```python
>>> a = (1, 2)
>>> id(a), id(a * 1)
(4379030656, 4379030656)
```

RustPython:

```
>>>>> a = (1, 2)
>>>>> id(a), id(a * 1)
(140352989490368, 140352989503168)
```

This is also covered by `seq_tests.test_repeat` which is now marked as `unittest.expectedFailure`.

**Comment by sobolevn** [comment]
The fix is on its way 🚂

**Comment by DimitrisJim** [comment]
Note: similar issue is present for the other immutables that can be multiplied, (`str` and `bytes`). Pick those up too if you're up for it.

**Comment by sobolevn** [comment]
Yeap, will add `str` and `bytes` support in a moment 💯

**Comment by sobolevn** [comment]
Related bug report about missing `str` and `bytes` tests: https://bugs.python.org/issue44891

**Comment by DimitrisJim** [comment]
I'd also submit a PR @sobolevn. The [devguide](https://devguide.python.org/coverage/#increase-test-coverage) states this at some point. You might want to check that it indeed isn't covered by running gcov but that sounds like overkill in this case.
