### ISSUE TITLE
Added undefined `__new__` method to non-built-in types 

### ISSUE THREAD

**Issue by moreal** [RustPython/RustPython#2869]
## Feature

Currently, non-built-in types (e.g. user defined class) has its `__new__` method. So they are different with `object.__new__` and it cause error in `inspect._signature_from_callable()`.

### RustPython-side

```
>>>>> type.__new__
<bound method __new__ of <class 'type'>>
>>>>> object.__new__
<bound method __new__ of <class 'object'>>
>>>>> class A:
.....   ...
..... 
>>>>> A.__new__
<bound method __new__ of <class '__main__.A'>>
>>>>> A.__new__ == object.__new__
False
```

### CPython 3.8-side
```python
>>> type.__new__
<built-in method __new__ of type object at 0x7fc673a1c480>
>>> object.__new__
<built-in method __new__ of type object at 0x7fc673a1c620>
>>> class A:
...   ...
... 
>>> A.__new__
<built-in method __new__ of type object at 0x7fc673a1c620>
>>> A.__new__ == object.__new__
True
```

## Python Documentation

- https://github.com/python/cpython/blob/fa919fdf2583bdfead1df00e842f24f30b2a34bf/Objects/typeobject.c#L6065-L6083
- https://docs.python.org/3/reference/datamodel.html?highlight=__new__#object.__new__

**Comment by jamestwebber** [comment]
I believe solving this would close #2732

**Comment by moreal** [comment]
> I believe solving this would close #2732

I agree with it.
