### ISSUE TITLE
`dict_keys`, `dict_values`, and `dict_items` are missing several methods

### ISSUE THREAD

**Issue by sobolevn** [RustPython/RustPython#2898]
## Feature

CPython:

```python
>>> dir(dict().keys())
['__and__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'isdisjoint']
```

RustPython:

```python
>>>>> dir(dict().keys())
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__str__', '__subclasshook__']
```

Diff: 
- `'__contains__'`
-  `'__and__'`
- `'__rxor__'`
- `'isdisjoint'`
- `'__or__'`
- `'__rand__'` 
- `'__ror__'` 
- `'__xor__'`
- `'__rsub__'`
- `'__sub__'`
- `'__sizeof__'`

The same is for `dict_values` and `dict_items`

**Comment by DimitrisJim** [comment]
Yup, I don't think a macro should be used to generate the types as is currently done. For their respective iterators, the macro seems like a good idea, for the types, not that much.

**Comment by DimitrisJim** [comment]
Additionally, though `__contains__` currently works (falling back to iterating), it can be `O(1)` for `keys` and `items` views by keying the dict ref they hold.

**Comment by youknowone** [comment]
is this done? can we list up what's done and left?

**Comment by rvsampson94** [comment]
I think __sizeof__ is the last one that needs to be merged. After that it should be done.

**Comment by nadavkluger** [comment]
Hey I want to start working on it but it seems like part of it is already implemented:
![image](https://user-images.githubusercontent.com/27895842/147653023-59f46d30-41ae-4b28-a82a-267c4fdb84a8.png)

![image](https://user-images.githubusercontent.com/27895842/147653062-31286407-c2f0-4421-a2db-3e3e2fe120e0.png)

**Comment by nadavkluger** [comment]
I want to work on it

**Comment by John15321** [comment]
Hey if its done you guys should close the issue :)

**Comment by youknowone** [comment]
@John15321 thank you!
