### ISSUE TITLE
Bump `typing` module to 3.8

### ISSUE THREAD

**Issue by moreal** [RustPython/RustPython#2918]
## Feature

[Currently](https://github.com/RustPython/RustPython/blob/0834ae3039fac0d39b303201a4096fec172ed30d/README.md), RustPython targets to support Python >= 3.8. But [the `typing` module seems to have stayed in 3.6](https://github.com/RustPython/RustPython/commit/e1bc0b9a8171745f81ab5d1ab929e944ed6671ff#diff-ddb987fca5f5df0c9a2f5521ed687919d70bb3d64eaeb8021f98833a2a716887). It should be bumped to resolve another issues to use `typing` module.

To resolve this issue, #2917 should be resolved first.

## Python Documentation

- https://github.com/python/cpython/blob/v3.8.0/Lib/typing.py

**Comment by coolreader18** [comment]
#2633
