### ISSUE TITLE
Range computation uses vectors and not iterables

### ISSUE THREAD

**Issue by mcon** [RustPython/RustPython#294]
In `builtin_range` (`vm/src/builtins.rs`), the elements of a range are in a vector, thereby taking up O(n) size when iterating over n elements, when this could be O(1) using an iterator.

**Comment by HomerMcMillan** [comment]
I'll work on this if nobody else has started.

**Comment by windelbouwman** [comment]
@mcon I believe this is implemented correctly now. Could you re-check and close this issue if you can confirm this issue is no longer present?

**Comment by windelbouwman** [comment]
Closing this issue, since I believe it is implemented.
