### ISSUE TITLE
 no matching package named `rustpython-vm` found

### ISSUE THREAD

**Issue by vprelovac** [RustPython/RustPython#2947]
macOS Big Sur, clean install of Rust.

vlad@Vladimirs-MacBook-Air ~ % cargo install rustpython

  ```
Updating crates.io index
  Installing rustpython v0.1.2
error: failed to compile `rustpython v0.1.2`, intermediate artifacts can be found at `/var/folders/yc/2061m39j2bxg37kz2wxb5sl00000gn/T/cargo-installVJRhrB`

Caused by:
  no matching package named `rustpython-vm` found
  location searched: registry `https://github.com/rust-lang/crates.io-index`
  required by package `rustpython v0.1.2`
```

vlad@Vladimirs-MacBook-Air ~ % cd /var/folders/yc/2061m39j2bxg37kz2wxb5sl00000gn/T/cargo-installVJRhrB

vlad@Vladimirs-MacBook-Air cargo-installVJRhrB % ls -la
total 8
drwxr-xr-x    3 vlad  staff    96 Aug 23 12:57 .
drwx------@ 152 vlad  staff  4864 Aug 23 12:57 ..
-rw-r--r--    1 vlad  staff  1044 Aug 23 12:57 .rustc_info.json

vlad@Vladimirs-MacBook-Air cargo-installVJRhrB % more .rustc_info.json 

`{"rustc_fingerprint":7515179083630404878,"outputs":{"931469667778813386":{"success":true,"status":"","code":0,"stdout":"___\nlib___.rlib\nlib___.dylib\nlib___.dylib\nlib___.a\nlib___.dylib\n/Users/vlad/.rustup/toolchains/stable-x86_64-apple-darwin\ndebug_assertions\nproc_macro\ntarget_arch=\"x86_64\"\ntarget_endian=\"little\"\ntarget_env=\"\"\ntarget_family=\"unix\"\ntarget_feature=\"fxsr\"\ntarget_feature=\"sse\"\ntarget_feature=\"sse2\"\ntarget_feature=\"sse3\"\ntarget_feature=\"ssse3\"\ntarget_os=\"macos\"\ntarget_pointer_width=\"64\"\ntarget_vendor=\"apple\"\nunix\n","stderr":""},"17598535894874457435":{"success":true,"status":"","code":0,"stdout":"rustc 1.54.0 (a178d0322 2021-07-26)\nbinary: rustc\ncommit-hash: a178d0322ce20e33eac124758e837cbd80a6f633\ncommit-date: 2021-07-26\nhost: x86_64-apple-darwin\nrelease: 1.54.0\nLLVM version: 12.0.1\n","stderr":""},"2797684049618456168":{"success":true,"status":"","code":0,"stdout":"___\nlib___.rlib\nlib___.dylib\nlib___.dylib\nlib___.a\nlib___.dylib\n","stderr":""}},"successes":{}}`

**Comment by fanninpm** [comment]
Try installing directly from the `main` branch.

**Comment by StackerDesu** [comment]
Clone this project and compile it with cargo.

**Comment by DimitrisJim** [comment]
Yeah, this is documented in the README use:

```
cargo install --git https://github.com/RustPython/RustPython
```

Same as #2996
