### ISSUE TITLE
Panic on out of bounds negative index

### ISSUE THREAD

**Issue by HomerMcMillan** [RustPython/RustPython#295]
Example:
```
Welcome to the magnificent Rust Python 0.0.1 interpreter
>>>>> a = [1,2,3]
>>>>> a[-4]
thread 'main' panicked at 'attempt to subtract with overflow', vm/src/obj/objsequence.rs:16:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The culprit is this function in the `PySliceableSequence` trait: 
```rust
fn get_pos(&self, p: i32) -> usize {
        if p < 0 {
            self.len() - ((-p) as usize)
        } else if p as usize > self.len() {
            // This is for the slicing case where the end element is greater than the length of the
            // sequence
            self.len()
        } else {
            p as usize
        }
}
```
`self.len() - ((-p) as usize)` panics when `-p > self.len()` This is similar to #276 but doesn't arise from converting a python int to usize. I think the best way to fix this is to change `get_pos` to return `Result<usize, PyObjectRef>` with an `IndexError` in the `Err` case.

**Comment by coolreader18** [comment]
Feel free to make a PR for this!

**Comment by makarchuk** [comment]
Seems like it should be closed now. @windelbouwman ?
