### ISSUE TITLE
storing to `__debug__` should be rejected by compiler.

### ISSUE THREAD

**Issue by HyeockJinKim** [RustPython/RustPython#2979]
## Feature

In Cpython, raise syntax error when saving a value to `__debug__`.
```python
>>> __debug__ = 3
  File "<stdin>", line 1
SyntaxError: cannot assign to __debug__
```

In RustPython, value can be stored to `__debug__`.
```python
>>>>> __debug__ = 3
>>>>> 
```

**Comment by DimitrisJim** [comment]
The additional cases not covered all appear to be related to function definitions/calls:

```python
>>> def foo(__debug__): pass
...
  File "<stdin>", line 1
SyntaxError: cannot assign to __debug__
>>> def foo(x): pass
...
>>> foo(__debug__=30)
  File "<stdin>", line 1
SyntaxError: cannot assign to __debug__
>>> def foo(__debug__=3): pass
...
  File "<stdin>", line 1
SyntaxError: cannot assign to __debug__
```

The other un-assignables (`True, False`) all handle this case correctly.

**Comment by muscar** [comment]
Hi there 👋🏻 I think https://github.com/RustPython/RustPython/pull/3203 should cover all the cases. It looks like the GH workflow needs approval before it can run.

**Comment by DimitrisJim** [comment]
Additional cases (some present in `test_syntax.py` and `test_compile.py`):

 - Calling a function accepting arbitrary kwargs: `def foo(**kwargs): pass; foo(__debug__='ok')`
 - Setting `__debug__` on `builtins` (tested in `test_compile.py`):

    ```python
    import builtins
    setattr(builtins, "__debug__", "ok")
    __debug__ == "ok"  # True
   ```

 - Wrong error message (implementation probably checks if args match before checking if arg name is ok):

    ```python
    def f(a, *args, **kwargs): pass
    f(__debug__ = 30)  # missing 1 pos arg, should be syntax error.
   ```
 - Attribute assignment. Currently not handled.
    
    ```python
    class Foo: pass
    f = Foo()
    f.__debug__ = 30
    ```
    A second case of this for an object that hasn't been defined yet should also be handled. CPython raises an error for the
    `__debug__` assignment while RustPython (currently) complains about an undefined name:

    ```python
     # CPython
     obj.__debug__ = 30   # SyntaxError
    # RustPython
    obj.__debug__ = 30   # NameError

**Comment by youknowone** [comment]
The given cases on this issue and comments are fully fixed

**Comment by DimitrisJim** [comment]
`setattr(...)` was the only unhandled case but I fixed that up real quick so we can keep this closed.
