### ISSUE TITLE
Use holyjit to generate faster code

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#300]
We could potentially use holyjit to speedup python bytecode: https://github.com/nbp/holyjit

Figure out how to do this. Maybe wait some time for the project to complete / mature.

**Comment by Lynskylate** [comment]
Holyjit seems to be no longer maintained, maybe we can use [cranelift](https://github.com/bytecodealliance/wasmtime/tree/main/cranelift) to generate faster code.
And we need a rfc to design asp for jit in RustPython, [PEP 523](https://www.python.org/dev/peps/pep-0523/#id37) and [pyston](https://github.com/pyston/pyston) maybe help for the target.

**Comment by coolreader18** [comment]
A JIT is currently WIP, see the `jit/` directory on master.
