### ISSUE TITLE
What's the purpose of GIL in RustPython?

### ISSUE THREAD

**Issue by theLastOfCats** [RustPython/RustPython#302]
RustPython declare the goals:
* Full Python-3 environment entirely in Rust (not CPython bindings)
* A clean implementation without compatibility hacks

And python_compiler using GIL acquire mechanism
https://github.com/RustPython/RustPython/blob/master/py_code_object/python_compiler/src/python_compiler.rs#L10

My questions:

0. Why RustPython implement this feature?
1. Is the RustPython is the CPython, but implemented on Rust? 
2. Or is it needed for compatibility reason? 
2.1 If so, doesn't it contradict goal 2?
3. If is compatibility for C extensions, maybe it will be better to make layer for this kind of use cases?

**Comment by windelbouwman** [comment]
At the moment this is an unknown for me.

This post might be informative: https://morepypy.blogspot.com/2018/09/inside-cpyext-why-emulating-cpython-c.html

**Comment by Mec-iS** [comment]
@theLastOfCats 
> 1. Why RustPython implement this feature?
I suppose the first step is to have a CPython "clone" that does implement the GIL.

**Comment by RonnyPfannschmidt** [comment]
a gil is pretty much the most simple way to have "safe" shared mutable object concurrency

its actually incredibly tricky to have certain invariant hold true without a gil

(like for example parallel loops doing append to lists that have to change capacity at time)

**Comment by dralley** [comment]
Maybe I'm missing something, but I can no longer find references to a GIL, interpreter lock, etc. in the RustPython source code.  It's only used in benchmarks.

**Comment by coolreader18** [comment]
Yes, the GIL was only referenced when calling to the CPython API for the benchmarks and previously to convert between CPython/RustPython bytecode (but that project is no longer active). In addition, the question of a GIL is a while off since we don't even have multithreading yet. This issue could probably be closed

**Comment by coolreader18** [comment]
Discussion for this topic can be found in #362.
