### ISSUE TITLE
Please add new labels

### ISSUE THREAD

**Issue by veera83372** [RustPython/RustPython#303]
Please add `has PR` label and automate the flow of adding label whenever there is PR for respective issue.
It's been hard for checking which one has PR and which one is not.

I can take up this automation task and other maintaining stuff related to PR and issues

**Comment by shinglyu** [comment]
`has PR` is there, feel free to automate it. I'm here to help if you need to modify admin-only settings.

**Comment by windelbouwman** [comment]
I will close this issue now.
