### ISSUE TITLE
Need to implement int.* 

### ISSUE THREAD

**Issue by veera83372** [RustPython/RustPython#304]
Following methods/attributes need to be implemented on type `int`. Please feel to pick unchecked method/attributes
`int` is  implemented in `vm/src/obj/objint.rs`

- [x] int . \_\_bool__
- [x] int . \_\_ceil__
- [x] int . \_\_dir__
- [x] int . \_\_floor__
- [x] int . \_\_index__
- [ ] int . \_\_getnewargs__
- [ ] int . \_\_init_subclass__
- [x] int . \_\_int__
- [x] int . \_\_invert__
- [x] int . \_\_radd__
- [x] int . \_\_rand__
- [x] int . \_\_rdivmod__
- [x] int . \_\_reduce__
- [x] int . \_\_reduce_ex__
- [x] int . \_\_rfloordiv__
- [x] int . \_\_rlshift__
- [x] int . \_\_rmod__
- [x] int . \_\_rmul__
- [x] int . \_\_ror__
- [x] int . \_\_round__
- [x] int . \_\_rpow__
- [x] int . \_\_rrshift__
- [x] int . \_\_rsub__
- [x] int . \_\_rtruediv__
- [x] int . \_\_rxor__
- [x] int . \_\_setattr__
- [ ] int . \_\_sizeof__
- [x] int . \_\_subclasshook__
- [x] int . \_\_trunc__
- [x] int . denominator
- [x] int . from_bytes
- [x] int . imag
- [x] int . numerator
- [x] int . real
- [x] int . to_bytes

**Comment by Tom1380** [comment]
Can someone point me towards where I can find the specifications for these methods?

**Comment by lausek** [comment]
Sorry, `__int__` was merged in #326 aswell.

**Comment by Mec-iS** [comment]
@Tom1380 The reference is CPython implementation -> https://github.com/python/cpython

**Comment by dralley** [comment]
The current list is just 

```
int.__getnewargs__
int.__init_subclass__
int.__sizeof__
```

**Comment by ashermancinelli** [comment]
I'd love to try at `int.__sizeof__`. Would anyone be willing to give some direction?

**Comment by coolreader18** [comment]
See, you *think* it'll be that simple :smile:. We've had two previous attempts at implementing int.__sizeof__, #1172 and #1426, the latter of which is currently open. There's also a discussion topic on __sizeof__ at #1250. If you want to give it a shot based on my comment (https://github.com/RustPython/RustPython/pull/1426#discussion_r329327681), feel free to, as #1426 has stagnated a bit.

**Comment by youknowone** [comment]
`__getnewargs__` is a pickle feature and `__init_subclass__` is metaclass support. (maybe we'd better to have metaclass issue for this)
So it seems `int` is now practically done.
