### ISSUE TITLE
Automatic push-based CI not triggering due to branch name change

### ISSUE THREAD

**Issue by fanninpm** [RustPython/RustPython#3067]
One of the unintended side effects of #2829's implementation is the breakage of this repo's infrastructure in various parts. In particular, CI is no longer triggered upon merging a PR because GitHub doesn't know to look for pushes to the `main` branch (rather than the old `master` branch). Here is the relevant line that causes this behavior:

https://github.com/RustPython/RustPython/blob/c064118e6b0615de6f6ee6ff5422faf14b03b54f/.github/workflows/ci.yaml#L3

Separately, there are a few unimportant instances in various places that make reference to a `master` branch that no longer exists. As of when I'm writing this, they can be found with [a cursory (although broad) search on GitHub for the word "master"](https://github.com/RustPython/RustPython/search?q=master).

**Comment by DimitrisJim** [comment]
It took almost 200 PRs for this to be noticed :smile:. Do you want to fix these up?
