### ISSUE TITLE
Improve speed of travis

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#308]
To reduce the amount of travis time consumed, maybe some build steps can be skipped. Maybe we can do less extensive checking on pull requests, perhaps not all rust versions for example. This saves time and server energy!

**Comment by coolreader18** [comment]
Testing on nightly might be unnecessary, as there aren't often backwards-incompatible changes that won't be fixed by the next day.

**Comment by shinglyu** [comment]
Do we have any hard dependency on nightly or beta? If not we can disable them in PR and branch push. If we want to be safe we can still test them when we merge to master.

**Comment by coolreader18** [comment]
Maybe some stuff with nightly for WASM, but I don't think beta would be necessary. [MANY more people use nightly than beta, anyway](https://blog.rust-lang.org/2018/11/27/Rust-survey-2018.html#rust-toolchain).

**Comment by shinglyu** [comment]
Yeah, I would say nightly + stable is enough.

**Comment by windelbouwman** [comment]
Closing this issue. I think our setup is usable now.
