### ISSUE TITLE
Embedding without standard library 

### ISSUE THREAD

**Issue by Suncradle** [RustPython/RustPython#3090]
Apologies if this has been asked before. Is it possible (or planned to be) to embed rustpython in an application with only a subset of the standard library? The size is a problem for small, portable applications, and most of it is unnecessary or nonfunctional (for example, in sandboxed wasm)

**Comment by fanninpm** [comment]
See also #3102

**Comment by youknowone** [comment]
excluding stdlib slightly help it. but not that much. we need a lot more work to make embedding-appropriate sized binary
