### ISSUE TITLE
[RFC] split rustpython_stdlib from rustpython_vm

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3102]
## Summary

Split rustpython_stdlib from rustpython_vm which contains non-necessary rust modules for vm itself.

## Detailed Explanation

Advantages:
- We will have pressure to define public APIs by dogfooding, because rustpython_stdlib cannot access rustpython_vm private.
- Compiling will be faster by deviding crates. At least fot rustpython_stdlib.
- `stdlib` can be a feature. Without it, the binary size will be smaller than now.

**Comment by DimitrisJim** [comment]
Question on this since #3132 got me thinking. 

Doesn't `vm` require minimal support from the `stdlib`? `sys` seems like it defines things that are also used in `vm/`, `importlib` should be around for importing things and `io` and `encodings` also are required if I recall correctly.

I can see how a subset of the stdlib could be separated but not really seeing how _all_ could be yanked and placed in a new crate with could be a `nostdlib` feature, a `limited-stdlib` maybe. This is just a quick though on it, though, what's your idea on this?

**Comment by youknowone** [comment]
I think modules defined in `sys.builtin_module_names` must be included in vm. Other modules will be splited.

I also think the name `vm::stdlib` doesn't fit anymore.
Maybe `vm::module` include builtin modules (since it is defined in `sys.builtin_module_names`),
and they will be re-exported through rustpython_stdlib again

**Comment by coolreader18** [comment]
Something I've been thinking about - oh which it seems also @DimitrisJim - some things *should* be core to the interpreter, right? Like `_signal`, or `_weakref`, or `_codecs` - imo, anything that's required to start up `rustpython` (and to be honest, I thought it was a given that `sys`/`builtins` would stay in the vm). CPython makes this distinction via "built-in" modules vs dlls. `_io` is `<module 'io' (built-in)>`, but `zlib` is `<module 'zlib' from '/usr/lib/python3.9/lib-dynload/zlib.cpython-39-x86_64-linux-gnu.so'>`. Obviously we don't have extension modules, but I think it's more productive/useful to put those ancillary modules in a separate crate while keeping the actually core ones in `rustpython-vm`.

**Comment by coolreader18** [comment]
Oh, right - like `sys.builtin_module_names`. These all seem preeetty core to the interpreter, except for things like functools/itertools but those are still very heavily used in all kinds of python code, they aren't like `zlib` which is domain-specific.
```
('_abc', '_ast', '_codecs', '_collections', '_functools', '_imp', '_io',
 '_locale', '_operator', '_peg_parser', '_signal', '_sre', '_stat', '_string',
 '_symtable', '_thread', '_tracemalloc', '_warnings', '_weakref', 'atexit',
 'builtins', 'errno', 'faulthandler', 'gc', 'itertools', 'marshal', 'posix',
 'pwd', 'sys', 'time', 'xxsubtype')
```

**Comment by coolreader18** [comment]
Maybe the distinction we could have, if we kept these in `rustpython-vm`, is `corelib` instead of `stdlib`? Obviously a different set of priorities than Rust's core vs std, but a similar concept imo.

**Comment by youknowone** [comment]
#3129 is now working version

**Comment by youknowone** [comment]
I have another public stdlib api suggestion in #3165

**Comment by youknowone** [comment]
This is finished by #3620
