### ISSUE TITLE
[RFC] iternext and its related functions' return types as `PyResult<PyIterReturn>`

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3124]
## Summary

iternext in CPython regards null pointer return as `StopIteration`. This is related to both easier handling during iterator processing and optimization.

## Detailed Explanation

`PyIterReturn` will be defined as:

```rust
enum PyIterReturn<T = PyObjectRef> {
    Object(T),
    StopIteration,
}

impl IntoPyResult for PyIterReturn {
   ...
}
impl IntoPyResult for PyResult<PyIterReturn> {
   ...
}
impl<T: PyValue> IntoPyResult for PyIterReturn<T> {
   ...
}
impl<T: PyValue> IntoPyResult for PyResult<PyIterReturn<T>> {
   ...
}
```
probably using `option_like!` macro.

The methods' signatures of `PyIter` will be:
```rust
    fn tp_iternext(zelf: &PyObjectRef, vm: &VirtualMachine) -> PyResult<PyIterReturn>;
    fn next(zelf: &PyRef<Self>, vm: &VirtualMachine) -> PyResult<PyIterReturn>;
    fn __next__(zelf: PyObjectRef, vm: &VirtualMachine) -> PyResult {
        Self::tp_iternext(&zelf, vm).into_pyresult(vm)
    }
```

## Unresolved Questions

How can we handle `StopAsyncIteration`?

**Comment by qingshi163** [comment]
I think PyObjectRef is not implement PyValue at moment, are you going to do it? @youknowone

**Comment by youknowone** [comment]
Not now. I even don't have a concrete idea about it yet. Feel free to take it.

I think PyObjectRef is not possible to implement PyValue. So that is my fault.
