### ISSUE TITLE
Build errors on Windows

### ISSUE THREAD

**Issue by maccam912** [RustPython/RustPython#313]
Is windows support a goal for RustPython? The current master doesn't build on Windows, failing with

```
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> vm\src\stdlib\io.rs:8:14
  |
8 | use std::os::unix::io::{FromRawFd, IntoRawFd};
  |              ^^^^ could not find `unix` in `os`
```

This happens in vm/src/stdlib/io.rs and vm/src/stdlib/os.rs because of that import, and the places in the code that this is being used fail as well with these imports not being available.

Is Windows support a goal of RustPython at this stage?

**Comment by coolreader18** [comment]
In-depth io support was implemented in #265, including the [dependency on unix](https://github.com/RustPython/RustPython/pull/265/files#diff-d02f403d064f9eeec4f7b38cc290bf20R37). This is fairly recent, and not well-timed with the influx of people from the github trending page :). In general, RustPython is cross-platform. @rmliddle, did you have any ideas on how to make `io` OS-agnostic?

**Comment by rmliddle** [comment]
#325 Is a start in the right direction. 

The platform dependent builds is fairly straightforward using [cfg](https://doc.rust-lang.org/rust-by-example/attribute/cfg.html).

The biggest issue on the io front is coercion of the windows file handles into the python `fileno`  attribute, however this should not (as far as I know) impact on the ability to build post merge.

**Comment by maccam912** [comment]
The old errors are fixed now, with a new one popping up, but I'm not sure if it's specific to Windows at this point:
```
error[E0433]: failed to resolve: could not find `BaseDirectories` in `xdg`
   --> src\main.rs:158:25
    |
158 |     let xdg_dirs = xdg::BaseDirectories::with_prefix("rustpython").unwrap();
    |                         ^^^^^^^^^^^^^^^ could not find `BaseDirectories` in `xdg`
```
Anyway thanks for the fix on the Unix specific stuff! You work fast.

**Comment by windelbouwman** [comment]
Windows must be supported. Unfortunately we have no appveyor CI system yet to check windows builds.
