### ISSUE TITLE
Is it possible to compile Python code to executables?

### ISSUE THREAD

**Issue by joeky888** [RustPython/RustPython#315]
Is it possible to compile Python code to executables like `.exe` files?

More specifically, can I compile [youtube-dl](https://github.com/rg3/youtube-dl) to single executable file?

The dependencies of youtube-dl are only Python3 and Python3-setuptools.

**Comment by coolreader18** [comment]
[PyInstaller](https://www.pyinstaller.org/) looks like it might work; however, this repository probably isn't the best place to ask the question, as this version of python can't even run `youtube-dl` yet.

**Comment by joeky888** [comment]
Yeah, but it seems to be very difficult (or maybe impossible) to build a single static executable on Linux using PyInstaller.

**Comment by volfco** [comment]
http://nuitka.net is what you are looking for, but this repo is a long away from being where it would need to be.

**Comment by joeky888** [comment]
nuitka does not compile Python code to static executables, also it takes 20 minutes to compile youtube-dl.

**Comment by windelbouwman** [comment]
At the moment this cannot be done with RustPython. First focus is being able to run youtube-dl at all :).

**Comment by windelbouwman** [comment]
@joeky888 I will close this issue, since it will not be possible in the near future.
