### ISSUE TITLE
PyIter::check or impl TryFromObject for PyIter compatibility

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3176]
## Feature

Our `PyIter` doesn't have `check` corresponds to CPython PyIter_Check

## Python Documentation

https://docs.python.org/3/c-api/iter.html#c.PyIter_Check

## Current status

`impl TryFromObject for PyIter` currently check if it is a PyIter object or not. But it is a little bit weird.
In CPython, it simply checks if it does have `tp_iternext`. 
In RustPython, it checks something more than `tp_iternext` including `__getitem__`. 

This difference could be made due to either we are not correctly implementing iterator or mapping protocol or current TryFromObject for PyIter is implemented wrong and covering something more than PyIter itself.

**Comment by DimitrisJim** [comment]
I think these correspond to two different functions, `PyObject_GetIter` and `PyIter_Check`. 

The first, `PyObject_GetIter` (i.e our impl TryFromObject for PyIter) checks for `iternext` and, on failure, checks if the object is sequence-like (i.e `PySequence_Check` which we currently don't have and fall back to checking `__getitem__`), it is roughly equivalent to `iter`.

`PyIter_Check` just queries the slot and returns.
