### ISSUE TITLE
Add proper support for kwargs

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#32]
Add support for keyword arguments.

**Comment by OddBloke** [comment]
#100 is the first part of this.

**Comment by OddBloke** [comment]
#100 has landed, which allows the specification of defaults when defining a function. Next step is to implement the syntax for keyword argument function calls, and the generation and consumption of the `CALL_FUNCTION_KW` opcode.

(After that, we will need to support keyword-only arguments (which I _think_ should just require syntax parsing and `MAKE_FUNCTION` compilation changes) and then `*args` and `**kwargs` function (I'm not entirely sure what will be involved here, I think it will include `CALL_FUNCTION_EX`).)

**Comment by windelbouwman** [comment]
@OddBloke I did some additional work on this. Do you think this issue can now be closed? What is still left to be done?

**Comment by windelbouwman** [comment]
I think most functionality regarding this issue is implemented. Closing the issue.
