### ISSUE TITLE
Fix collection(s) repr to correctly handle subclasses

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#3217]
In CPython:

```python
>>> from collections import deque
>>> class MyDeque(deque): pass
>>> MyDeque()
'MyDeque([])'
```

While in RustPython:

```python
>>>>> from collections import deque
>>>>> class MyDeque(deque): pass
>>>>> MyDeque()
deque([])
```

This needs to be applied for `set`, `frozenset` and `bytearray` too.

Prior similar work: #3137

**Comment by Snowapril** [comment]
currently, rustpython's `repr` is hardcoded with its name. maybe fix it with `slots.name` can be work.

**Comment by muscar** [comment]
I think this addresses the issue: https://github.com/RustPython/RustPython/pull/3219/files.

**Comment by DimitrisJim** [comment]
Please request to work on issues and then someone can assign you. #3218 and #3219 are in conflict. @muscar if possible, alter your PR to only fix the classes other than deque. This way both PRs can be merged!

Please do request things though, it makes it easier for everyone involved :smile:

**Comment by youknowone** [comment]
well, claims will be respected but generally it is not necessary. (at least, we were not using that workflow before.)

If there is no claim, first PR will be preferred to be merged without special reasons.

**Comment by DimitrisJim** [comment]
> it is not necessary

Oh sure, I'm not saying otherwise. Requesting things just makes it easier and doesn't result in one of the PRs being closed (and possibly disheartening new contributors).

**Comment by muscar** [comment]
Fair enough :) Will as on any future ones.
