### ISSUE TITLE
make PyType::name return type `&str`

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3232]
`PyType::name()` is a commonly used internal api.
Even though it can return `&str`, it returns a `String` for now.

**Comment by Snowapril** [comment]
As it is annotated with `pyproperty`, it cant return &str directly. Is it better to make new method, such as `_name`, which return &str and use it in the other codes?

**Comment by youknowone** [comment]
Yes, but I think `name()` for `&str` and `__name__` for `#[pyproperty]` is better.

**Comment by Snowapril** [comment]
Oh gosh. it is cool 😊 Could I work on this issue?

**Comment by DimitrisJim** [comment]
closed by #3261
