### ISSUE TITLE
Add `_statistics` module containing `_normal_dist_inv_cdf`

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#3251]
This should be _relatively_ easy. `_statistics` needs to be defined as a built-in module and `_normal_dist_inv_cdf` should be added as its sole function.

`_normal_dist_inv_cdf` is pretty straight-forward to implement with the [C version](https://github.com/python/cpython/blob/main/Modules/_statisticsmodule.c#L29) being a pretty direct translation from the [Python version](https://github.com/RustPython/RustPython/blob/main/Lib/statistics.py#L825).

**Comment by DimitrisJim** [comment]
Basic scaffold for the module (to be placed in `stdlib/src`):

```rust
pub(crate) use _statistics::make_module;

#[pymodule]
mod _statistics {

    #[pyfunction]
    fn _normal_dist_inv_cd(...) {}
}
```

it then needs to be exported in `stdlib/src/lib.rs` in a similar way to other modules.

**Comment by djrmarques** [comment]
SO this is no longer necessary since the merge made above right?
