### ISSUE TITLE
[WASM] Run RustPython WASM from another language?

### ISSUE THREAD

**Issue by kesmit13** [RustPython/RustPython#3294]
I would like to be able to load the RustPython WASM file into another language to execute Python code and retrieve Python results. I've looked at the WASM module produced by the following, and it appears the only export is the `main` function.
```
cargo build --release --target wasm32-wasi --features="freeze-stdlib"
```
Is `main` the only way to interact with the WASM module, or is there another way to use it that allows you to get results back from a function call? If using `main` is the only way, how do command-line arguments get passed in?

**Comment by youknowone** [comment]
Did you build `rustpython-wasm` crate?

`cd wasm/lib` and try to build there. I never tried wasm stuff myself but it must have more stuffs.

cc @coolreader18

**Comment by harisraharjo** [comment]
Hey @kesmit13, sorry for pinging you but it looks like you could make it work. Could you give me a pointer how you do it?

**Comment by kesmit13** [comment]
@harisraharjo I ended up going a different route. We are now using CPython compiled to WASM. See this project https://github.com/singlestore-labs/python-wasi.
