### ISSUE TITLE
Time module functions for Windows

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#3382]
See #3381 for the PR for Unices.

The `time` module for Windows is currently missing the following (among other things):

 - [ ] `get_clock_info`
 - [ ] `monotonic`/`monotonic_ns`
 - [ ] `perf_counter`/`perf_counter_ns`

(note that the last two set of functions are there but they aren't implemented correctly)

Not sure how easy/hard these might be, but, I'd be willing to help as best as I can through gitter (though I don't have a Windows machine).

**Comment by Snowapril** [comment]
I'm currently working on `monotonic`/`monotonic_ns` 😊

**Comment by DimitrisJim** [comment]
I want to say that `monotonic` and `perf_counter` share the same clock for windows too but I haven't checked the source. In unices, they both use `CLOCK_MONOTONIC`.
