### ISSUE TITLE
Allow writing union types as `X` | `Y`

### ISSUE THREAD

**Issue by moreal** [RustPython/RustPython#3419]
## Feature

Since CPython 3.10 version, it became to allow writing union types as `X | Y` (e.g. `int | str`).

## Python Documentation

- https://www.python.org/dev/peps/pep-0604/
- https://github.com/python/cpython/blob/a4774f42e35861c4bb16928cffb011c2d8a285ac/Objects/unionobject.c
- https://github.com/python/cpython/blob/2c045bd5673d56c3fdde7536da9df1c7d6f270f0/Objects/typeobject.c#L4359-L4361

**Comment by rtpg** [comment]
I'm kinda curious about this one, have you started looking at this one already? If not I'll take a shot

**Comment by moreal** [comment]
@rtpg No, I didn't. I opened this issue as a task card. You can take this one. 😉

**Comment by youknowone** [comment]
`__or__` and `__ror__` needs to be implemented in `type`. `type` is defined in `vm/src/builtins/pytype.rs` as `PyType` struct.
Other types `__or__` implementation will be useful. it can be found in any type implementing `|` operator, like `int`, `set` and other types. For those types, search for `fn or` in  `vm/src/builtins/<typename>.rs`.

By looking at links of the the issue, CPython seems to implement `Union` in C now. I think we can use python version at the first - if we are not going to Union type at the same time.
To bring `Union` from `typing.py`, `VirtualMachine::import` is useful. Search for `vm.import` for the use cases.
To get attribute `__getitem__` and invoke the method, search for `vm.get_attribute_opt` and `vm.invoke`.

**Comment by hrchu** [comment]
Take this one in PyCcon APAC 2021 sprint

**Comment by youknowone** [comment]
@moreal is this done?

**Comment by moreal** [comment]
> @moreal is this done?

@youknowone As I know, I believe it is done.
