### ISSUE TITLE
Failed to create virtualenv using RustPython

### ISSUE THREAD

**Issue by alexprengere** [RustPython/RustPython#3429]
When I want to test alternate Python interpreters, I usually create a virtualenv using:

```bash
virtualenv .env -p ./path/to/python
```

`virtualenv` is installed system-wide through pipx.

Then I run the test suite of some projects I maintain to report incompatibilities (like I did with #3411). When I use this pattern with RustPython, I get an immediate error:

```
TypeError: 'NoneType' object is not callable
```

**Comment by DimitrisJim** [comment]
Can you currently get it working with interpreters other than CPython and PyPy? 

The reason I'm asking is, after a quick glance, it seems like handling is done by certain Creator classes for which I only see implementations for CPython and PyPy (`virtualenv/create/via_global_ref/builtin`) and so I'd be interested to see how other implementations handle it.

**Comment by alexprengere** [comment]
CPython and PyPy/PyPy3 are the only interpreters I use every day. I have tried Pyston too, but I cannot remember if I had similar issues or not.

**Comment by youknowone** [comment]
`rustpython -m venv` now works
