### ISSUE TITLE
Create a simple test framework until we can run unittest

### ISSUE THREAD

**Issue by orf** [RustPython/RustPython#344]
It would be nice if we could create a simple test framework to organize our tests. The built in `unittest` module seems a bit out of reach right now and I don't think plain python files with `assert` will scale much more.

I am proposing building a really simple test framework that will run `test_*` methods inside various test files and report any errors found. We could expand on this as we add more features to the language, and hopefully it would bring a bit more structure to our Python tests.

**Comment by orf** [comment]
We already kind of have this, with `SampleTestCase`.

**Comment by cthulahoops** [comment]
There was a suggestion elsewhere that we target being able to import a common python library. I wonder how feasible ```pytest``` would be as a target. It would be useful to us, and will likely test our code pretty well.

**Comment by orf** [comment]
Pytest does some crazy magical things (bytecode rewriting for one), so
perhaps it might be a bit hard. IMO reaching compatibility with unittest
would be a good goal.

**Comment by cthulahoops** [comment]
But then we might have to interact with the unittest API! :)

**Comment by orf** [comment]
That indeed would be horrible, but less so than individual files!

Baby steps I think.

**Comment by RonnyPfannschmidt** [comment]
even as a pytest maintainer i would propose to go for having a working unittest first, as its used in the stdlib testsuite
