### ISSUE TITLE
Wamp install doesn't seem to work with windows

### ISSUE THREAD

**Issue by trsh** [RustPython/RustPython#3440]
```
PS C:\Users\trsh\.wasmer\bin> python C:\Projects\kaka.py
kaka
PS C:\Users\trsh\.wasmer\bin> .\wapm.exe run rustpython C:\\Projects\\kaka.py
[2021-11-15T19:20:49Z ERROR rustpython] can't open file 'C:\\Projects\\kaka.py': No such file or directory
PS C:\Users\trsh\.wasmer\bin> .\wapm.exe run rustpython C:\Projects\kaka.py
[2021-11-15T19:21:01Z ERROR rustpython] can't open file 'C:\Projects\kaka.py': No such file or directory
PS C:\Users\trsh\.wasmer\bin> .\wapm.exe run rustpython C:/Projects/kaka.py
[2021-11-15T19:21:15Z ERROR rustpython] can't open file 'C:/Projects/kaka.py': No such file or directory
```

Windows 10 x64

**Comment by coolreader18** [comment]
You need to give access to the directories, since WASI is sandboxed. Try `.\wapm.exe run --dir C:\ rustpython C:\Projects\kaka.py` or maybe `.\wapm.exe run --dir ..\..\..\.. rustpython ..\..\..\..\Projects\kaka.py` if that doesn't work.

**Comment by trsh** [comment]
> You need to give access to the directories, since WASI is sandboxed. Try `.\wapm.exe run --dir C:\ rustpython C:\Projects\kaka.py` or maybe `.\wapm.exe run --dir ..\..\..\.. rustpython ..\..\..\..\Projects\kaka.py` if that doesn't work.

Sorry but I don't get it. WAMP is a package manager and when `rustpython` is installed with it, it should run as standalone like the doc/README points out. So why `--dir C:\ rustpython` ? Anyway, check also this https://github.com/RustPython/RustPython/issues/3441

**Comment by coolreader18** [comment]
WebAssembly is sandboxed, and only has access to the directories you give it. If you want a full rustpython interpreter, build from source (it'll be up to date, too, the wapm version is pretty old).
