### ISSUE TITLE
Division by zero should raise ZeroDivisionError

### ISSUE THREAD

**Issue by silmeth** [RustPython/RustPython#345]
CPython, consistently with [documentation](https://docs.python.org/3/library/exceptions.html#ZeroDivisionError), raises `ZeroDivisionError` when trying to divide by 0:

```
>>> 5/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> -5/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> 5%0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

RustPython on the other hand happily returns `inf` on division and panics on modulo:

```
>>>>> 5/0
inf
>>>>> -5/0
-inf
>>>>> 5%0
thread 'main' panicked at 'explicit panic', /home/silmeth/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.2.1/src/algorithms.rs:497:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
zsh: exit 101   cargo run --release
```

I’ll try to make a PR fixing this and #331.

**Comment by Tom1380** [comment]
You should close this issue.

**Comment by silmeth** [comment]
There’s still one thing I’ve missed in my PR, `divmod(a, 0)` still panics for both floats and ints instead of throwing `ZeroDivisionError`, so I’m gonna make a new pull request for this and then close this issue.
