### ISSUE TITLE
Appending list too many times crashes RustPython 

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#3456]
Description:
In test.py, we define a empty list buf, and then we append a piece of code into the list with format i = buf. RustPython crashes.

test.py
```
def test_oneline_defs():
    buf = []
    for i in range(500):
        buf.append('def i{i}(): return {i}'.format(i=buf))
    buf.append('OK')

test_oneline_defs()
```

Reproduce:

run " rustpython test.py " and it reports:
```
memory allocation of 668423534 bytes failed
Aborted (core dumped)
```

Version: Rust Python 0.1.2 interpreter on Ubuntu 16.04

**Comment by andrew-ld** [comment]
this code does not work even with cpython, after a while it is killed by the oom killer

**Comment by youknowone** [comment]
I am going to close this by @andrew-ld
