### ISSUE TITLE
marshal module is imcomplete

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3458]
## Feature

[marshal](https://docs.python.org/3/library/marshal.html) dumps and loads are incomplete

## Python Documentation

https://docs.python.org/3/library/marshal.html

**Comment by dswij** [comment]
Would love to work on this, but I'm new to RustPython. Would appreciate some guidance if possible :slightly_smiling_face:

**Comment by jakearmendariz** [comment]
Hi, I was looking at this issue (new to this project) and I am struggling a bit. 

I assume the primary changes would be made to the [marshal.rs file](https://github.com/RustPython/RustPython/blob/main/vm/src/stdlib/marshal.rs). My first thought is that we would add more cases the loads and dumps match statements to handle `PyStr`, `PyInt`, `PyFloat` etc. However, the `loads` function [expects](https://github.com/RustPython/RustPython/blob/db3b3127df34ff5dd569301aa36ed71ae5624e4e/vm/src/stdlib/marshal.rs#L34) the returning of a `PyCode` object, thus at some point a `PyCode` object would have to be created (either in loads after reading the raw bytes, or in dumps by converting all `PyObjectRef` into `PyCode` first.

Am I understanding this correctly? If so, how can we convert and the `ConstantData`/`PyObjectRef`/bytes into a `PyCode` or `CodeObject`? 

FYI I am able to get any constant to a `PyConstant` without much trouble, it's the `CodeObject` creation that seems necessary and is confusing.

Thanks for any advice or tips you can give. I'm somewhat new to rust and interpreters and appreciate all the help I can get!

**Comment by youknowone** [comment]
Your approach is correct. The return type can be changed to `PyObjectRef` to include any type of python object. The most common way to convert `PyCode` or other types into `PyObjectRef` is using `into_pyobject`

**Comment by djrmarques** [comment]
Hello, is this issue closed already?

**Comment by youknowone** [comment]
Oh, yep. `test_marshal.py` is done. So this is also done. Thank you for remind it.

**Comment by youknowone** [comment]
#3681 
@djrmarques good news, marshal is not completed yet
