### ISSUE TITLE
Wasm builds broken, break starts at 9a86bbd718a099b01b07fbc42e0afc1253a5bff0

### ISSUE THREAD

**Issue by GTRI-nathan** [RustPython/RustPython#346]
Hi! I believe that 9a86bbd718a099b01b07fbc42e0afc1253a5bff0 broke wasm builds because it tries to import unix stuff, which isn't built on wasm. It's still broken on master because of functions in os that don't build when on wasm (rust_file and raw_file_number are the two that I see now).

**Comment by coolreader18** [comment]
Yes, this is covered by #311.
