### ISSUE TITLE
SaturatedSliceIter::next has overflow bug

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3468]
```sh
$ cargo run Lib/test/test_list.py -v -k test_extendedslicing

test_extendedslicing (__main__.ListTest) ... thread 'main' panicked at 'attempt to add with overflow', vm/src/builtins/slice.rs:377:9
```

Probably introduced in #3340

**Comment by Snowapril** [comment]
```bash
cargo run Lib/test/test_userlist.py -v -k test_extendedslicing 
```
above one also panicked by same reasom

**Comment by Snowapril** [comment]
```python
a = self.type2test(range(10))
del a[9::1<<333]
```
These line make panicked

**Comment by Snowapril** [comment]
`SaturatedSliceIter` used for both set_slice and del_slice, but del_slice seems required different condition for iterating.
`set_slice`(`subscript` in cpython) loop with condition on slice length, but `set_slice`(`ass_subscript` in cpython) check current `index` is over `stop` or not.
