### ISSUE TITLE
Error when building Rustpython using the freeze-stdlib feature

### ISSUE THREAD

**Issue by Keithcat1** [RustPython/RustPython#3501]
Rust 1.56, Windows 10 X64, Rustpython master

Steps to reproduce:
git clone https://github.com/RustPython/RustPython
cd RustPython
cargo build --features=freeze-stdlib
...
error: Error listing dir "C:\\py\\git\\rustpython\\vm\\pylib-crate\\Lib": The system cannot find the path specified. (os error 3)

**Comment by Snowapril** [comment]
Did you set the environment variable `RUSTPYTHONPATH`?

**Comment by Keithcat1** [comment]
Not originally. I did a clean build now and set RUSTPYTHONPATH to the directory containing my Python distributions standard library and there is no difference. However as far as I understand it RUSTPYTHONPATH doesn't matter when using the freeze-stdlib feature, because the freeze-stdlib feature embeds a vendored copy of the Python standard library into Rustpython and doesn't actually find it on your system.

**Comment by Keithcat1** [comment]
I figured it out. Before cloning Rustpython, try:
```
git config core.symlinks true
```
This fixed the problem for me on Windows 10 anyway.
