### ISSUE TITLE
Where is #[pymethod] defined?

### ISSUE THREAD

**Issue by phorward** [RustPython/RustPython#3509]
Hi folks,

can you please shortly direct me to the place where the pymethod-macro (or isn't this a macro?) is defined?
I wasn't able to do so, but it's used in several places, as `find . -type f -exec grep -nsH pymethod {} \;` reports.

Thanks a lot!

**Comment by youknowone** [comment]
`pymethod` itself is an annotation but not a macro. The upper `pyclass` is a proc-macro and it consumes inner `pymethod` annotations. To look in pyclass macro, See https://github.com/RustPython/RustPython/blob/main/derive/src/pyclass.rs
Telling us the purpose why you are looking for it would be helpful to find answers for your needs. If you are looking for the rules to use them, this document would be also helpful: https://github.com/RustPython/RustPython/wiki/Python-Attributes

**Comment by phorward** [comment]
@youknowone thank you very much for the hint and clarification. Well, I currently study parts of RustPython for better understanding in its details, therefore I don't have a direct usage for the annotation.

**Comment by lastmjs** [comment]
I was also confused by this, which led me here. Now I understand

**Comment by sniffer123** [comment]
@youknowone Hello,I had a similar problem.I defined a macro for a quick implementation of the method.like this:
`macro_rules! add_entity_impl {
    ($entity_name:literal) => {
        paste! {
            #[pymethod]
            fn [<add_ $entity_name>](zelf: PyObjectRef,vm: &VirtualMachine)-> PyResult<bool>{
                Ok(true)
            }
		}
	};
}`
and use it like this:
`
#[pyclass]
impl World {
	add_entity_impl!("car");
}`
but it keeps saying:
`error: cannot find attribute `pymethod` in this scope`
How should I do to achieve my purpose?Thanks!

**Comment by youknowone** [comment]
@sniffer123 It is interesting that it doesn't recognize macro expansion. You may be able to manually add it using `set_str_attr` the method object. I don't remember the details right now, but `cargo expand` will be helpful to look how the expansion works
