### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [RustPython/RustPython#3515]
Hey there!

I belong to an open source security research community, and a member (@srikanthprathi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by coolreader18** [comment]
Hmm, we don't really have a unified method of communicating to us. That.. would probably be a good idea to set up? In the meantime you could email me at coolreader18@gmail.com (which I just made cause I realized I should probably have an oss email) and I can share it with the other core devs.

**Comment by youknowone** [comment]
is this resolved?
