### ISSUE TITLE
TypeError: Unsupported operand types for '/': 'float' and 'float'

### ISSUE THREAD

**Issue by atomsymbol** [RustPython/RustPython#352]
Hello. I tried to run a small [mandelbrot.py](https://github.com/RustPython/RustPython/files/2834289/mandelbrot.py.txt) test and the interpreter reports a TypeError:

    ./rustpython mandelbrot.py 
    Traceback (most recent call last):
      File mandelbrot.py, line 12, in <module>
    TypeError: Unsupported operand types for '/': 'float' and 'float'

**Comment by windelbouwman** [comment]
Cool! Good test snippet!

**Comment by silmeth** [comment]
This probably should be closed now. :)

**Comment by atomsymbol** [comment]
The `end=''` in `print('*', end='')` is not supported yet.

**Comment by windelbouwman** [comment]
Implemented it! I see some performance differences :D

**Comment by atomsymbol** [comment]
Cool. It is 17x slower than CPython3.6.5 though, but more memory efficient according to `/usr/bin/time`.

**Comment by windelbouwman** [comment]
And on top of all: its memory safer!

**Comment by atomsymbol** [comment]
Performance just improved from 1.47 to 1.28 seconds.

**Comment by atomsymbol** [comment]
Performance has improved from 1.28 to 1.04 seconds.

**Comment by atomsymbol** [comment]
Performance has degraded from 1.04 to 1.23 seconds.

**Comment by adrian17** [comment]
(I think this should be tracked in another bug.)
