### ISSUE TITLE
rustpython VM storing defined functions across interpreter calls.

### ISSUE THREAD

**Issue by DurkelTheDonkey** [RustPython/RustPython#3556]
Hi, I'm using the rustpython VM and I'm trying to define some functions in one call and then at a later time I'd like to call those functions an arbitrary amount of times. The trouble I'm running into is saving the state across those calls to the interpreter and I end up trying to call functions that are not defined.
```rust
use rustpython_vm::compile::Mode;
use rustpython_vm::Interpreter;
use rustpython_vm::import::import_file;

fn main() {
    Interpreter::default().enter(|vm| {
        let imp = import_file(vm, "mylib", "mylib".to_owned(), MAIN.to_owned()).unwrap();
        let scope = vm.new_scope_with_builtins();
        let code_obj = vm
            .compile(
                r#"import * from mylib
init()"#,
                Mode::Exec,
                "<embedded>".to_owned(),
            )
            .unwrap();
        vm.run_code_obj(code_obj, scope).unwrap();
    });
    println!("Hello, rust!");
}

const MAIN: &str = r#"print("PYTHON MODULE INIT")
def init():
    print("Python says init")
"#;
```
This will print `PYTHON MODULE INIT` as it should when `MAIN` is compiled. However it will panic when I try to import the library or if I try to run `init` without importing the module.

How do I save the state (or scope) of the compiled `MAIN` module and pass it to the interpreter in later calls?

**Comment by coolreader18** [comment]
I'm not exactly sure what you mean by passing it to the interpreter, but I'd assume you're later calling `Interpreter::default().enter()` multiple times? Cause the solution for that is to just save the interpreter instead of recreating it every time, `let interp = Interpreter::default(); for _ in _ { interp.enter(|vm| { .. }); }`

Alternatively, you could just move your whole program into the `enter()` call.

**Comment by coolreader18** [comment]
Well in this you never have the `from mylib import *` bit, so there's not `init()` in scope. If you want to preserve that you should save `scope` as well and then it'll all happen in the same scope.

**Comment by DurkelTheDonkey** [comment]
Thank you, that clears up a lot of confusion, sorry for the inconvenience :)
