### ISSUE TITLE
Change PyAttributes type to IndexMap

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3607]
For now it is implemented with HashMap. But to keep the insertion order, it need to be changed to IndexMap.

**Comment by ShreyasB92** [comment]
Hi, I am a beginner. Can I contribute to this?

**Comment by youknowone** [comment]
If you have basic Rust experiences, yes. I guess this is not deeply related to RustPython architecture. Just by replacing the type from HashMap to IndexMap and fixing the following errors, it will work.

**Comment by youknowone** [comment]
closed by #3660
