### ISSUE TITLE
Add some sort of automatic clippy on pull requests

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#361]
Maybe a good github integration can be found which will run clippy on pull requests. Clippy is superhandy to learn new rust syntax you were unaware of.

See also:

https://github.com/marketplace/category/code-review

What are your opinions / ideas?

**Comment by makarchuk** [comment]
I think it's important to make sure clippy is happy, before introducing it into CI. So I ran clippy on a current code just for a test and it's not really happy with it.

It raises multiple errors of `if blocks have the same body` , like this one 

```
if objtype::isinstance(value, &self.ctx.tuple_type()) {
        objsequence::get_elements(value).to_vec()
} else if objtype::isinstance(value, &self.ctx.list_type()) {
        objsequence::get_elements(value).to_vec()
} else 
```


and this one (which I guess might be an actual bug)

```
error: using `clone` on a double-reference; this will copy the reference instead of cloning the inner type
   --> vm/src/obj/objsequence.rs:232:29
    |
232 |         new_elements.extend(elements.clone().to_owned());
    |                             ^^^^^^^^^^^^^^^^
    |
    = note: #[deny(clippy::clone_double_ref)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_double_ref
help: try dereferencing it
    |
232 |         new_elements.extend(&(*elements).clone().to_owned());
    |                             ^^^^^^^^^^^^^^^^^^^^
help: or try being explicit about what type to clone
    |
232 |         new_elements.extend(&[std::rc::Rc<std::cell::RefCell<pyobject::PyObject>>]::clone(elements).to_owned());
    |                             
```

I think I can issue a PR fixing those.

I can also try and set Travis up to run `cargo clippy`, but admittedly I never configured Travis before, so it might take some time.

**Comment by shinglyu** [comment]
@makarchuk You can copy one of the task in `matrix.includes` as an example: https://github.com/RustPython/RustPython/blob/master/.travis.yml#L22

Also remember to add it to `allow_failures` so it won't make the pipeline red. But it's nice to add it as allow to fail, even if clippy is not happy yet. Because this way people will start to see annoying yellow warnings and help fix it together.

**Comment by veera83372** [comment]
@makarchuk  Are you working on it?

**Comment by makarchuk** [comment]
I haven't started it yet, but I was planning on doing it this weekend, yes

**Comment by veera83372** [comment]
Okay cool

**Comment by makarchuk** [comment]
Sure, go for it
