### ISSUE TITLE
Add `__self__` and `__self_class__` property accessor for `super`

### ISSUE THREAD

**Issue by Snowapril** [RustPython/RustPython#3610]
## Feature
Add `__self__` and `__self_class__` for `PySuper`. Please refer this PR #3601 
For now, `obj` field in RustPython have both for `obj` and `obj_type` in cpython. See below link

## Python Documentation
https://github.com/python/cpython/blob/main/Objects/typeobject.c#L8755-L8772

**Comment by youknowone** [comment]
@djrmarques if you are looking for a good starting point to learn how RustPython works, this is a good starting point.
