### ISSUE TITLE
Array iterator name is different from CPython

### ISSUE THREAD

**Issue by Snowapril** [RustPython/RustPython#3612]
## Feature
The name of `array.array` iterator has to be `array_iterator` but `arrayiterator` in RustPython.

## Python Documentation
https://github.com/python/cpython/blob/3.8/Modules/arraymodule.c#L2993

**Comment by fanninpm** [comment]
Relevant code:

https://github.com/RustPython/RustPython/blob/cfb3505c70778aab6fe86fa47c7cad7368cb8452/stdlib/src/array.rs#L1282
