### ISSUE TITLE
issue building on ubuntu 20.04

### ISSUE THREAD

**Issue by verhulstm** [RustPython/RustPython#3669]
i am seeing this issue

#######

   Compiling rustpython-parser v0.1.2 (/home/user/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/4c39668/parser)
error: there is no argument named `byte`
  --> parser/build.rs:51:38
   |
51 |             write!(actual_sha3_str, "{byte:x}").unwrap();
   |                                      ^^^^^^^^

error: there is no argument named `kwds`
   --> parser/build.rs:107:10
    |
107 |         "{kwds}",
    |          ^^^^^^

   Compiling pmutil v0.5.3
error: could not compile `rustpython-parser` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rustpython v0.1.2 (https://github.com/RustPython/RustPython.git#4c39668b)`, intermediate artifacts can be found at `/tmp/cargo-install3Kixi8`

Caused by:
  build failed

#######
i ran

cargo install --git https://github.com/RustPython/RustPython.git rustpython --features ssl

**Comment by youknowone** [comment]
Maybe your rust compiler is outdated. If you installed rust from apt, remove it and install it again from rustup (https://rustup.rs/)
If you already installed rust from rustup, try to update it (rustup update)

**Comment by verhulstm** [comment]
great! that got me past that issue, thanks
