### ISSUE TITLE
Add support for dis module

### ISSUE THREAD

**Issue by cthulahoops** [RustPython/RustPython#367]
Lack of this makes compiler debugging more painful than it should be.

Will need us to make the code object work fully.

**Comment by ksunden** [comment]
`dis` module is pure python and appears to work, at least as far as my simple test goes

```
>>>>> def fib(a):
.....     return a if a < 2 else fib(a-1) + fib(a-2)
>>>>> for i in range(10):
.....    print(fib(i))
0
1
1
2
3
5
8
13
21
34
>>>>> dis.dis(fib)
                 0 LoadName             (a)
                 1 LoadConst            (2)
                 2 CompareOperation     (Less)
                 3 Duplicate
                 4 JumpIfFalse          (8)
                 5 Pop
                 6 LoadName             (a)
                 7 Jump                 (19)
          >>     8 LoadName             (fib)
                 9 LoadName             (a)
                10 LoadConst            (1)
                11 BinaryOperation      (Subtract, false)
                12 CallFunction         (Positional(1))
                13 LoadName             (fib)
                14 LoadName             (a)
                15 LoadConst            (2)
                16 BinaryOperation      (Subtract, false)
                17 CallFunction         (Positional(1))
                18 BinaryOperation      (Add, false)
          >>    19 ReturnValue
                20 LoadConst            (None)
                21 ReturnValue
```

(I have `PYTHONPATH=/usr/lib/python3.6/:/usr/lib/python3.6/site-packages`, just my distro provided python 3.6 standard lib)

**Comment by cthulahoops** [comment]
I really should have linked to this issue with my pull requests:

#512 and #555 add the beginnings of a rust implementation of the dis module, which is what you're seeing there.

Only dis and disassemble are implemented. (And dis doesn't support everything it should yet.)

As discussed in #445, the internals of the VM are too different to make compatibility with the python implementation of dis sensible at the moment.

This is still open as I'm still planning on fleshing out the dis module a bit more.

**Comment by youknowone** [comment]
is this still open?

**Comment by youknowone** [comment]
basic one is implemented
