### ISSUE TITLE
issue with rustpython --install-pip

### ISSUE THREAD

**Issue by verhulstm** [RustPython/RustPython#3670]
on ubuntu 20.04

i am getting this 

######

  File "/home/user/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/4c39668/vm/pylib-crate/Lib/zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "/tmp/tmp_1qijfve/pip.zip/pip/_vendor/cachecontrol/filewrapper.py", line 6, in <module>
ModuleNotFoundError: No module named 'mmap'

#####

while running

rustpython --install-pip

**Comment by youknowone** [comment]
Yes, this is recently broken because they started to require `mmap`. We don't have fix right now.

**Comment by fanninpm** [comment]
See also #3544

**Comment by youknowone** [comment]
#3755 is not enough to run pip again

**Comment by fanninpm** [comment]
As `mmap` is [_necessary_ but not _sufficient_](https://en.wikipedia.org/wiki/Necessity_and_sufficiency) to run pip, what do we need to tackle next?
