### ISSUE TITLE
int.real returns self for `int` type without subclassing

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3687]
when a is int,
```python
assert a.real is a
```

when a is subclass of int,
```python
assert a.real is not a
assert type(a.real) is int
```

**Comment by killme2008** [comment]
I test these statements with main branch, it looks fine as expected:

```
$ cargo run --release
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> class SubInt(int): pass
>>>>> subint = int.__new__(SubInt, 11)
>>>>> subint.real is not subint
True
>>>>> type(subint.real) is int
True
>>>>> a=1
>>>>> a.real
1
>>>>> a.real is a
True
```

**Comment by Snowapril** [comment]
@killme2008 It seems int methods(`conjugate`, `__trunc__`, `__floor__` and `__ceil__`) and getter(`real` and `numerator`) use the same function.
```c
static PyObject *
long_long(PyObject *v)
{
    if (PyLong_CheckExact(v))
        Py_INCREF(v);
    else
        v = _PyLong_Copy((PyLongObject *)v);
    return v;
}
```
According to the code, when a is exact `int` type it returns `self`. 
When it is not an exact real type, it creates an int-type object and copies the value to it.
At the current rustpython implementation, some of it did not follow the cpython's.

**Comment by youknowone** [comment]
@killme2008 I am sorry to make a poor description. That looks working for `a=1` due to small int cache. Testing with bigger number results wrong.

```python
>>>>> a = 100000000
>>>>> a.real is a
False
```
