### ISSUE TITLE
optional `key` argument for `_bisect` functions

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3693]
## Feature

`key` argument is added in CPython 3.10

## Python Documentation

https://docs.python.org/3/library/bisect.html

**Comment by supreetsingh10** [comment]
I would like to work on this. I am going through the code base, will reach out on gitter if I have questions.

**Comment by youknowone** [comment]
@supreetsingh10 This issue is already taken by @rebunto in #3695

**Comment by supreetsingh10** [comment]
> 

No problem, I will study the codebase and pick another issue soon. I will contact you on Gitter, if I need some guidance. Thanks
