### ISSUE TITLE
Triple quote multiline strings not supported in interactive shell

### ISSUE THREAD

**Issue by rayzchen** [RustPython/RustPython#3760]
I saw #33 and checked it but it seems that nothing has been done for strings that go over two lines, like:

```py
a = """
hello
this is after a newline
"""
```

Is there any reason for this? Or has it just not been implemented yet?
Using branch `main`.

```
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> """
SyntaxError: Got unexpected string at line 2 column 2

 ^
>>>>>
```

**Comment by youknowone** [comment]
Oh, I didn't know multi-line input is not supported in our interactive session.
That works with source file.

**Comment by rayzchen** [comment]
So it is supported, just not in the editor?
