### ISSUE TITLE
Is it possible to call the Rust code from the RustyPython?

### ISSUE THREAD

**Issue by Jerrody** [RustPython/RustPython#3782]
Like:
Rust:
```rs
fn cool() {}
```
Python:
```py
cool()
```

**Comment by youknowone** [comment]
Yes, but only for RustPython-compatible one. For now, you can create a module with the functions.

```rust
#[pymodule]
mod your_best_module {
    #[pyfunction]
    fn cool() {}
}
```

Then RustPython can call it like:

```python
import your_best_module

your_best_module.cool()
```

**Comment by Jerrody** [comment]
> Yes, but only for RustPython-compatible one. For now, you can create a module with the functions.
> 
> ```rust
> #[pymodule]
> mod your_best_module {
>     #[pyfunction]
>     fn cool() {}
> }
> ```
> 
> Then RustPython can call it like:
> 
> ```python
> import your_best_module
> 
> your_best_module.cool()
> ```

Thanks, for the answer.

**Comment by Jerrody** [comment]
> ```rust
> 
> mod your_best_module {
> ```

```rs
#[pymodule]
mod your_best_module {
    #[pyfunction]
    fn cool() {}
}
```

Is this a `pyo3` crate?

**Comment by Jerrody** [comment]
And another question. Does RustyPython support Python's libraries?

**Comment by Jerrody** [comment]
And the performance moment.
As I can see from benchmarks, RustyPython is very slow compared to CPython, Is this true?
https://rustpython.github.io/benchmarks

![image](https://user-images.githubusercontent.com/68968657/173291563-498e450a-f106-4086-af64-bb8e72e2ad57.png)

**Comment by youknowone** [comment]
No, you can't use pyo3 with RustPython. That's RustPython module.
Yes, unless the library is written in pure python. but never tensorflow. RustPython doesn't support C extension.
The benchmark is very old one. It's now 5~20x fater than before. But still very slower than CPython.

You'd better to share what you are looking for in RustPython.
In practice, you are safe to support RustPython is not production-ready yet. Try PyO3 if you need full python support.

RustPython only support pure-python codes and a lot of standard libraries. (Though not all of them)

**Comment by Jerrody** [comment]
> No, you can't use pyo3 with RustPython. That's RustPython module. Yes, unless the library is written in pure python. but never tensorflow. RustPython doesn't support C extension. The benchmark is very old one. It's now 5~20x fater than before. But still very slower than CPython.
> 
> You'd better to share what you are looking for in RustPython. In practice, you are safe to support RustPython is not production-ready yet. Try PyO3 if you need full python support.
> 
> RustPython only support pure-python codes and a lot of standard libraries. (Though not all of them)

Welp, I need it for the GameEngine API to interop with Engine via scripting. RustyPython interesting thing, but I also wanna integrate DL in the future and, of course, I thing that would be better if people can use any library that they want.

**Comment by Jerrody** [comment]
So, yeah, would be better to try `pyo3`.
