### ISSUE TITLE
itertools.chain should evaluate lazily

### ISSUE THREAD

**Issue by rng-dynamics** [RustPython/RustPython#3787]
CPython:
```
>>> from itertools import *
>>> a = chain.from_iterable(repeat(range(2)))
>>> next(a)
0
>>> next(a)
1
>>> next(a)
0
```

RustPython does not evaluate lazily and the call to `from_iterable` never returns:
```
>>>>> from itertools import *
>>>>> a = chain.from_iterable(repeat(range(2)))
```

**Comment by youknowone** [comment]
Ok, they are not interested in. We will add it to `extra_tests/snippets/stdlib_itertools.py`.

**Comment by rng-dynamics** [comment]
> Ok, they are not interested in it. We will add it to `extra_tests/snippets/stdlib_itertools.py`.

In #3788 I added a similar test.
