### ISSUE TITLE
pip cannot find any site-packages

### ISSUE THREAD

**Issue by JJJHolscher** [RustPython/RustPython#3808]
rustpython --install-pip fails for 
OS: Manjaro 21.3.0
Rustc: 1.81.0

```
downloading get-pip.py...
running get-pip.py...
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip
```

I managed to install pip with ensurepip from the ensure-pip branch. 

```
$ cargo run --release --features ssl -- -m ensurepip                                                                                              
[...]
Successfully installed pip-22.0.4 setuptools-58.1.0
```

But then the error repeated when I tried to install numpy beautifulsoup or configparser.

```
$ cargo run --release --features ssl -- -m pip install numpy                                                                                            
[...]
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement numpy (from versions: none)
ERROR: No matching distribution found for numpy
```

(_tangential_: I tried to debug `~/.local/lib/rustpython3.10/pip/_internal/index/package_finder.py`) in vscode but the default debugger would not start when rustpython was its interpreter. I have not raised an issue for this because I am unfamiliar with debugger internals.)

**Comment by dieterplex** [comment]
pip is going to look up pypi simple index page for packages and parsing links of candidate.
While parsing tags in html parser, it doesn't work correctly and give no links.
What I found currently is there's something wrong with `re` module internally that re match() give wrong result for tag end position.
It's similar to the failed test case `test_get_starttag_text` in `test_htmlparser.py`.

**Comment by fanninpm** [comment]
This has been a problem since late-January/early-February. See also:

- #3544
- #3670

**Comment by fanninpm** [comment]
@JJJHolscher does the absolute latest version of the `main` branch work for you?

**Comment by JJJHolscher** [comment]
> @JJJHolscher does the absolute latest version of the `main` branch work for you?
yes !
installing numpy failed because ctypes is not in rustpython yet, but configparser succeeded.

**Comment by JJJHolscher** [comment]
.
