### ISSUE TITLE
Cannot install pip with RustPython

### ISSUE THREAD

**Issue by pateljoel** [RustPython/RustPython#3825]
I'm trying to use pip with RustPython and i'm hitting into a pip error, I install 

I make sure that SSL is built with RustPython

```
cargo install --git https://github.com/RustPython/RustPython --features ssl
```

and once I install pip the error appears.

```
rustpython --install-pip
downloading get-pip.py...
running get-pip.py...
ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip
```

What am I missing?

**Comment by fanninpm** [comment]
> What am I missing?

This has been a problem since late-January/early-February. See also:

- #3544
- #3670
- #3808

**Comment by youknowone** [comment]
this is installable - not yet working
