### ISSUE TITLE
`PyUnionType` `hash` should be consistent regardless of the order of arguments.

### ISSUE THREAD

**Issue by Snowapril** [RustPython/RustPython#3851]
### CPython3.10
```python
>>> (str|int).__args__
(<class 'str'>, <class 'int'>)
>>> (int|str).__args__
(<class 'int'>, <class 'str'>)
>>> hash(str|int)
-2443872088029664091
>>> hash(int|str)
-2443872088029664091
```
### Python3.10
```python
>>>>> (str|int).__args__
(<class 'str'>, <class 'int'>)
>>>>> (int|str).__args__
(<class 'int'>, <class 'str'>)
>>>>> hash(str | int)
93930046793440
>>>>> hash(int | str)
93930046797200
```
This is related with `test_types::UnionTests::test_hash`.

**Comment by eaeiv** [comment]
Expanding on the issue, hashing the same Union back to back doesn't even net the same value.

A quick dive shows that hashing a `PyUnion` creates a `PyFrozenSet` from a `PyTuple` iterator of the Union. The hash function is then called on this new `PyFrozenSet` which calls down to `crate::utils::hash_iter_unordered`. 

```
pub fn hash_iter_unordered<'a, T: 'a + std::fmt::Display, I, F, E>(iter: I, hashf: F) -> Result<PyHash, E>
where
    I: IntoIterator<Item = &'a T>,
    F: Fn(&'a T) -> Result<PyHash, E>,
{
    let mut hash: PyHash = 0;
    println!("hash: {}", &hash);
    for element in iter {
        let item_hash = hashf(element)?;
        println!("--Start Iteration--");
        println!("item_hash: {}", &item_hash);
        // xor is commutative and hash should be independent of order
        hash ^= item_hash;
        println!("hash: {}", &hash);
    }
    println!("--End Loop--");
    Ok(fix_sentinel(mod_int(hash)))
}
```

This all looks fine (minus my ugly println!s), but  threw in the macros to observe the state of the `hash` and `item_hash`. This is where nothing makes sense.

1. I can reproduce the behavior described above.
2. The for loop only ever iterates once, no matter the length of the union. (The iterator should be pointing to the underlying elements vector)
```
>>>>> hash(int|str)
hash: 0
--Start Iteration--
item_hash: 2194653731728
hash: 2194653731728
--End Loop--
2194653731728
>>>>> hash(int|str|str)
hash: 0
--Start Iteration--
item_hash: 2194653734080
hash: 2194653734080
--End Loop--
2194653734080
>>>>> hash(int|str|str|bool)
hash: 0
--Start Iteration--
item_hash: 2194653734864
hash: 2194653734864
--End Loop--
2194653734864
```
3. The Union hashes don't ever evaluate to the same value anyway...
```
>>>>> hash(int|str)
hash: 0
--Start Iteration--
item_hash: 2194653733296
hash: 2194653733296
--End Loop--
**2194653733296**
>>>>> hash(int|str)
hash: 0
--Start Iteration--
item_hash: 2194653732960
hash: 2194653732960
--End Loop--
**2194653732960**
>>>>> hash(int|str)
hash: 0
--Start Iteration--
item_hash: 2194653735536
hash: 2194653735536
--End Loop--
2194653735536
>>>>> hash(int|str)
hash: 0
--Start Iteration--
item_hash: 2194653734752
hash: 2194653734752
--End Loop--
**2194653734752**
```

My theory is that its just hashing a reference to the `PyFrozenSet` that is created on every call of this hash function. This would explain the single loop iteration, as well as the constantly changing hash value. I'll keep looking for the fix, but something tells me my inexperience with the nuance of Rust's memory system is holding me back atm.

**Comment by moreal** [comment]
As a comment, I looked this issue and I realized the `PyTupleIterator` seems not working well. When I iterated the `PyTuple::iter`'s return value and prints the name of the elements with `class()`, it prints only `tuple_iterator`.

So I think the iterator works like:

```python
class tuple_iterator:
  def __iter__(self):
    yield self
```
