### ISSUE TITLE
traceback.tb_next is not writable

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3857]
See `PyTraceback` type.

It is writable at lease since Python 3.10
(I didn't track it down if it is changed or not)

#3862 requires this feature

**Comment by youknowone** [comment]
adding `#[pyproperty(setter)]` will fix it

**Comment by kimnanhee** [comment]
3857 issue, Could you assign me?

**Comment by youknowone** [comment]
Once this is done, the next commit can be reverted.

https://github.com/RustPython/RustPython/pull/3862/commits/1bc28033ae1660bfe0c783231092b3b3a2a10fa5

**Comment by youknowone** [comment]
revoke assignment by lost of tracking

**Comment by youknowone** [comment]
Once this is fixed, those lines need to be removed:  https://github.com/RustPython/RustPython/blob/e513bf11fee3836d08fe23a04799130f321a4739/Lib/unittest/result.py#L236-L238

**Comment by tgsong827** [comment]
Can I take over this issue ?
