### ISSUE TITLE
`set.update` should not use `IterNext`

### ISSUE THREAD

**Issue by Snowapril** [RustPython/RustPython#3866]
## Feature
Our `set.update` uses `IterNext` for iterating given args and update the set contents (makes sense).
But this makes incompatibility with cpython.
cpython's implementation is converting given args to tuple and uses `get_size` and `get_item`. 
As these method does not go through the `iternext`, there is no exception if the set is mutated during `update`. 

## Python Documentation
https://github.com/python/cpython/blob/3.10/Objects/setobject.c#L930-L941

## Related test cases
* `test_set.py` `test_merge_and_mutate`

**Comment by Snowapril** [comment]
I'm sorry for figuring out the correct causes. Here is a modified one.
```rust
for iterable in others {
    for item in iterable.iter(vm)? {
        self.add(item?, vm)?;
    }
}
```
Currently, rustpython use `IterNext` for the second loop. But cpython checks whether iterable in the second loop is `set` type or `dict` type. If it is not for both cases, it uses `IterNext`. Therefore, in the test cases, as the given iterable was set type so it should not use `IterNext`.
Please refer this code (https://github.com/python/cpython/blob/3.10/Objects/setobject.c#L881-L928)

**Comment by tgsong827** [comment]
I want to try this. Could you please assign to me?
