### ISSUE TITLE
Panic if second argument to assert isn't a string.

### ISSUE THREAD

**Issue by cthulahoops** [RustPython/RustPython#389]
```
>>>>> assert 1 == 0, 9
Traceback (most recent call last):
  File <unknown>, line 1, in <module>
thread 'main' panicked at 'Inner error getting str', vm/src/obj/objstr.rs:105:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by veera83372** [comment]
I would like to pick it up but I need a small clarification with the following things.

https://github.com/RustPython/RustPython/blob/07fd61f55f43844c1e7b6e6ebc8d91f0869b0353/vm/src/exceptions.rs#L74
Here we are assuming that everything is a string but it can be any type, so we need to get value from any type and pass it as a message.

**Comment by cthulahoops** [comment]
Yes, exactly. ```vm.to_str``` should do the job.

**Comment by veera83372** [comment]
Okay Thanks, Will do a PR

**Comment by cthulahoops** [comment]
I think the change doesn't belong there though, but in the code that raises the AssertionError. Not 100% sure though.
