### ISSUE TITLE
Several types in `itertools` module must be acceptable base type

### ISSUE THREAD

**Issue by Snowapril** [RustPython/RustPython#3890]
## Feature
`filterfalse`,  `chain`, `starmap`, `islice`, `takewhile`, `dropwhile`, `cycle`, and `compress` must be acceptable base types.
That is, those types should be possible being the base type of others like the below code.
```python
>>> import itertools
>>> class test(itertools.filterfalse): pass
```

## Python Documentation
* https://docs.python.org/3/c-api/typeobj.html?highlight=py_tpflags_basetype#Py_TPFLAGS_BASETYPE

## Relevant Test Case
* `test_itertools.py` `test_keywords_in_subclass`

**Comment by fanninpm** [comment]
Resolved in #3893
