### ISSUE TITLE
IndentationError works differently with cpython in interective shell.

### ISSUE THREAD

**Issue by Hyeonji-Ryu** [RustPython/RustPython#3892]
cpython returns `IndentationError` when it gets ‘\n’ after statements like `for`, `if`
-  cpython
```
>>> for i in range(1,4):
... 
  File "<stdin>", line 2
    
    ^
IndentationError: expected an indented block
```
but rustpython keeps waiting until some string come in.
- rustpython
```
>>>>> for i in range(1,4):
..... 
..... 
..... d
..... 
IndentationError: expected an indented block at line 4 column 1
```

**Comment by youknowone** [comment]
@kth496 do you have advices for this issue?

**Comment by kth496** [comment]
@youknowone I'm looking at it with Hyeonji-Ryu to solve the issue! 😀
