### ISSUE TITLE
getset doesn't have deleter

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3899]
`del` calls `setattr` with None in getset.

CPython type: `PyGetSetDef`
RustPython type: `PyGetSet`

#3897 is related

**Comment by moreal** [comment]
I'm not sure, but the `PyGetSet.deleter` may resolve this issue?

**Comment by youknowone** [comment]
Removing `PyGetSet.deleter` will resolve the issue.

**Comment by youknowone** [comment]
closed by #3904
