### ISSUE TITLE
Rust functions and python functions have the same type

### ISSUE THREAD

**Issue by cthulahoops** [RustPython/RustPython#390]
Rust functions should have a different type:

```
>>> type(abs)
<class 'builtin_function_or_method'>
```

This is important because certain methods don't make sense. (```__code__``` in particular.)

**Comment by Tom1380** [comment]
Tom1380/RustPython@432884e I think I got the first step right, but I can't find where the type is actually set, I need it to change the type to `builtin_function_or_method` for the Rust functions.

**Comment by Tom1380** [comment]
I thought the changes in Tom1380/RustPython@99b0b6f  would do the trick, but they make the shell panic, does somebody know why?

```
Welcome to the magnificent Rust Python 0.0.1 interpreter
>>>>> type(abs)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by cthulahoops** [comment]
The full failure path is convoluted! But I think it's because ```__get__``` is missing for the new type.

**Comment by Tom1380** [comment]
Ok I did it, if the tests pass I'm making the pull request.

**Comment by Tom1380** [comment]
@cthulahoops I made a pull request, can you take a look?

**Comment by Tom1380** [comment]
Sweet!
