### ISSUE TITLE
Need to cause `TypeError` message manually inside `slot_new` of `range` 

### ISSUE THREAD

**Issue by Snowapril** [RustPython/RustPython#3955]
## Feature
We need to cause `TypeError` message manually inside `slot_new` of `range`, not by `FuncArgs::bind`

if length of arguments is 
* 0 => "range expected at least 1 argument, got 0"
* 1~3 => just as implemented
* 4 ~ => format!("range expected at most 3 arguments, got {}", args.args.len())

## Python Documentation
* https://github.com/python/cpython/blob/3.10/Objects/rangeobject.c#L114-L122

## Related test cases
* `test_range::test_range_constructor_error_messages` https://github.com/RustPython/RustPython/blob/main/Lib/test/test_range.py#L94-L107

**Comment by youknowone** [comment]
The error message is very similar to our auto-generated message except for the function type part.
When the error messages are only including parameter count informations, I think we'd better to enhance `bind` part later instead of manually fixing this cases.

**Comment by Snowapril** [comment]
I agree. We need to enhance it at `FuncArgs::bind` side. I'll close the issue
