### ISSUE TITLE
Adding sqlite

### ISSUE THREAD

**Issue by CohenAriel** [RustPython/RustPython#3983]
https://docs.python.org/3/library/sqlite3.html

The CPython implementation uses a third party C library. I think that we have to use bindings like https://docs.rs/libsqlite3-sys/0.25.1/libsqlite3_sys/.

**Comment by youknowone** [comment]
I added you to assignee based on gitter chat

**Comment by CohenAriel** [comment]
Should I add it as a feature? If I should, should I add it to the default features?

**Comment by youknowone** [comment]
Mostly, it is up to windows. If users can build sqlite3-sys without painful preparation, feature is not necessary.

**Comment by CohenAriel** [comment]
It's just a Cargo dependency, but in CPython I don't think it downloads the
sqlite library automatically so idk.

**Comment by youknowone** [comment]
Yes, I think most of them are not doing that. I think feature is better in very high chance unless it is very easy as libz-sys.

**Comment by jamestwebber** [comment]
> It's just a Cargo dependency, but in CPython I don't think it downloads the sqlite library automatically so idk.

I'm fairly sure that on Windows CPython includes the sqlite library automatically, as part of the installation.

**Comment by CohenAriel** [comment]
Maybe, but when building from source if you don't have the library installed it doesn't install it. https://devguide.python.org/getting-started/setup-building/index.html#compile-and-build

**Comment by jamestwebber** [comment]
Ah yes you're right. My attempts to work with Python on Windows, a long time ago, are coming back to me 😂 

It looks like they have subprojects in the MSVC project and there's a script to download the sources for sqlite support. They do mention it as optional--I'm not sure if the resulting interpreter fails gracefully when someone tries `import sqlite3` but I kinda doubt it.
