### ISSUE TITLE
Exposing functions/classes from Java (using a WASM runtime) to RustPython

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [RustPython/RustPython#3985]
Heya, the title says it all haha, I'm interested in trying to embed RustPython into my Java application, and I want to use it as a scripting language, but I don't know how I'd expose a function to it at all really, is there anything specific I'd need to do? Any advice to use this within Java too? GraalVM would be ideal but as that isn't an option for me, I'd like to look at other ways of doing this

**Comment by youknowone** [comment]
wow, interesting challenge.

This is including 3 separated parts.
1. exporting java symbol to wasm side.  I think you will handle this well.
2. importing wasm symbol to rust. I don't know well about wasm, but `wasm_bindgen` is the part rust recognize wasm symbols in rust.
3. RustPython recognize wasm symbols as Python function. I think this is manually approachable like `wasm/lib/src/js_module.rs`, but not sure how to do exactly.

@coolreader18 any advice?

**Comment by Mythical-Forest-Collective** [comment]
> 1. exporting java symbol to wasm side. I think you will handle this well.

I've actually seen a few projects such as "New Moon With Report" that give this functionality, I just don't know if it'll run with RustPython haha, something to test when i can

**Comment by Mythical-Forest-Collective** [comment]
I am realising this would be better as a discussion

**Comment by Mythical-Forest-Collective** [comment]
Created a discussion for this instead: #3997
