### ISSUE TITLE
_winapi.GetModuleFileName

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4001]
## Feature

_winapi.GetModuleFileName

## Python Source code
https://github.com/python/cpython/blob/v3.10.5/Modules/_winapi.c#L1292-L1324

**Comment by tushushu** [comment]
Hey, I'm new here. May I work on this issue?

**Comment by jiang1997** [comment]
I'd like to take on this issue.

**Comment by jiang1997** [comment]
Am I supposed to implement this using ``winapi``?

**Comment by youknowone** [comment]
Using `windows` will be better!
