### ISSUE TITLE
I can't bulid rustpython and I don't know why

### ISSUE THREAD

**Issue by shenjian333333** [RustPython/RustPython#4030]
warning: unused imports: `PyStrRef`, `PyTupleRef`, `TryFromObject`, `function::Either`, `suppress_iph`
  --> vm\src\stdlib\nt.rs:14:20
   |
14 |         builtins::{PyStrRef, PyTupleRef},
   |                    ^^^^^^^^  ^^^^^^^^^^
15 |         common::{crt_fd::Fd, os::errno, suppress_iph},
   |                                         ^^^^^^^^^^^^
16 |         convert::ToPyException,
17 |         function::Either,
   |         ^^^^^^^^^^^^^^^^
...
22 |         PyResult, TryFromObject, VirtualMachine,
   |                   ^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

   Compiling rustpython v0.1.2 (C:\Users\zhouy\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\dff916d)
warning: `rustpython-vm` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 3m 53s
     Running `C:\Users\zhouy\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\dff916d\target\debug\rustpython.exe`
thread 'main' panicked at 'initialization failed; run with RUST_BACKTRACE=1 to see Python backtrace', vm\src\vm\mod.rs:251:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\zhouy\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\dff916d\target\debug\rustpython.exe` (exit code: 101)

C:\Users\zhouy\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\dff916d\src>

**Comment by dzvon** [comment]
Please follow the steps in https://github.com/RustPython/RustPython/blob/main/DEVELOPMENT.md#setting-up-a-development-environment, and see what happens.
