### ISSUE TITLE
Adding clippy linting configurations

### ISSUE THREAD

**Issue by veera83372** [RustPython/RustPython#406]
I am planning to add some kind of `allow/deny` configuration in the root level of project in a `clippy.toml`.

does it anyone have any suggestions/ideas?

**Comment by windelbouwman** [comment]
@veera83372 we are using clippy now, do you have any edits you still want to make? Otherwise we can close this issue maybe?

**Comment by veera83372** [comment]
I don't have anything, we can close this issue
