### ISSUE TITLE
allow `from __future__ import generator_stop`

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4060]
## Feature

code:
```python
from __future__ import generator_stop
```

Expected: Nothing

Actual: SyntaxError: future feature generator_stop is not defined

## TODO

Add it to `compile_future_features` function

**Comment by matheusfgoncalves95** [comment]
Hey everyone. This is my very first contribution to open source, but here goes nothing: #5320.

Thanks in advance.
