### ISSUE TITLE
class.__doc__ is wrong

### ISSUE THREAD

**Issue by Yaminyam** [RustPython/RustPython#4085]
## CPython
```
>>> class c: pass
...
>>> print(type(c).__doc__)
type(object) -> the object's type
type(name, bases, dict, **kwds) -> a new type
```

CPython version is 3.10.4

## RustPython
```
>>>>> class c: pass
>>>>> print(type(c).__doc__)
type(object_or_name, bases, dict)
type(object) -> the object's type
type(name, bases, dict) -> a new type
```

**Comment by youknowone** [comment]
what was the CPython version?

using text block (\`\`\`) will be better for text-only reports.

```
>>> class c: pass
...
```

**Comment by Yaminyam** [comment]
> what was the CPython version?
> 
> using text block (```) will be better for text-only reports.
> 
> ```
> >>> class c: pass
> ...
> ```

The text has been edited!

**Comment by youknowone** [comment]
we maintain generated doc db here: https://github.com/RustPython/__doc__
