### ISSUE TITLE
Refactor f-string parser

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4102]
F-string parser is not efficient enough.
Especially not easy to maintain the brace pairs.

First step:
FStringParser need to take &str and consume any amount of matching characters and returns &str again. The remaining bytes will be fed to parser again.

Second steps
- parse function for outer brace and inner expr need to be separated.
- location need to be correctly passed to inner expressions

**Comment by fanninpm** [comment]
Before making the f-string parser more efficient, it might be better to make it _compliant_ with https://github.com/python/cpython/blob/3.10/Lib/test/test_fstring.py (without crashing or throwing unnecessary `SyntaxError`s).

**Comment by youknowone** [comment]
The brace matching is really painful for current structure. I think the first step is also related to implement future features.

**Comment by dvermd** [comment]
I'd like to work on this one.
Could you elaborate a little more on what would be the first step ?

I understand the location passing to the inner expressions as `Location::default()` is used when creating sub-parsers.
Splitting `FStringParser::parse` also seems like a good idea.

**Comment by youknowone** [comment]
`FStringParser::parse` currently consume its inner iterator and returns only its parsed result. Due to its design, we need to detect the end of f-string first and pass the substring iterator to FStringParser.
If we can remove the char iterator from FStringParser and users can pass &str to `FStringParser::parse` and take &str from its result, we will not need to find the end of f-string before calling FStringParser::parse.

**Comment by dvermd** [comment]
Can you explain why the parser accepts stacked '{}' for the format specifier ? I don't manage to forge a working example on cpython with these. I must be missing something...

**Comment by fanninpm** [comment]
@dvermd have you tried taking a look at https://github.com/python/cpython/blob/3.10/Lib/test/test_fstring.py?

**Comment by charliermarsh** [comment]
@youknowone - Heads up that there's a new PEP focused on formalizing the f-string grammar, which is now open for comment: https://discuss.python.org/t/pep-701-syntactic-formalization-of-f-strings/22046
