### ISSUE TITLE
platform.python_implementation returning "CPython"

### ISSUE THREAD

**Issue by ecpost** [RustPython/RustPython#4111]
Python's platform.python_implementation function is now returning "CPython" instead of "RustPython".  I believe it is because Lib/platform.py was refreshed recently (2daddd913dc2bf0dbc046159f28d897508199815) with the latest from CPython, which contains the python_implementation function.  Previously, that function (among other things) had been removed from Lib/platform.py back in 2020 (bbb04c3dedc6af62f2567b5af4292bff97f8780f) so that the Rust version of that function in stdlib/src/platform.rs would handle the implementation.

I noticed this because it breaks whats_left.py.  (There's a check to make sure the sub-process isn't running CPython, and it now thinks it is, even though it's from "cargo run...".)

I can work on a PR, but I wasn't sure if there's more to this, like other related changes in the works or whatever.  If not, I could bascially mimic what was done in bbb04c3dedc6af62f2567b5af4292bff97f8780f.  Let me know if I can help.

**Comment by youknowone** [comment]
Oh, thank you! it was a mistake. It will be great if you can try.

@palaviv do you have advice?

**Comment by ecpost** [comment]
Comparing the last version of platform.py (prior to the 3.10.6 update) to the very first version (which matches the CPython version from late 2019), there are 3 areas with changes:
- The libc_ver function has a TODO comment and immediate return of the defaults at the beginning of the function.
- The _syscmd_uname function has a similar change.
- A large section of code is removed (compiled regexes, a cache, and all the python_* functions that were redone in Rust) and replaced with `from _platform import *`.

That should be easy enough for me to do to the 3.10.6 version.  I can wait a bit to see if palaviv has any comments first.

Regarding the old TODO's in there, I could take a closer look at those too and see if I can take care of them.  I'm thinking it should be a separate PR so the "CPython" platform issue is fixed sooner rather than later.

**Comment by youknowone** [comment]
palaviv is not very active these days. You can go ahead as you want. Your analysis sounds very clear

**Comment by ecpost** [comment]
Ok, thanks.  I have it ready.  I'm not able to build at the moment, I think because of #4117?  I'll submit the PR later...

**Comment by youknowone** [comment]
That must be not a problem when you build from project root. How it fails?

**Comment by youknowone** [comment]
Deleting code can mislead future update if the CPython code is updated - exactly what I thought.
The typical python flow to check native module is checking import error.

```python
try:
    from _platform import *
except ModuleNotFound:
    # Add python function here
```
This pattern will prevent it.

**Comment by youknowone** [comment]
@ecpost if you are looking for easy-medium level issues, we have a series of TODO list in number protocol: #3244

**Comment by ecpost** [comment]
> That must be not a problem when you build from project root. How it fails?

I'll put the details in #4117.  (Or let me know if it's better to open a new issue.)

---

I see your platform.py change in #4128 -- is that just a temporary workaround, and I should still continue with the original change to platform.py I proposed (apply the 2020 changes to the new 3.10.6 version)?

---

> ... This pattern will prevent it.

Are you suggesting I take the code I was going to delete and put it in that except block?  Just confirming.
