### ISSUE TITLE
python.rs file is not generated locally

### ISSUE THREAD

**Issue by lastmjs** [RustPython/RustPython#4166]
If I want to fork RustPython and access it locally in a Rust project, it doesn't currently work because `RustPython/compiler/parser/python.rs` is not generated. I haven't been able to figure out how to generate it, so I just copied the file from my `.cargo` folder.

**Comment by fanninpm** [comment]
@youknowone does this have to do with LALRPOP not being installed?

**Comment by fanninpm** [comment]
@lastmjs Try `cargo clean` followed by `cargo build`. Does that work?

**Comment by youknowone** [comment]
@fanninpm that's not intended

**Comment by lastmjs** [comment]
I would expect it to just work after I've cargo installed RustPython

**Comment by lastmjs** [comment]
I think my issue might be a duplicate of this: https://github.com/RustPython/RustPython/issues/4117

**Comment by lastmjs** [comment]
I also have all features turned off, should I have `rustpython-parser/lalrpop` as a feature?

**Comment by lastmjs** [comment]
I believe this has been resolved with https://github.com/RustPython/RustPython/pull/4176
