### ISSUE TITLE
does gc implemented????

### ISSUE THREAD

**Issue by yuyang-ok** [RustPython/RustPython#4181]
https://github.com/RustPython/RustPython/blob/main/stdlib/src/gc.rs

**Comment by fanninpm** [comment]
The short answer (right now) is no. Every time RustPython runs into a reference cycle, the cycle will live until the whole program comes to a stop, gets terminated, or runs out of memory.

However, progress is being made. See #4158 and #4180.

**Comment by yuyang-ok** [comment]
ok , thanks.
