### ISSUE TITLE
Update libraries to Python 3.11

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4247]
3.11 is released today.

**Comment by fanninpm** [comment]
@jopemachine from what I've seen, you seem to be interested in updating the code in the `Lib/` directory. Do you want to take care of this upgrade? If so, how much do you want to tackle?

**Comment by jopemachine** [comment]
> @jopemachine from what I've seen, you seem to be interested in updating the code in the `Lib/` directory. Do you want to take care of this upgrade? If so, how much do you want to tackle?

Thanks for letting me know.
I'm interested in participating in RustPython's various issues including python the Lib update,
but unfortunately I'm not sure how much time I can spend on this for now because I have to process several personal works.

**Comment by lastmjs** [comment]
I'm excited for the upgrade, our project needs this issue to be resolved which has been resolved in Python 3.11: https://github.com/python/cpython/issues/89026

**Comment by lastmjs** [comment]
Sorry  I wasn't asking to be assigned, just saying I'm excited and that this is important to our project.

**Comment by fanninpm** [comment]
@lastmjs I took a look at the PR you linked, and it seems easy enough to update the files mentioned in that PR. Would you like to give it a try and send us a PR?

**Comment by lastmjs** [comment]
No thanks, I am happy waiting

**Comment by youknowone** [comment]
replaced by #4564
I can't believe I made the same issue just a few weeks ago.
