### ISSUE TITLE
`bytecode/src` is not found

### ISSUE THREAD

**Issue by yt2b** [RustPython/RustPython#4294]
https://github.com/RustPython/RustPython/blob/f54b5556e28256763c5506813ea977c9e1445af0/DEVELOPMENT.md?plain=1#L176-L177

`DEVELOPMENT.md` says that implementation of bytecode is in `bytecode/src` directory.

But `bytecode/src` is not found.
I think that `compiler/core/src` is correct here.
Has directory structure changed?

**Comment by DimitrisJim** [comment]
> Has directory structure changed?

Yeah, that section probably needs some updating :smile:

**Comment by yt2b** [comment]
Directory structure has changed in #4119, #4121.
I'll fix `DEVELOPMENT.md`.
