### ISSUE TITLE
Is the start location of `ExprKind::BoolOp` correct?

### ISSUE THREAD

**Issue by harupy** [RustPython/RustPython#4305]
In https://github.com/charliermarsh/ruff/pull/1009, I found the start location of `ExprKind::BoolOp` points to `or` or `and`.

Example:

```python
foo or bar
    ^

foo and bar
    ^

# ^ represents the start location of this BoolOp expression
```

Is this intended? Should the start location point to `foo` in the example above?

```python
foo or bar
^

foo and bar
^
```

**Comment by harupy** [comment]
Not sure if this works, but can we move `<location:@L>` before `<e1:AndTest>`?

https://github.com/RustPython/RustPython/blob/18af44b7c7410c3448df1f3b080bd358e586d265/compiler/parser/python.lalrpop#L758-L766

**Comment by youknowone** [comment]
Thank for you reporting. That seems going to be working.

**Comment by harupy** [comment]
@youknowone Thanks for the comment. I'll file a PR.
