### ISSUE TITLE
Checking unmatched "raiseregex" leads to rustpython panicked

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4312]
In the following example, we instance a object of unittest, then the unmatched error is collected by the assertRaisesRegex, rustpython get panicked.

test.py:

```
import unittest

class uTest(unittest.TestCase):
	pass

uTest = uTest()

with uTest.assertRaisesRegex(Exception, 'aaa'):
     aab
```

Behavior on rustpython(rustpython 0.1.2):
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', vm/src/suggestion.rs:55:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Expected behavior(behavior on CPython 3.9.1):
`NameError: name 'aab' is not defined`

Step to reproduce:
type "cargo run --release test.py" on the console of Ubuntu 18.04 and MacOS Big Sur 11.7.1
rust version: rustc 1.65.0

**Comment by DimitrisJim** [comment]
If a traceback doesn't exist when looking for suggestions, `None` should just be returned instead of `unwrap`ing.
