### ISSUE TITLE
Extra argument in compile() leads to panicked.

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4316]
The following test assign the compile() four arguments, then rustpython thread 'main' get panicked.

test.py:
```
import sys
PyCF_ONLY_AST = 1024
obj = compile('1', '', 'exec', PyCF_ONLY_AST)
```

Behavior on rustpython(rustpython 0.1.2):
```
thread 'main' panicked at 'static type has not been initialized', vm/src/class.rs:22:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Behavior on CPython 3.9.1(Expected):
work well

Step to reproduce:
type "cargo run --release test.py" on the console of Ubuntu 18.04 or MacOS Big Sur 11.7.1
rust version: rustc 1.65.0

**Comment by DimitrisJim** [comment]
Nice find. `ast` is not initialized here (i.e, if you `import ast` before running this, it works fine). Seems we also need to initialize `ast` earlier (it exists in `sys.modules` for cpython but not for rustpython).
