### ISSUE TITLE
atexit.register() takes exited function causing rustpython panicked

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4318]
In the following example, we define a function 'myexit' that executes sys.exit(2). The we call the atexit.register(), rustpython get panicked. 

test.py:
```
def myexit():
    import sys
    sys.exit(2)
import atexit
atexit.register(myexit)
```

Behavior on rustpython(rustpython 0.1.2):
```
Error in atexit._run_exitfuncs: <function myexit at 0x7fd048796290>
  File "/Users/xiaxinmeng/Downloads/RustPython-main/pylib/Lib/traceback.py", line 206, in print_stack
    print_list(extract_stack(f, limit=limit), file=file)
thread 'main' panicked at 'assertion failed: unraisable.exc_type.fast_issubclass(vm.ctx.exceptions.exception_type)', vm/src/stdlib/sys.rs:550:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Behavior on CPython 3.9.1(Expected):
work well

Step to reproduce:
type "cargo run --release test.py" on the console of Ubuntu 18.04 and MacOS Big Sur 11.7.1
rust version: rustc 1.65.0

**Comment by DimitrisJim** [comment]
For anyone interested: this involves changing the class in the assert statement from exception to base exception, it doesn't seem to catch `SystemExit` since `isinstance(SystemExit(), Exception)` is false.

**Comment by jan-krecke** [comment]
Hi @DimitrisJim, hi @xiaxinmeng,

I would like to try to tackle this. I'm pretty new to Rust, though, and completely new to RustPython, so I hope I can be of use. 

I have changed the exception type from `exception_type` to `base_exception_type`. Now, when running the snippet provided by @xiaxinmeng , it exits with

```shell
Error in atexit._run_exitfuncs: <function myexit at 0x55ac73c4eac0>
  File "/path/to/repo/RustPython/pylib/Lib/traceback.py", line 206, in print_stack
    print_list(extract_stack(f, limit=limit), file=file)
: 2
``` 

instead of (Python 3.11.1):

```shell
Exception ignored in atexit callback: <function myexit at 0x7f7cfa40c4a0>
Traceback (most recent call last):
  File "/path/to/repo/RustPython/examples/atexit_test.py", line 3, in myexit
    sys.exit(2)
SystemExit: 2
```

@DimitrisJim,  do you have any tips on where to look to make the exit equal to the CPython one?

**Comment by jan-krecke** [comment]
Well, I guess this `// TODO` has to be hashed out
https://github.com/RustPython/RustPython/blob/c01f014b1269eedcf4bdb45d5fbc62ae2beecf31/vm/src/stdlib/sys.rs#L554-L563
