### ISSUE TITLE
Multiple 'for' loop make rustpython panicked.

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4319]
The following test defined a nested 'for' loop at line 4, then rustpython gets panicked 

test.py:
```
class F:
    def a(self):
        x = None
        x = [[(x_1 := 2) for self in range(2)] for x in range(2)]
        print(x, self)
F().a()
```

Behavior on rustpython(rustpython 0.1.2):

```
thread 'main' panicked at 'internal error: entered unreachable code: var x_1 in a Function should be free or cell but it's Local', compiler/codegen/src/compile.rs:1215:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Behavior on CPython 3.9.1(Expected):
`[[2, 2], [2, 2]] <__main__.F object at 0x7f91076e8fd0>`

Step to reproduce:
type "cargo run --release test.py" on the console of Ubuntu 18.04 or MacOS Big Sur 11.7.1
rust version: rustc 1.65.0

**Comment by youknowone** [comment]
it seems more like a walrus operator(:=) bug than loop itself.

**Comment by yt2b** [comment]
Same panic has occured with the following code.

```
def f():
    [[x := 1 for j in range(5)] for i in range(5)]
```

```
thread 'main' panicked at 'internal error: entered unreachable code: var x in a Function should be free or cell but it's Local', compiler/codegen/src/compile.rs:1215:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I looked into CPython implementation. 
If symbol is defined as LOCAL and in free list, Symbol scope is replaced from LOCAL to CELL.

https://github.com/python/cpython/blob/0264f634f720fbf12afaf1715a53cd1495fbd85b/Python/symtable.c#L572-L603

Symbol defined with walrus operator inside comprehension should be Cell in outer scope.
