### ISSUE TITLE
Import standart modules.

### ISSUE THREAD

**Issue by alexpantyukhin** [RustPython/RustPython#434]
What if to implement some of standart modules like `os`, `itertools` etc?

**Comment by Tom1380** [comment]
What do you mean?

**Comment by alexpantyukhin** [comment]
I mean to allow use the following code for example:
```python
import os
print(os.name)
```

**Comment by Tom1380** [comment]
Ok I’m sorry I thought we could already do it.

**Comment by coolreader18** [comment]
Can this be closed? Your example of `os.name` now works.
