### ISSUE TITLE
Duplicate parameter names are allowed

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#4368]
Currently, using a parameter with the same name as a positional/default/keyword is allowed:

```python
>>>>> def f(*a, **a): pass
>>>>> def f(a, *, a): pass
>>>>> def f(a, a=0, *, a): pass
```

In CPython, all fail with the appropriate message:

```python
>>> def f(*a, **a): pass
... 
  File "<stdin>", line 1
SyntaxError: duplicate argument 'a' in function definition
```

**Comment by branai** [comment]
Would you do this by modifying compiler/parser/python.lalrpop ?

**Comment by DimitrisJim** [comment]
@branai we get a view of the parsed params in the function `parse_params` of  `compiler/parser/src/function.rs`. That's where the checking for duplicate names should probably live.

**Comment by branai** [comment]
@DimitrisJim I could be wrong, but it looked like starred arguments were parsed in ```parse_args```, separately from the parameters in ```parse_params```. I'll double check later today.

**Comment by nicku12345** [comment]
Hi @DimitrisJim @branai , I am interested in this item and debugged a bit. I have made a PR (my first PR here) in https://github.com/RustPython/RustPython/pull/4380. Could you guide me through to see if it is correct?
