### ISSUE TITLE
Implement `strict_mode` keyword parameter in `binascii.a2b_base64()`

### ISSUE THREAD

**Issue by moreal** [RustPython/RustPython#4374]
Since Python 3.11, `binascii.a2b_base64()` function became to provide `strict_mode` keyword parameter. [^1]

[^1]: https://docs.python.org/3/library/binascii.html?highlight=binascii#binascii.a2b_base64

## Related links

 - Python docs: https://docs.python.org/3/library/binascii.html?highlight=binascii#binascii.a2b_base64
 - RustPython implementation: https://github.com/RustPython/RustPython/blob/1d8269fb729c91fc56064e975172d3a11bd62d07/stdlib/src/binascii.rs#L147
 - CPython implementation: https://github.com/python/cpython/blob/deaf509e8fc6e0363bd6f26d52ad42f976ec42f2/Modules/binascii.c#L388

**Comment by evanrittenhouse** [comment]
I can try to take this on! I'm new to the project but I'll take a stab at it.

**Comment by evanrittenhouse** [comment]
Not sure why that PR got closed - I'm still working on it, though it may take a while.

**Comment by youknowone** [comment]
closed by #4460
