### ISSUE TITLE
Report argument name when a duplicate keyword argument is present

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#4381]
Currently we don't mention the keyword name that was detected as a duplicate, i.e:

```python
>>> def foo(**kwargs): pass
>>> foo(k=10, k=20)
```

Results in:

```
SyntaxError: keyword argument repeated at line 1 column 8
```

While in CPython, the same call:

```
SyntaxError: keyword argument repeated: k
```

Ignoring our addition of the line/col numbers (which need some fixing), the same message should exist, i.e:

```
SyntaxError: keyword argument repeated: k at line 1 column 8
```

should be the wanted result.

**Comment by fanninpm** [comment]
Have you tried creating a `.py` file with that example?

**Comment by DimitrisJim** [comment]
yup, am I missing something?

**Comment by fanninpm** [comment]
I was thinking that the line/column information may be redundant in some cases (e.g. running a file), but not others (e.g. running interactively).

**Comment by anilbey** [comment]
Hello, I'm new to Rust. I come from a Python background. 
I thought contributing to RustPython can be a very good start for me :)

I just tried to address this issue in #4382. Does it look good to you?

The output with the #4382 change:
```
>>>>> def foo(**kwargs): pass
>>>>> foo(k=10, k=20)
SyntaxError: keyword argument 'k' repeated at line 1 column 10
foo(k=10, k=20)
```
