### ISSUE TITLE
Tokenizer is missing `NL` token

### ISSUE THREAD

**Issue by charliermarsh** [RustPython/RustPython#4385]
The CPython tokenizer has both a `NEWLINE` and `NL` token.

Given this code:

```python
x = (
  "a"
  "b"
)

x = "a" \
  "b"
```

RustPython currently outputs the same tokenization for these two snippets (modulo the left and right parens -- notice that in both cases, we have `String` followed by `String`):

```
Name {
    name: "x",
}
Equal
Lpar
String {
    value: "a",
    kind: Normal,
}
String {
    value: "b",
    kind: Normal,
}
Rpar
Newline
Name {
    name: "x",
}
Equal
String {
    value: "a",
    kind: Normal,
}
String {
    value: "b",
    kind: Normal,
}
Newline
```

Whereas in CPython, there are `NL` tokens in the first case that aren't present for continuations:

```
❯ python -m tokenize test.py
0,0-0,0:            ENCODING       'utf-8'
1,0-1,1:            NAME           'x'
1,2-1,3:            OP             '='
1,4-1,5:            OP             '('
1,5-1,6:            NL             '\n'
2,2-2,5:            STRING         '"a"'
2,5-2,6:            NL             '\n'
3,2-3,5:            STRING         '"b"'
3,5-3,6:            NL             '\n'
4,0-4,1:            OP             ')'
4,1-4,2:            NEWLINE        '\n'
5,0-5,1:            NL             '\n'
6,0-6,1:            NAME           'x'
6,2-6,3:            OP             '='
6,4-6,7:            STRING         '"a"'
7,2-7,5:            STRING         '"b"'
7,5-7,6:            NEWLINE        '\n'
8,0-8,0:            ENDMARKER      ''
```

**Comment by DimitrisJim** [comment]
I remember quickly looking into this but not replying in the other issue. `NL` seems to be a token only used for the python implementation of the tokenizer (i.e `tokenize.py`), [this comment](https://github.com/python/cpython/blob/79c10b7da84f52999dc483fc62c8e758ad3eff23/Grammar/Tokens#L65) indicates this.

`NL` is used for physical lines while `NEWLINE` for logical ones, the C tokenizer appears to just join the physical lines to make a logical one while the Python version doesn't, now sure why that is.

**Comment by bluetech** [comment]
I am working on porting a tokenizer-level linter flake8-commas to Ruff, and it relies on NL.

I reckon NL should be emitted in an `else` case here:

https://github.com/RustPython/RustPython/blob/main/compiler/parser/src/lexer.rs#L1073-L1083

CPython tokenize.py code for comparison:

https://github.com/python/cpython/blob/e8097d49f64e47f0ad7568e7181e6e2c466b6964/Lib/tokenize.py#L540-L544

https://github.com/python/cpython/blob/e8097d49f64e47f0ad7568e7181e6e2c466b6964/Lib/tokenize.py#L507-L508

I'll try to see if it works when I get a chance.

BTW, I think the `NL`/`NEWLINE` names are pretty bad, so maybe in RustPython should call `NL` something like `NonLogicalNewline`?

**Comment by DimitrisJim** [comment]
Okay, I now see why this issue was initially raised, wasn't aware linters depend on the `NL` but it makes sense . The alternative would be *also* running the Python tokenizer which would be prohibitive.
