### ISSUE TITLE
`PyInt.format` only raises `ValueError`

### ISSUE THREAD

**Issue by yt2b** [RustPython/RustPython#4387]
In the current implementation, `PyInt.format` only raises `ValueError`.

https://github.com/RustPython/RustPython/blob/2c8af125e396f9dee73bd426a0bc088b60c30969/vm/src/builtins/int.rs#L569-L574

But in CPython, Other error can also be raised.

```
>>> f"{-1:c}"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: %c arg not in range(0x110000)
```

**Comment by yt2b** [comment]
@DimitrisJim 
I'll work on this issue.

**Comment by DimitrisJim** [comment]
great, thanks for your recent work on the formatting @yt2b!
