### ISSUE TITLE
Unnecessary clones

### ISSUE THREAD

**Issue by nhynes** [RustPython/RustPython#440]
For instance, in `int_add()` in `objint.rs`, `get_value()` makes a clone, but only a reference is needed. For numerics-heavy benchmarks, most of the time is spent in `malloc`, as a result. Here's a fix:

```diff
diff --git a/vm/src/obj/objint.rs b/vm/src/obj/objint.rs
index 7f03216..698ab20 100644
--- a/vm/src/obj/objint.rs
+++ b/vm/src/obj/objint.rs
@@ -256,7 +256,10 @@ fn int_add(vm: &mut VirtualMachine, args: PyFuncArgs) -> PyResult {
     );
     let i = BigInt::from_pyobj(_i);
     if objtype::isinstance(i2, &vm.ctx.int_type()) {
-        Ok(vm.ctx.new_int(i + get_value(i2)))
+        Ok(vm.ctx.new_int(i + match i2.borrow().payload {
+            PyObjectPayload::Integer { ref value } => value,
+            _ => panic!("Invalid payload type")
+        }))
     } else if objtype::isinstance(i2, &vm.ctx.float_type()) {
         Ok(vm
             .ctx
```

The same holds for other invocations of `get_value` (and for other types). The issue here is that `fn get_value` must return an owned int despite only a ref being needed. A simple solution is something like

```rust
macro_rules! get_value {
  ($obj_ref:ident, $payload_type:ty) => {
    match $obj_ref.borrow().payload {
      $payload_type { ref value } => value,
      _ => panic!("Invalid payload type"),
    }
  }
}
```

Also, panicking is a not-so-great idea when the enclosing function returns a `Result` anyway.

**Comment by cthulahoops** [comment]
Rather than using a macro, I think we can use a function signature something like this?

```
pub fn get_value<'a>(obj: &'a PyObjectRef) -> &'a IntType {
```

We panic here because the Result value represents a python exception, but this case should be unreachable and represents a bug in the interpreter. There's no recoverable exception.

**Comment by nhynes** [comment]
> I think we can use a function signature something like this?

That was my initial hunch, but the lifetime of `pyobj_ref.borrow()` is shorter than the borrow of the returned value. AFAIK you'd have to return `(value, borrow)` to extend the lifetime. The macro works because the borrow lifetime is lexical.

**Comment by HomerMcMillan** [comment]
```rust
pub fn get_value<'a>(obj: &'a PyObjectRef) -> impl Deref<Target = Vec<u8>> + 'a {
    Ref::map(obj.borrow(), |py_obj| {
        if let PyObjectPayload::Bytes { ref value } = py_obj.payload {
            value
        } else {
            panic!("Inner error getting int {:?}", obj);
        }
    })
}
```
This is the bytes object version of `get_value`. You can do this to get around the short lifetime on `pyobj_ref.borrow()`. I don't think it even needs a trait object as the return, you can just return a `Ref<BigInt>`

**Comment by youknowone** [comment]
`objint::get_value` now returns `&BigInt`.

We probably will fight with other unnessessary clones for forever.
