### ISSUE TITLE
Direct write to sys.stdout prints a wrong string

### ISSUE THREAD

**Issue by grihabor** [RustPython/RustPython#4448]
Hi! I've built rustpython from [current master](https://github.com/RustPython/RustPython/tree/acbc517b55406c76da83d7b2711941d8d3f65b87) and got this strange bug. When I write smth to stdout it appends string length at the end

## Expected behavior

```python
>>> import sys
>>> sys.stdout.write('hey')
hey3
>>> sys.stdout.write('hey what')
hey what8
```

## Actual behaviour

```python
>>>>> import sys
>>>>> sys.stdout.write('hey')
hey3
>>>>> sys.stdout.write('hey what')
hey what8
```

**Comment by coolreader18** [comment]
Ah, that's actually just the repl displaying the result of the call! If you assign it to a variable you can see it stops happening.
