### ISSUE TITLE
Store byte indices on tokens and nodes

### ISSUE THREAD

**Issue by charliermarsh** [RustPython/RustPython#4468]
In Ruff, we often need to go from `Location` to byte index (e.g., if we know a statement starts on row 31, column 4, we need a way to map that to a byte index in the source code, so that we can do a slice in the appropriate spot).

Today, we solve this problem by [indexing the source code in advance](https://github.com/charliermarsh/ruff/blob/a7ce8621a9c43bae200bdea60aa6803ef497ede1/src/source_code/locator.rs#L1) -- so, we iterate over all characters, and create a map from (row, column) to byte index.

It would be nice if this information was already included in the parser's representation, since in theory, we have the byte indices during lexing.

Though I haven't dug into the details, I assume it's enough to extend `Location` to include a byte index during lexxing -- then the parsing step would "just work"? (This does create some oddities whereby methods like `go_right` no longer make sense on `Location`, since that byte offset isn't well-defined in isolation, so perhaps it needs to be a separate piece of data, independent from `Location`.)

Is RustPython open to supporting something like this?

**Comment by DimitrisJim** [comment]
> I assume it's enough to extend Location to include a byte index during lexxing

If I'm understanding the idea correctly, this would be slightly tricky mainly due to the handling of new lines on Windows. Our `NewLineHandler` simply slides over the `'\r'` character so any count based on what the `Lexer` sees would be slightly off.

If that is tackled then I can see how lexer might hold onto a running count of the byte index (incrementing it with every `next_char` call) and insert that into a `Location` when `get_pos` is called on it (AFAIK, nothing in the next stages after the lexer care what `Location`s members are, so we could add an index in there).

**Comment by charliermarsh** [comment]
I'm happy to work on this when I have time. I think my main hesitation is around how it changes the semantics of `Location`. As an example: in Ruff, I sometimes want to take a location, and "jump to the next line". So I just increment the row by one, and set the column to zero. If `Location` has a `byte_index` field, though, I can't really do that anymore -- I have to figure out the byte index of that next line in order to create a `Location`. So, maybe that field becomes `Option`? Or maybe there's a separate struct, like `ContextualizedLocation`? Or maybe it's passed in as separate fields on `Located`?

**Comment by DimitrisJim** [comment]
> So I just increment the row by one, and set the column to zero.

Do you require the index for these locations you create or only for `Location`s created via the lexer? If the former is required it seems like some sort of mapping like you currently create would be required. If the latter, `Location` could have an optional field, as you propose, which can only be set by the lexer and all other methods on `Location` could be non-mutating and return a new `Location` with the index set to `None`. 

At least, that's an initial thought on it.

**Comment by charliermarsh** [comment]
Ah yeah, I guess I do need them for locations that I create. That's a good point. So perhaps this is unavoidable, unless the lexer somehow created and output that map separately from the token stream itself. But, that seems like it's an API that's catering to too-specific of a use-case.
