### ISSUE TITLE
[RFC] Doesn't compile on Linux aarch64: expected `i8`, found `u8`

### ISSUE THREAD

**Issue by jonathanslenders** [RustPython/RustPython#4493]
## Summary

I've a 64bit Linux VM on Apple Silicon. Both for 0.2.0 as well as on the main branch, compilation fails. I'm getting 20 errors, but all of them are in `sqlite.rs`, and all errors are the same. Here are the first few:

```
 $ cargo build
   Compiling rustpython-stdlib v0.2.0 (/home/jonathan/git/RustPython/stdlib)
error[E0308]: mismatched types
    --> stdlib/src/sqlite.rs:122:20
     |
122  |         ptr_to_str(s, vm).unwrap().to_owned()
     |         ---------- ^ expected `i8`, found `u8`
     |         |
     |         arguments to this function are incorrect
     |
     = note: expected raw pointer `*const i8`
                found raw pointer `*const u8`
note: function defined here
    --> stdlib/src/sqlite.rs:2806:8
     |
2806 |     fn ptr_to_str<'a>(p: *const i8, vm: &VirtualMachine) -> PyResult<&'a str> {
     |        ^^^^^^^^^^     ------------

error[E0308]: mismatched types
    --> stdlib/src/sqlite.rs:527:39
     |
527  |                 let stmt = ptr_to_str(expanded, vm).or_else(|_| ptr_to_str(sql.cast(), vm))?;
     |                            ---------- ^^^^^^^^ expected `i8`, found `u8`
     |                            |
     |                            arguments to this function are incorrect
     |
     = note: expected raw pointer `*const i8`
                found raw pointer `*mut u8`
note: function defined here
    --> stdlib/src/sqlite.rs:2806:8
     |
2806 |     fn ptr_to_str<'a>(p: *const i8, vm: &VirtualMachine) -> PyResult<&'a str> {
     |        ^^^^^^^^^^     ------------
```

Is there anything I'm doing wrong, or would this be a bug?

**Comment by DimitrisJim** [comment]
@qingshi163 any ideas what might be causing this? Pinging since you merged the `sqlite` implementation recently.

**Comment by jonathanslenders** [comment]
@youknowone : Doing a simple find/replace in `stdlib/src/sqlite.rs` of the change you're proposing seems to work. It compiles and works without any issues. I'm not using sqlite3 here, so didn't test in depth.

**Comment by fanninpm** [comment]
Feel free to submit a PR for this.

____

If you want RustPython to run our copy of the CPython test suite, you can use this command:

```shell
cargo run --release --features ssl,jit -- -m test -j 1 -u all --slowest --fail-env-changed -v
```
If you only want RustPython to run the `test_sqlite3` test from the CPython test suite, you can use this command:

```shell
cargo run --release --features ssl,jit -- -m test -j 1 -u all --slowest --fail-env-changed -v test_sqlite3
```

For a list of all resources and more command-line options, you can execute `cargo run --release --features ssl,jit -- -m test -h`.

**Comment by jonathanslenders** [comment]
FYI: this is the output of the test suit on my machine:
```
----------------------------------------------------------------------
Ran 63 tests in 0.541s

OK (skipped=7, expected failures=11)

== Tests result: FAILURE ==

270 tests OK.

10 slowest tests:
- test_socket: 38 sec 863 ms
- test_xmlrpc: 36 sec 3 ms
- test_signal: 32 sec 407 ms
- test_subprocess: 32 sec 391 ms
- test_io: 29 sec 308 ms
- test_statistics: 27 sec 565 ms
- test_pickle: 22 sec 298 ms
- test_decimal: 16 sec 414 ms
- test_selectors: 12 sec 953 ms
- test_trace: 12 sec 503 ms

8 tests failed:
    test_grp test_ioctl test_pathlib test_posixpath test_pwd
    test_shutil test_socket test_urllib2

3 tests skipped:
    test_ctypes test_univnewlines test_zipfile64

Total duration: 8 min 28 sec
Tests result: FAILURE
```

**Comment by williamdes** [comment]
Thank you @jonathanslenders for fixing this !
It now builds on (https://github.com/sudo-bot/docker-rustpython/actions/runs/4243160081):

- `linux/386` (not affected by the fix)
- `linux/amd64` (not affected by the fix)
- `linux/arm/v6`
- `linux/arm/v7`
- `linux/arm64/v8`
- `linux/ppc64le`

But not on s309x because of the nix crate:
- See: https://github.com/nix-rust/nix/issues/1968
- See: https://github.com/nix-rust/nix/pull/1835

**Comment by williamdes** [comment]
Update: thix nix crate merged the s390x fix!
