### ISSUE TITLE
Recently added `_feature_version` parameter in `compile()` is not supported yet

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4515]
## Feature

it prints error messages:
```
TODO: compile() got `_feature_version` but ignored
```

**Comment by dannasman** [comment]
Hi!

How and where exactly should the `_feature_version` be used? I looked at CPython and to my understanding it is used to compute parser flags there.

**Comment by youknowone** [comment]
I didn't investigate what it is. But it is used in https://github.com/python/cpython/blob/3.11/Lib/ast.py#L50-L51
If it is harmless, just safely ignoring without error message will be fine.

**Comment by DimitrisJim** [comment]
yeah, I don't know how much sense it makes to support it. `feature_version` allows parsing code as previous versions of Python. I think we can ignore it and add a TODO instead (so it doesn't spam the output).
