### ISSUE TITLE
Some valid named unicode characters cause syntax errors

### ISSUE THREAD

**Issue by charliermarsh** [RustPython/RustPython#4566]
`"\N{BACKSPACE}another cool trick"` yields a syntax error in RustPython, but runs without error on CPython.

See: https://github.com/charliermarsh/ruff/issues/3207.

**Comment by charliermarsh** [comment]
For reference, Python does throw errors on obviously-invalid named unicode characters like `"\N{AAA} another cool trick"`.

**Comment by DimitrisJim** [comment]
Seems like this is coming from `unicode_names2`. `unicode_names2::character("BACKSPACE")` doesn't return a character.

**Comment by fanninpm** [comment]
Related question (out of curiosity): What does `unicode_names2::name('\x08')` return?

**Comment by DimitrisJim** [comment]
It's also a `None`, it doesn't support any of the control characters (so `'\N{LINE FEED}'`, `\N{NUL}'` etc, all raise SyntaxErrors).

**Comment by DimitrisJim** [comment]
After a bit of searching it appears it doesn't support [name aliases](http://www.unicode.org/Public/12.1.0/ucd/NameAliases.txt) (which all these control characters fall into). I personally don't know of any libs that support it but we could just grab that file, parse it and have `unicodedata` and the string parser fall back to it.

**Comment by youknowone** [comment]
[unic-ucd-name_aliases](https://docs.rs/unic-ucd-name_aliases/) supports getting alias from the name but not the other way.

**Comment by youknowone** [comment]
https://github.com/progval/unicode_names2/issues/11

**Comment by youknowone** [comment]
unicode_names2 will take patch
https://github.com/progval/unicode_names2/issues/11#issuecomment-1445037320
