### ISSUE TITLE
Format panic in test_int__format__locale

### ISSUE THREAD

**Issue by minhrongcon2000** [RustPython/RustPython#4588]
## Issues

In `Lib/test/test_types.py``test_int__format__locale`, if you change from `format(x, 'n')` to `format(x, ',')` and run the test, RustPython will panic! It doesn't crash in CPython!

See #4593 for test case

**Comment by youknowone** [comment]
not reproducible

**Comment by minhrongcon2000** [comment]
@youknowone Another way to reproduce this is to run the following code
```
x = 123456789012345678901234567890
for i in range(0, 30):
    format(x, ',')
    x = x // 10
```
This will result in a panic!

**Comment by fanninpm** [comment]
Do you have a stack trace? If so, it would be helpful for you to copy-paste the terminal output. If the output is too lengthy, you can put it in a `<details>` tag, like this:

````markdown
<details>
<summary>Stack trace</summary>

```text
{paste the stack trace here, please}
```
</details>
````
___

Here is the result: 
<details>
<summary>Stack trace</summary>

```text
{paste the stack trace here, please}
```
</details>

**Comment by minhrongcon2000** [comment]
@fanninpm I updated the above comment with stack trace

**Comment by youknowone** [comment]
I made test case at #4593. Anyone who want to work on this issue can start from the commit.

**Comment by daksh-code** [comment]
I'm working on this issue
