### ISSUE TITLE
Dictionaries are represented internally with string keys

### ISSUE THREAD

**Issue by OddBloke** [RustPython/RustPython#46]
Python allows any hashable object to be used as a key.

**Comment by OddBloke** [comment]
I spent a while this evening poking around at this, and it's less than trivial to fix; `RefCell` doesn't implement Hash (presumably because the contained value is essentially always mutable), which means we can't just use a naive `HashMap<PyObjectRef, PyObjectRef>` (instead of the current `HashMap<String, PyObjectRef>`.

**Comment by cthulahoops** [comment]
Ouch. It's a pretty fundamental problem given that you can create broken dicts in python by messing with hash on mutable objects. I guess we'll need an unsafe hash table implementation that mirrors python's quirks.

Maybe we can get away with using rust hash tables where the keys are common rust types?

**Comment by OddBloke** [comment]
My first thought (once I'd realised the fundamental problem) was that `PyObjectRef` could become a struct (instead of the simple type definition it is now) which implements `Hash` by borrowing the `PyObject` contained in the `RefCell` and calling its hash implementation (which we'd also have to write, of course). I don't know what performance impact that might have (but perhaps having something is better than nothing, and we can revisit the performance issues later once we can run anything but toy examples).

My initial run at the `PyObject` `Hash` implementation (as part of the conversion of the `HashMap` type which I ended up aborting) is pushed up at https://github.com/OddBloke/RustPython/commit/08a41820493d83f8f4c00e69caa19446ec4bd39d. I was still experimenting, so I didn't think too carefully about which types should/shouldn't be hashable; it still serves to illustrate the rough idea.

Specific issues with that: there are some types that shouldn't be hashable (e.g. lists), and there are some types which should be hashed by identity, _not_ by value.

(Also, perhaps your classes work will get us to the point where we can also consider calling `__hash__` on objects?)

**Comment by OddBloke** [comment]
A drive-by thought: we need to retain a reference to the key objects somehow, because Python dictionaries allow us to iterate over the keys.

(Also, `__hash__()` isn't the only thing used in determining identity for dictionary keys:

```py
>>> class Foo:
...   def __hash__(self):
...     return 1
... 
>>> d = {}
>>> d[Foo()] = 1
>>> d[Foo()] = 2
>>> d
{<__main__.Foo object at 0x7fbed66f7c18>: 1, <__main__.Foo object at 0x7fbed66f7be0>: 2}
```
)

**Comment by windelbouwman** [comment]
Another issue is that custom object can implement `__hash__` and `__eq__`. But to run those functions, we actually require the `VirtualMachine` struct. If we would implement the `Hash` trait on PyObject, we would still require the `VirtualMachine` reference somehow.

**Comment by shinglyu** [comment]
Maybe we can do some hybrid, try to use HashMap if the key is some simple type, and use the Vec implementation when the key gets complicated? But I agree that the Vec implementation is not optimal. If user expects the performance characteristic of a hash map but we give them a linear list, it might cause some library to be terribly slow.

**Comment by shinglyu** [comment]
@OddBloke I believe `__eq__` also plays a role in your example, I'm not sure how the default implementation should be.

```
>>> class Foo:
...    def __hash__(self):
...       return 1
...    def __eq__(self, other):
...       return self.__hash__() == other.__hash__()
... 
>>> x = Foo()
>>> y = Foo()
>>> dd = {}
>>> dd[x] = 1
>>> dd[y] = 2
>>> dd
{<__main__.Foo instance at 0x7f2336174fc8>: 2}
```

**Comment by cthulahoops** [comment]
There might be a problem with the hybrid solution (rust hashmaps for string keys, something else in other cases) that we (might) need to preserve object identity when the keys are strings:

```
>>> list(d.keys())[0] is x
True
```

Could be fixed by a ```Hashmap<String, (PyObjectRef, PyObjectRef)>```.  Which leads me to: ```HashMap <i64, vec!<(PyObjectRef, PyObjectRef)>>``` (where the ```i64``` is the result of ```key.__hash__```).

There's also the fact that dictionaries in python 3.7 are supposed to preserve insertion order.

**Comment by windelbouwman** [comment]
Ah, that might be an idea! We could use this: `HashMap<usize: Vec<(PyObjectRef, PyObjectRef)>>`. The ordering still remains a problem, but then we have already a start!

Btw, I suggest to keep `HashMap<String, PyObjectRef>` for class and module dictionaries.

**Comment by cthulahoops** [comment]
At some point we'll need to implement slots too, which is probably a major performance thing.

**Comment by shinglyu** [comment]
Adding the relavant spec here: https://docs.python.org/3.7/library/stdtypes.html#typesmapping

> Changed in version 3.7: Dictionary order is guaranteed to be insertion order. This behavior was an implementation detail of CPython from 3.6.

If we have to fulfill all these requirements maybe it's better to implement the hashmap manually copying  to cpython's design.

But in general I believe the priority is 
1. Allow keys other then `String` > 2. Allow iterating the keys and preserve the key object identity >>> 3. Keep the insertion order

I'll try to study the cpython implementation this weekend.

**Comment by cthulahoops** [comment]
Blog post on the implementation: https://morepypy.blogspot.com/2015/01/faster-more-memory-efficient-and-more.html

CPython: https://github.com/python/cpython/blob/master/Objects/dictobject.c

**Comment by windelbouwman** [comment]
Hilarious video: https://www.youtube.com/watch?v=p33CVV29OG8

**Comment by windelbouwman** [comment]
Okay, implementation strategy in steps:
- Change to HashMap<String, PyObjectRef> for Instance and Class types to reduce dependency on actual dict.
- Implement ordered list as in cpython/pypy 
- Change dict insert/delete to require a vm reference, such that we can call python functions.
- Glue everything together..

**Comment by cthulahoops** [comment]
If I'm following correctly, I'm sceptical on point 1. It's possible to get references to the dictionary for both instances and classes, and to manipulate it in various ways. I think it has to be a fully featured python dictionary.

(Though I think we can bypass a full dictionary for rust defined classes.)

**Comment by windelbouwman** [comment]
@cthulahoops would you do the honors and close this issue?

**Comment by cthulahoops** [comment]
```
>>>>> {True: 'fixed'}[True]
'fixed'
```
