### ISSUE TITLE
Refactor Symbolic Strings

### ISSUE THREAD

**Issue by holygits** [RustPython/RustPython#463]
There are symbolic strings littered throughout the code base.
e.g. "\_\_repr\_\_", "\<module\>"

These should be hidden behind ~enums~ static constants

**Comment by windelbouwman** [comment]
Why would you hide string behind enums? Is this a performance thing?

**Comment by holygits** [comment]
Oh sorry, I meant static constants, in some cases maybe an enum would work? ¯\_(ツ)_/¯

**Comment by windelbouwman** [comment]
Would this result in code size reduction?

**Comment by holygits** [comment]
I think this is ok to close. It was from a maintenance point of view, updates, typos etc. It was pointed out in the PR that the strings are unlikely to change
