### ISSUE TITLE
Investigate the `with` statement changes related to context manager

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4650]
introduced from #4648 and #4649

**Comment by dalinaum** [comment]
I took a quick look, made the following patch, and it worked for `test_with`, but not for `test_contextlib`. I'll look into it a bit more.
dalinaum@f4b51e299f4dcaef3d72c3a16e7b46f2eacad9fd

**Comment by youknowone** [comment]
done by @dalinaum on #4656 and #4659
