### ISSUE TITLE
Compile issue in aarch64

### ISSUE THREAD

**Issue by TheYkk** [RustPython/RustPython#4661]
The type of `libc::c_char::MAX` is different on aarch64 which is `u8` however its `i8` in x86_64 systems
https://github.com/RustPython/RustPython/blob/01512e27a0c8c95d28e134e196b06530e3372540/stdlib/src/locale.rs#L41

Afte I changed the `i8` to `u8` it compiled without any issues.

```
ubuntu@instance-20230306-0019:~/rust/RustPython$ rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

Tested commit id
`commit 01512e27a0c8c95d28e134e196b06530e3372540`

**Comment by youknowone** [comment]
@TheYkk Could you open a PR for the fix?

**Comment by rjzak** [comment]
Same issue on `powerpc64le-unknown-linux-gnu`. Fixed with either `while ![0, libc::c_char::MAX].contains(&*ptr) { ` or `while ![0 as libc::c_char, libc::c_char::MAX].contains(&*ptr) { `.
