### ISSUE TITLE
Add at least one architecture `libc::c_char == u8` build to CI

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4665]
to prevent breaking #4661

**Comment by youknowone** [comment]
`aarch64-unknown-linux-gnu` looks good. The only Tier 1, so the toolchain would be stable.

**Comment by yugborana** [comment]
hii, I would like to contribute, if you could tell more about the process to be done in this issue

**Comment by DimitrisJim** [comment]
@yugborana great! You basically need to update the workflow file to add the target. If you take a look at the current workflow, there's already some checks made [for other targets](https://github.com/RustPython/RustPython/blob/9b55505cdf514f591cc913e615693ff92f58ff71/.github/workflows/ci.yaml#L192) which you could use as inspiration.

**Comment by yugborana** [comment]
well, I am very new to this, what new updates I have to make in workflow file? Sorry for disturbance

**Comment by youknowone** [comment]
I'd not to recommend this issue if you are very new to github actions. Would you look in #4564 ?

**Comment by yugborana** [comment]
yeah ok

**Comment by youknowone** [comment]
closed by #4704
