### ISSUE TITLE
LALRPOP warns incompatibility to future version of Rust

### ISSUE THREAD

**Issue by fanninpm** [RustPython/RustPython#4680]
Starting with the Rust 1.68 release, we will start seeing this error:

```text
warning: the following packages contain code that will be rejected by a future version of Rust: lalrpop v0.19.8
```

___

_Feel free to air your grievances about the things you find lacking from LALRPOP._

**Comment by DimitrisJim** [comment]
@youknowone has already opened a PR upstream for this (and so have others, I think there's three PRs open for this atm). It seems LALRPOP is also used in rustup https://github.com/rust-lang/rustup/issues/3213 so I'm hoping this might result in some activity on it.
