### ISSUE TITLE
Encoding and functools ModuleError

### ISSUE THREAD

**Issue by basicfunc** [RustPython/RustPython#4691]
## Feature

While running program, 
```
from functools import lru_cache as lc

@lc
def fib(s):
    if s <= 1:
        return s

    return fib(s-2) + fib(s-1)


for i in range(5_000_000):
    print(f"Fib for {i}: {fib(i)}")
```
I received, 
```
encodings initialization failed. Only utf-8 encoding will be supported.
ModuleNotFoundError: No module named 'encodings'

The above exception was the direct cause of the following exception:

RuntimeError: Could not import encodings. Is your RUSTPYTHONPATH set? If you don't have access to a consistent external environment (e.g. if you're embedding rustpython in another application), try enabling the freeze-stdlib feature
Traceback (most recent call last):
  File "C:\Users\Rahul\tests\fib.py", line 1, in <module>
    from functools import lru_cache as lc
ModuleNotFoundError: No module named 'functools'
```

![image](https://user-images.githubusercontent.com/84739019/225354814-a3f0e560-48a9-4584-aeda-de9e8feee2a8.png)

which is rather weird, I understand if `functools` are not implemented for current implementation of `RustPython`, but why this encoding errors?

Whats more surprising is that it works on playground,
![image](https://user-images.githubusercontent.com/84739019/225355738-8fa993a2-cced-4c95-b775-7255ec1fd20f.png)

Did I missed something while compiling?
I compiled just by `cargo b --release -j10`

## Python Documentation

Here is current implementation of [`functools`](https://github.com/python/cpython/blob/main/Lib/functools.py)

**Comment by basicfunc** [comment]
It appears to be I compiled `RustPython` without `stdlib`, while trying to compile `RustPython` on Windows with the `freeze-stdlib` feature. I noticed that the error occurred due to a difference in how Windows and Linux handle symbolic links.

Upon inspecting the source code, I found that the directory being referred to in the code was a symbolic link, which is interpreted differently on Windows than on Linux. As a result, the compilation failed with the following error message:

![image](https://user-images.githubusercontent.com/84739019/225375302-29aff0de-8499-49cd-84c3-e67f401828ae.png)

While digging deep, I was able to find bug and resolve it where I just hardcoded the `/Lib` directory path in `\pylib\src\lib.rs` as follows:

![image](https://user-images.githubusercontent.com/84739019/225377287-0704be11-47ec-40a8-b330-35ba369f8ad4.png)

**Just replaced `/Lib` with `../Lib`.**

**Comment by youknowone** [comment]
did you set environment variable `RUSTPYTHONPATH` but still getting the problem?

**Comment by basicfunc** [comment]
> did you set environment variable RUSTPYTHONPATH but still getting the problem?

I able to compile `RustPython` with `stdlib` and it resolved the issue. But the problem is it doesn't compile on Windows without the change I mentioned in PR #4695.
