### ISSUE TITLE
Performance significantly slower than CPython on basic benchmarks

### ISSUE THREAD

**Issue by basicfunc** [RustPython/RustPython#4694]
I have benchmarked `RustPython` against `CPython` on three basic algorithms - Fibonacci sequence, matrix multiplication, and quicksort. In all three cases, `RustPython` is significantly slower than `CPython`, taking at least 9 seconds to complete tasks that CPython completes in under 1 second.

I have used the following hardware and software configurations for my tests:

- CPU: 12th Gen Intel(R) Core(TM) i5-1235U
- RAM: 8GB
- Operating System: Windows 11
- CPython version: 3.10.10
- RustPython version: 0.2.0 (Release Build)

# **I have used the following code for my benchmarks:**
## Quicksort example:
![image](https://user-images.githubusercontent.com/84739019/225370373-ee1a8cd4-0a20-4363-b2c7-c13c2112cae1.png)

## Fibonacci Series example:
![image](https://user-images.githubusercontent.com/84739019/225370398-e7f8f2e8-8a46-4dd1-b0b1-d9db6e1dab94.png)

## Matrix Multiplication Example
![image](https://user-images.githubusercontent.com/84739019/225371970-0bb6d75d-4e5c-4197-a6df-738d134fece8.png)

**Comment by DimitrisJim** [comment]
Yup. This is a known issue. Perhaps we should add it as a section in the README since people commonly have this question/commonly do these benchmarks.

**Comment by basicfunc** [comment]
Okay, can I expect some perfomance improvements in future?

**Comment by DimitrisJim** [comment]
Oh there's definitely been work on that front. How much improvement and how soon definitely depends on the amount of time people can spend on it so can't offer any guarantees there!

**Comment by basicfunc** [comment]
Okay, that's a good news.
