### ISSUE TITLE
Invalid comment style

### ISSUE THREAD

**Issue by BenSchweitzer** [RustPython/RustPython#4717]
I can't get the project to build on my local machine using dev containers in VS Code. Digging through the logs I found that https://github.com/RustPython/RustPython/commit/330eaf3ed6d944d31d2b3b590c029279c24cdd2b introduced a TODO comment using python style comments (#) instead of rust (//).

https://github.com/RustPython/RustPython/blob/1218ddd5dc9a4153399d7d7c701e26dc9dd77998/vm/src/anystr.rs#L379-L380

**Comment by fanninpm** [comment]
This should be fixed by #4719.
