### ISSUE TITLE
panicked when output buffer is resized too many times

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4729]
See the following example, the output buffer is resized too many times, then the thread 'main' get panicked.

test.py
```
size = 8*1024
for i in range(1, 120):
    print('Step %d ' % i, format(size, ','), 'bytes')
    size = size + (size >> 3) + 6
```

Output:
```
Step 1  8,192 bytes
.....
Step 60  8,584,834 bytes
Step 61  9,657,944 bytes
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Behavior on CPython 3.10.8 (work well):
```
Step 1  8,192 bytes
......
Step 118  7,953,906,657 bytes
Step 119  8,948,144,995 bytes
```

Reproduce step:
install rustpython with command "cargo install --git https://github.com/RustPython/RustPython", then "rustpython test.py"

Environment:
Ubuntu 18.04
rustic 1.68.0
rustpython v0.2.0 (#a824e7b3)

**Comment by xiaxinmeng** [comment]
This bug seems to be fixed in the commit d39b44c4d3863e8d0c88e64a5c3e85fa437b77ae. All versions of RustPython get crashes with this example before this commit, while all versions after this commit can work well.

**Comment by DimitrisJim** [comment]
Thanks for finding the commit @xiaxinmeng. Closing as fixed.

**Comment by youknowone** [comment]
great, so it was formatting bug when the bytes hits specific value. Thank you!
