### ISSUE TITLE
Update crates.io with RustPython 0.2.0

### ISSUE THREAD

**Issue by itsankitkp** [RustPython/RustPython#4793]
Currently crates.io says latest RustPython version to be v0.1.2 but I can see current version v0.2.0 in github releases. Shouldn't crates.io point to latest version (v0.2.0) as well?

README.MD banner mentions few failing builds/outdated dependencies corresponding to v0.1.2, it would be better if it shows latest version instead.

**Comment by DimitrisJim** [comment]
See also: https://github.com/RustPython/RustPython/issues/3539
