### ISSUE TITLE
Contextvars: creation of Contextvar object fails with RuntimeError

### ISSUE THREAD

**Issue by itsankitkp** [RustPython/RustPython#4796]
Found while working on https://github.com/RustPython/RustPython/issues/4791

Issue:
in RustPython 0.2.0
```
>>>>> from contextvars import ContextVar
>>>>> ContextVar('var', default=42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected payload 'ContextVar' but 'ContextVar' found
```
in cpython 3.12a
```
>>> from contextvars import ContextVar
>>> ContextVar('var', default=42)
<ContextVar name='var' default=42 at 0x7f10fe687d20>
```
I am bit fuzzy about its implementation. In cpython, PyContext is stored in PyThreadState (atleast this is what I can see in context_get in [context.c](https://github.com/python/cpython/blob/main/Python/context.c) ).
Should we create similar datastructure and store in PyThreadState equivalent (which is what, VirtualMachine here?).
And this should go to fn init for ContextVar like this?
```
    impl Initializer for ContextVar {
        type Args = ContextVarOptions;

        fn init(_obj: PyRef<Self>, _args: Self::Args, _vm: &VirtualMachine) -> PyResult<()> {
             // create some objects here
            _obj.name = _args.name.to_string();
            _obj.default = _args.default.into();
            Ok(())
        }
    }
```

**Comment by fanninpm** [comment]
See also [`stdlib/src/contextvars.rs`](https://github.com/RustPython/RustPython/blob/main/stdlib/src/contextvars.rs) and #3188.

**Comment by itsankitkp** [comment]
> See also [`stdlib/src/contextvars.rs`](https://github.com/RustPython/RustPython/blob/main/stdlib/src/contextvars.rs) and #3188.

I can see the questions and I believe it is still unsolved? How do you plan to take this forward? 
and this `how RustPython deals with thread safety` 
Anyways, I will be closing this issue as #3188 will fix this.
