### ISSUE TITLE
Context::empty_str to &'static PyStrInterned

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4869]
Search for `pub empty_str: PyRef<PyStr>,` to find the definition.

it is currently a `PyRef<PyStr>`, but can be an interned string.

**Comment by itsankitkp** [comment]
I am new to internals of rustpython-vm, can you please let me know (or refer relevant doc, if any) what does interned string means and why is it better?

**Comment by youknowone** [comment]
will this be helpful? https://docs.python.org/3/library/sys.html#sys.intern

**Comment by itsankitkp** [comment]
Thanks, got it.
