### ISSUE TITLE
RustPython becomes silent if raising an error in trace() function

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4906]
RustPython becomes silent if an error is raised in trace() function. The following example can normally print things on CPython while it fails on RustPython. 

```
import sys
def trace(frame, event, arg):
    raise NameError
    return trace

sys.settrace(trace)
print("fail here")
try:
    a = 1/0
except:
    print("not allowed")
```

Output on RustPython --- silent

Output on CPython (Expected):
fail here
not allowed

Environment 
Ubuntu 18.04
RustPython 0.2.0
CPython 3.11.3

**Comment by DimitrisJim** [comment]
I *think* this should be an easy fix. The [docs](https://docs.python.org/3/library/sys.html#sys.settrace) for `settrace` state:

> If there is any error occurred in the trace function, it will be unset, just like settrace(None) is called.

looking at the way CPython currently behaves, it seems like the Exception is ignored, the trace function is set to nothing and execution continues as it would. In our case, every time a call is made (not only printing, _any_ call) the `trace` function is called:

https://github.com/RustPython/RustPython/blob/fa790558211ec690541299258f44d7453501958a/vm/src/protocol/callable.rs#L48-L54

and this will eventually call the trace function which will return an `Err` and end execution early:

https://github.com/RustPython/RustPython/blob/fa790558211ec690541299258f44d7453501958a/vm/src/protocol/callable.rs#L101-L106

so, the `res` over here shouldn't be propagated, instead, it should be matched on and if it is an `Err` the trace function should be set to `None`. Similarly for the `profile_func` (I'd assume, I haven't checked the docs).

**Comment by matthew-hagemann** [comment]
I see in the docs for profile it does mention:
> Error in the profile function will cause itself unset.

I'll add in the match and create a PR
