### ISSUE TITLE
Undefined variables shouldn't be deleted in the function scope

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4910]
See the following example, l and a are two uninitialized variables in function f(). They should be accessible to 'del' method. The output of test.py on RustPython is "ss". The expected output should be an UnboundLocalError.

test.py
```
def f():
	del l
	del a
l = "ss"
f()
print(l)
```

Expected behavior (CPython 3.11): 
```
Traceback (most recent call last):
  File "/home/xxm/Desktop/RustPython/test.py", line 579, in <module>
    f()
  File "/home/xxm/Desktop/RustPython/test.py", line 576, in f
    del l
        ^
UnboundLocalError: cannot access local variable 'l' where it is not associated with a value
```

Actual output(RustPython):
`"ss"`

Environment:
Ubuntu 18.04
RustPython 0.2.0
CPython 3.11.3

**Comment by youknowone** [comment]
wow... we have so many scope bugs.
