### ISSUE TITLE
Add venv PIP test to CI

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4911]
#4904 

I remember it worked once ensurepip is added first time. But broken. This is regression. Adding a job in CI will prevent it.

**Comment by itsankitkp** [comment]
> #4904
> 
> I remember it worked once ensurepip is added first time. But broken. This is regression. Adding a job in CI will prevent it.

What is correct steps to get pip working in venv? (notwithstanding current regression)
Is it same as steps mentioned in #4904 ?

**Comment by youknowone** [comment]
Very similar in concept, but details different.

```shell
cargo build --release --features=ssl  # jit is not used
./target/release/rustpython -m ensurepip
./target/release/rustpython -m venv testvenv
```

And try1
```shell
. ./testvenv/bin/activate
python -m pip
```
resulted
```
/Users/user/Projects/RustPython/testvenv/bin/python: No module named pip
```

Try 2
``` 
./testvenv/bin/pip
```

resulted
```
Traceback (most recent call last):
  File "./testvenv/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```
Not sure if try 2 worked, but at least try 1 worked.

**Comment by itsankitkp** [comment]
In rustvenv
```
>>> import sys
>>> sys.path
['/tmp', '/home/ankit/RustPython/pylib/Lib', '/tmp/venv/lib/python3.11/site-packages']
```
1. /tmp/venv/lib/python3.11 is empty
2. /tmp/venv/lib/rustrustpython3.11 exists but it is not in syspath. Also, notice rust two times.
3. /tmp/venv/lib/rustrustpython3.11 contains site-packages (as required).
4. If we move site packages from rustrustpython3.11 to python3.11 things work.
5. If if we add rustrustpython to syspath, things work as well (both above methods)
```
>>> import sys
>>> sys.path
['/home/ankit', '/home/ankit/RustPython/pylib/Lib', '/tmp/venv/lib/python3.11/site-packages']
>>> sys.path.append('/tmp/venv/lib/rustrustpython3.11/site-packages')
>>> import pip

```
@youknowone

**Comment by youknowone** [comment]
Thank you! It seems we need to remove the redundant `rust` prefix

**Comment by itsankitkp** [comment]
Yes, found the issue and added a fix in https://github.com/RustPython/RustPython/pull/4924
