### ISSUE TITLE
{:d} format should support bool value.

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4939]
{:d} format is supported to pass a boolean value. See the following test case. CPython can execute it and return expected result, while RustPython report a TypeError.

```
for i in range(12):
    print('{:d}, '.format(chr(i) in "ss"), end='')
    if i % 16 == 1:
        print()
```

Behaviors on CPython:
```
0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
```

Behaviors on RustPython
```
Traceback (most recent call last):
  File "/home/xxm/Desktop/RustPython/test.py", line 169, in <module>
    print('{:d}, '.format(chr(i) in "ss"), end='')
TypeError: unsupported format string passed to bool.__format__
```
Ubuntu 18.04
RustPython 0.2.0 [0284059](https://github.com/RustPython/RustPython/commit/02840593bc56ae416ba2646166628f1712d6cf43)
CPython 3.8.0, 3.9.0, 3.11.3

**Comment by fanninpm** [comment]
@JazzGlobal are you interested in trying this one out? I think it's similar to what you contributed recently.

**Comment by JazzGlobal** [comment]
> @JazzGlobal are you interested in trying this one out? I think it's similar to what you contributed recently.

Sure I can take it!

**Comment by JazzGlobal** [comment]
Since #4948 only covered `:d`, we should probably make additional issues to cover the other FormatType options. They would probably be good first issues as well.

**Comment by xiaxinmeng** [comment]
Thanks! I have included additional test cases in order to address the formatting issue in #4950. I hope these new cases will be helpful in resolving the format issue

**Comment by JazzGlobal** [comment]
Thank you!
