### ISSUE TITLE
break allowed outside of loops

### ISSUE THREAD

**Issue by OddCoincidence** [RustPython/RustPython#497]
The following should be a syntax error, but is allowed and causes a panic at runtime:

```python
def illegal_break():
     break
```

**Comment by coolreader18** [comment]
Can this be closed now?

**Comment by OddCoincidence** [comment]
There are a few more edge cases not covered by the fix. Also a similar problem exists for `yield` and `return` being allowed outside of functions.

**Comment by AaronRocinante** [comment]
`yield` can exist outside of loops, in which case the function will just yield the generator with one element.

**Comment by AaronRocinante** [comment]
The current fix probably cannot handle breaks in nested loops, because having only a boolean indicator `in_loop` is not enough to keep track of the nesting. For example, 
```
def f():
    a = 3
    while a:
        for i in range(10):
            print(a, i)
            if i == 2:
                break
        a -= 1
        if a == 1:
            break
```
The `self.in_loop` will be reset to `false` at the end of the for loop, but we will still be inside the `while` loop.

**Comment by OddCoincidence** [comment]
Yeah, this is the edge case I was alluding to above.

The `in_loop` flag should actually be enough, if instead of setting to false, it just saves and then restores the prior value.

**Comment by AaronRocinante** [comment]
@OddCoincidence please take at the PR #542 for the fix. Thank you~
