### ISSUE TITLE
Unwrap none value error on cargo run --release

### ISSUE THREAD

**Issue by bjoroen** [RustPython/RustPython#4977]
## Summary
Running ```cargo run --release``` gives me an unwrap on None value error.
After pulling the latest commits, I now get this error: 
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /RustPython/compiler/core/src/bytecode.rs:286:27      
````

## Expected

Repl to start 

## Actual
unwrap None value error
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /RustPython/compiler/core/src/bytecode.rs:286:27      
````

**Comment by youknowone** [comment]
Bytecode is recently changed. Removing all `__pycache__` and `*.pyc` will be helpful.

**Comment by bjoroen** [comment]
Cargo clean did work, thanks a lot. 
Sorry for the unnecessary issue, I should have done that before submitting an issue.

**Comment by DimitrisJim** [comment]
> Sorry for the unnecessary issue, I should have done that before submitting an issue.

It's okay, I don't think this is documented anywhere? It's a natural issue to bump into.
