### ISSUE TITLE
Fix broken mac build

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4995]
First broken build: https://github.com/RustPython/RustPython/commit/7a3f965396b725e7fa16c7a10cd06b239f92f167

**Comment by DimitrisJim** [comment]
do we set `RUST_BACKTRACE` in the tests? Might be useful since locally you can't repro so the logs are the only thing we're going with.

**Comment by youknowone** [comment]
By testing from #5008, it came from CI changes, not the code changes.

**Comment by DimitrisJim** [comment]
This still bugs me, the tests on the PR passed, when merged to main they started failing. What CI changes caused this?

**Comment by youknowone** [comment]
No idea at all. I also experienced locally unreproducible error in #4733
I hope to know how can I have exactly same environment to CI macOS
