### ISSUE TITLE
Add `get_int_max_str_digits` and `set_int_max_str_digits` in `sys`.

### ISSUE THREAD

**Issue by DimitrisJim** [RustPython/RustPython#5010]
## Feature

These were newly added in 3.11 and should be relatively straightforward to add, reference: https://docs.python.org/3/library/stdtypes.html#int-max-str-digits

Additions to `int_info` already exist so just the get/set function should be added. (See `PyIntInfo` in [`sys.rs`](https://github.com/RustPython/RustPython/blob/main/vm/src/stdlib/sys.rs)).

**Comment by bobby-palmer** [comment]
It seems like this issue can be closed. Is there more to add with this or is it finished?

**Comment by DimitrisJim** [comment]
Yeah, thanks for noticing! There's some more things to be done for it since it can be set via a command line arg but that should be a separate issue.
