### ISSUE TITLE
`RUSTPYTHONPATH` doesn't automatically set on Windows

### ISSUE THREAD

**Issue by ANVLISTENER** [RustPython/RustPython#5030]

**Comment by ANVLISTENER** [comment]
import os

**Comment by fanninpm** [comment]
What is your platform?

**Comment by ANVLISTENER** [comment]
Windows 11

**Comment by ANVLISTENER** [comment]
Looked like RUSTPYTHONPATH not added automatically.

**Comment by youknowone** [comment]
Yes, we currently have that problem on Windows.

**Comment by youknowone** [comment]
@ANVLISTENER I recently fixed RUSTPYTHONPATH problem on Windows. Could you please test if it works?
