### ISSUE TITLE
Can you put a pure python core library as a built-in library?

### ISSUE THREAD

**Issue by yingshaoxo** [RustPython/RustPython#5039]
https://github.com/micropython/micropython-lib/tree/c113611765278b2fc8dcf8b2f2c3513b35a69b39

**Comment by JamesClarke7283** [comment]
Can you provide more details as to what you want to be done?

Maybe a checklist as well. Would be helpful to anyone attempting.

**Comment by yingshaoxo** [comment]
Never mind, I just found a big bug about a lot of c_based programming language. They strongly rely on c but c compiler is not very open. Or the CPU structure is not open, I can't even found cput structure documentation online.

By the way, rust uses too much storage as a compiler. And it is not noly rely on c but also c++, which makes it bigger.
