### ISSUE TITLE
[RFC] A fake module from source API (mostly for wasm targets)

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#5041]
## Summary

Provides an API `VirtualMachine::compile_module` that creates a Python module from source code.

## Detailed Explanation
We can use `vm.compile` and `builtins.exec` to provide dynamic libraries without system IO.

Below is not actual code, but it shows the general flow.
```rust
let scope = rustpython_vm::scope::Scope::with_builtins(None, vm.new_dict());
let code = vm.compile(<source text>, "<source>", Mode::Exec); // compiled code
vm.run_code_obj(code_obj, scope);
// now `scope` contains module attributes
let module = PyModule::new();
for (name, value) in scope.locals {
    module.set_attr(name, value);
}
```

We can package these complex procedures into a single function.

The WASM architecture limits the use of Python modules due to access to system io.
Currently, the only way to use Python modules in WASM is to freeze them at compile time.
This API is not only limited to WASM, but will be very useful for WASM.

## Drawbacks, Rationale, and Alternatives

- Better API name or space? I didn't consider putting `import` in the name, like `vm.import_from_source`, because in Python, `import` implies complex filesystem usage via `importlib`.

**Comment by youknowone** [comment]
@DimitrisJim @coolreader18 Do you have advices?

**Comment by coolreader18** [comment]
Not relevant to naming, but I thought the standard procedure was to make the scope's locals be the actual dict of the module itself?

**Comment by coolreader18** [comment]
Ok, I thought there was some sort of function like this already, found it:

https://github.com/RustPython/RustPython/blob/bdb0c8f64557e0822f0bcfd63defbad54625c17a/wasm/lib/src/vm_class.rs#L274-L309

**Comment by coolreader18** [comment]
Not totally sure if that's the right naming, but it's prior art at least. Though inject_module does feel good I think, inject isn't overloaded with much in Python so that could be a good choice

**Comment by coolreader18** [comment]
Oh though maybe your proposal wouldn't add it to sys.modules? That feels like the actual "injection" in that operation

**Comment by youknowone** [comment]
Thank you! `inject_module` looks really good reference. I thought that approach cannot prevent user to put mismatching source code with the same name. But wasm may really need it.

**Comment by lattice0** [comment]
Yes. Context: we can have python sources with custom functions and call them with arguments, instead of running them. Currently we have to import the python source file. Some applications wouldn't want or even have permission to write to files.
