### ISSUE TITLE
Importing modules not working with WASI

### ISSUE THREAD

**Issue by d3lm** [RustPython/RustPython#5058]
I tried to import a module that's just next to another module, e.g.

```
main.py
utils.py
```

If I try to import `utils` in `main.py`

```
import utils

utils.sayHello()
```

it fails and says

```
ModuleNotFoundError: No module named 'utils'
```

Any idea why that is not working?

**Comment by d3lm** [comment]
@youknowone Any idea what the issue could be? Is it maybe that paths are not correctly resolved when compiled to WASI?

**Comment by youknowone** [comment]
Hmm. I confirmed `open('f.py')` works but `import f` doesn't work.

**Comment by youknowone** [comment]
@d3lm I am still not used to be developing on wasm/wasi. Do you have recommendation for debuggers setup?

**Comment by d3lm** [comment]
Interesting. Here I think there's something going on with maybe path resolution but I am not entirely sure. Debugging is a little difficult with Rust because AFAIK dwarf symbols don't fully work with Rust. So the best is to add logs which is quite tedious 😑 😅 I ll have a look. Can you point me to the right places where module resolution happens?

**Comment by youknowone** [comment]
It revealed as configuration problem to me.
Could you test it with additional feature `encodings`? It probably will be fixed.

**Comment by d3lm** [comment]
Oh awesome!!! Thanks so much for looking at it. How did you find it out? Will verify tomorrow morning 🙏

**Comment by youknowone** [comment]
`latin-1` is very important encoding and implemented in rust, but it had kept error about it. it was just.. weird 😅

**Comment by d3lm** [comment]
Yay, I just confirmed it now works! Thanks a lot 🙏
