### ISSUE TITLE
Add rustpython to arewepythonyet

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#508]
http://arewepythonyet.com/

This website currently lacks a rustpython option. This should be fixed asap :).

**Comment by dralley** [comment]
Page is dead :(

Close issue?

**Comment by coolreader18** [comment]
That sucks, @windelbouwman should we close this?

**Comment by windelbouwman** [comment]
Agreed, let's close this issue for now. We can re-open / create a new issue later.
