### ISSUE TITLE
The REPL should an exit() function

### ISSUE THREAD

**Issue by AdamGS** [RustPython/RustPython#509]
Any version of the python REPL has an exit() function (in addition to CTRL+C/D), which is just comfortable and keeps basic compatibility with other REPL implementations.

**Comment by matrizx** [comment]
I'll give it a go.

**Comment by youknowone** [comment]
CPython has a `Quitter` object in `Lib/_sitebuiltins.py`. Once RustPython starts to import CPython Libs, creating a `Quitter` object in __builtin__ will work just as CPython.

**Comment by windelbouwman** [comment]
@AdamGS could you recheck? This was recently implemented. If this works as expected, we can close this issue.

**Comment by 0jdxt** [comment]
@windelbouwman as far as I can tell `exit()` works in the REPL.
