### ISSUE TITLE
None.__ne__(None) behavior is changed in 3.12

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#5103]
Related test:  https://github.com/youknowone/RustPython/blob/6e699d93fe9ed1f16921ef3ab4a83fc0a72c5473/extra_tests/snippets/builtin_none.py#L25

**Comment by evanrittenhouse** [comment]
Feel free to assign this one to me

**Comment by evanrittenhouse** [comment]
Just want to check - is there  a way to run this test outside of installing Python 3.12 on my system and running `python3 builtin_none.py`? Doesn't look like it's in a test class, so PyTest can't pick it up.

**Comment by fanninpm** [comment]
> installing Python 3.12 on my system

You can use `pyenv` or `conda` to install a newer version of Python than the one that's on your system.

That `builtin_none.py` should be fine as one of the `extra_tests`.

**Comment by youknowone** [comment]
Even though the test is working under pytest, you sill need to install Python 3.12 to test with it.

Steps:
1. Change test to the new behavior (you need Python 3.12 here)
2. Fix RustPython to work like the new one. (See vm/src/builtins/singleton.rs)

**Comment by evanrittenhouse** [comment]
So I've been looking at this for a while now - I think that it ends up requiring a change [here](https://github.com/RustPython/RustPython/blob/8fc2c39d62d230f53ed701395612c3168a4464be/vm/src/builtins/object.rs#L100), but I'm not sure how to get the `richcompare` slot to resolve to `NotImplemented` for `None`. Any tips?

**Comment by youknowone** [comment]
PyNone is here: https://github.com/RustPython/RustPython/blob/8fc2c39d62d230f53ed701395612c3168a4464be/vm/src/builtins/singletons.rs#L12

You can implement `Comparable` for `PyNone` like other types. e.g. https://github.com/RustPython/RustPython/blob/8fc2c39d62d230f53ed701395612c3168a4464be/vm/src/builtins/range.rs#L441-L468

**Comment by evanrittenhouse** [comment]
Ah got it, thanks for the pointer. Hadn't seen the `Comparable` trait, I'll keep that in mind for future issues.
