### ISSUE TITLE
Mismatching abstractmethod error messages

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#5137]
Python 3.12 changed error messages.

https://github.com/RustPython/RustPython/pull/5134/files#diff-e020d5ddd536ec48b0414753af7d5240750a05262f32dad378b4c79e6cc3743dR152-R160 (#5134)

Related source code in RustPython is in `vm/src/builtins/object.rs`.

**Comment by youknowone** [comment]
@NakanoMiku39 Are you interested in this issue?

**Comment by NakanoMiku39** [comment]
> itle ~Fix abstractmethod error messages~ Mismatching abstractmethod

Yeah Sure
