### ISSUE TITLE
sys.flags.int_max_str_digits is not -1

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#5139]
## Summary

sys.flags.int_max_str_digits now returns sys.get_int_max_str_digits().

Introduced from https://github.com/RustPython/RustPython/pull/5127/files#diff-128fff16ea63b541718887f5c714e0c1a357414fe1146b4893ef699e8853e3b0R953

Related RustPython code is `vm/src/stdlib.sys.rs`  `Flags::int_max_str_digits`.

Not sure yet if we need to change the value of Settings or sys::Flags.

**Comment by itsankitkp** [comment]
Is this fixed now?
in rustpython (317f4494)
sys.flags.int_max_str_digits returns -1
sys.get_int_max_str_digits() returns 4300
in cpython 3.11.6
same results as above.

Also, worked fine with `-X int_max_str_digits` flag

**Comment by fanninpm** [comment]
> in cpython 3.11.6

Have you tried CPython 3.12?

**Comment by itsankitkp** [comment]
> > in cpython 3.11.6
> 
> Have you tried CPython 3.12?

Tried latest cpython (3.13 dev version)
both sys.flags.int_max_str_digits and sys.get_int_max_str_digits() returns 4300
its coming from here: https://github.com/python/cpython/pull/96499
