### ISSUE TITLE
Make vm.import_from_str() so we can import string python programs as modules

### ISSUE THREAD

**Issue by lattice0** [RustPython/RustPython#5177]
## Summary

Make an option to `vm.import_from_str()`. Currently, `vm.import` expects us to have a file path, and thus the python file needs to be somewhere in the system or maybe in a virtual file system. For some cases the python file could come as a string. I know that the mini repl allows us to run runtime generated python code, but there's no way to **turn a string python program into a module inside the VM** so I can then get the function attribute and call it with arguments.

https://github.com/RustPython/RustPython/discussions/5173 is what I tried to do

## Expected use case

Run python programs generated at runtime, but also be able to get its attributes like functions and call them with arguments. Currently we can only compile a string and run it, no way to turn it into a module on the VM

**Comment by youknowone** [comment]
#5214 added a similar feature

**Comment by youknowone** [comment]
#5214 added a similar feature. Thank you for suggestion!
