### ISSUE TITLE
UTF8 encoding messy code

### ISSUE THREAD

**Issue by xiaoxstz** [RustPython/RustPython#5193]
## Summary

It does not support utf-8 encoding yet?

## Expected

When running scripts with Chinese strings, it would come across messy code issues.

For example, the script below.

```python
print("测试中文")
```

```python
# coding=utf-8
print("测试中文")
```

The output is:
> 娴嬭瘯涓枃

**Comment by youknowone** [comment]
RustPython (almost) *only* support utf-8 and ascii. Would you check if your source code is a correct utf-8 file?

```python
Welcome to the magnificent Rust Python 0.3.0 interpreter 😱 🖖
RustPython 3.12.0
Type "help", "copyright", "credits" or "license" for more information.
>>>>> print("测试中文")
测试中文
>>>>> 
```
```sh
❯ ./target/debug/rustpython test_utf8_zh.py
测试中文
```

**Comment by xiaoxstz** [comment]
# My Environment

* OS：`Windows 10 pro 22H2`
* How to install `RustPython`

```Shell
# Install rust
scoop install main/rust
# Install the latest RustPython
cargo install --git https://github.com/RustPython/RustPython
```

## File encoding
I have ensured the encoding of the Python script file is utf8

![Encoding-vscode](https://github.com/RustPython/RustPython/assets/81862747/e2ba902c-3072-45bb-a80a-6f670a93d3bd)

## Other related issue

I have also found the issue in the interactive panel

```Shell
D:\Desktop                                                             
λ RustPython                                                           
Welcome to the magnificent Rust Python 0.3.0 interpreter � �           
RustPython 3.12.0                                                      
Type "help", "copyright", "credits" or "license" for more information. 
>>>>> print("测试中文")                                                    
娴嬭瘯涓枃                                                                 
>>>>>                                                                  
```

**Comment by joshua-mdp** [comment]
Maybe the codepage is set to something else?

**Comment by youknowone** [comment]
Could you upload your `test.py` file here? You can drag-and-drop the zipped source code to the comment box.

**Comment by ghuls** [comment]
Maybe your terminal is interpreting the printed bytes as UTF-16 instead of UTF-8.

```python
In [12]: "测试中文".encode("utf-8")
Out[12]: b'\xe6\xb5\x8b\xe8\xaf\x95\xe4\xb8\xad\xe6\x96\x87'
```

**Comment by kawogi** [comment]
What happens if you execute a simple Rust program printing "测试中文"?

**Comment by barraponto** [comment]
btw, what is the output of `locale` in your terminal?

**Comment by youknowone** [comment]
It doesn't seem like a bug and the original author doesn't response.

Please feel free to reopen it if the problem is not solved.

Thank you everyone for helping!

**Comment by xiaoxstz** [comment]
> Maybe your terminal is interpreting the printed bytes as UTF-16 instead of UTF-8.
> 
> ```python
> In [12]: "测试中文".encode("utf-8")
> Out[12]: b'\xe6\xb5\x8b\xe8\xaf\x95\xe4\xb8\xad\xe6\x96\x87'
> ```

Yes. The result is the same.

**Comment by xiaoxstz** [comment]
> btw, what is the output of `locale` in your terminal?

I run the command `systeminfo` and get the result below:

```txt
System Locale:             zh-cn;Chinese (China)
Input Locale:              en-us;English (United States)
```

**Comment by xiaoxstz** [comment]
> Could you upload your `test.py` file here? You can drag-and-drop the zipped source code to the comment box.
[test.zip](https://github.com/user-attachments/files/17227642/test.zip)

**Comment by xiaoxstz** [comment]
I have fixed it by changing the locale of my terminal (PowerShell).

The result of the commands:

* `$OutputEncoding`: The value is `Unicode (UTF-8)`. It is used to output to other programs.
* `[Console]::OutputEncoding`: The value is `Chinese Simplified (GB2312)`. It is used to display to the terminal.
* `[Console]::InputEncoding`: The value is `Chinese Simplified (GB2312)`. It is used to input to the terminal.

So, the issue is clear now. `[Console]::OutputEncoding`  and `[Console]::InputEncoding` are set uncorrectly.

```PowerShell
[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding
[Console]::InputEncoding = New-Object System.Text.UTF8Encoding
```
