### ISSUE TITLE
Attempting to run WASI example in readme

### ISSUE THREAD

**Issue by Densaugeo** [RustPython/RustPython#5283]
## Summary

The WASI example in the readme appears to be incomplete. Following the instructions produces a .wasm file, but running it does not work.

## Details

The build command works as expected and a .wasm is produced. However, running the wasmer command gives this error:

```
$ wasmer run --dir . target/wasm32-wasi/release/rustpython.wasm extra_tests/snippets/stdlib_time.py 
[ERROR rustpython_vm::vm::compile] Failed reading file 'extra_tests/snippets/stdlib_random.py': No such file or directory (os error 44)
```

I have confirmed that `stdlib_random.py` does exist. Backspacing part of the file name and hitting tab causes it to autocomplete, so it's definitely spelled correctly. The file permissions also appear correct, and using sudo has no effect.

I am building with cargo 1.77.2 (installed by rustup) on Fedora 39.

**Comment by youknowone** [comment]
Hi, wasmer behavior seems to be changed. I recently used this comment:
```shell
$ wasmer run --dir `pwd` -- target/wasm32-wasi/release/rustpython.wasm `pwd`/extra_tests/snippets/stdlib_random.py
```

**Comment by Densaugeo** [comment]
Thanks! New example works for me.
