### ISSUE TITLE
Testing WebAssembly

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#530]
There are a few questions if we were to write tests for the WASM library:

- What "framework" to use?:
  - I saw @windelbouwman mention https://wasmer.io in the Gitter chat.
  - wasm-bindgen also has it's own [testing system](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/index.html), which supports testing in headless browsers through WebDrivers.
- How would it integrate with CodeCov? Is it possible to integrate it with CodeCov?

**Comment by windelbouwman** [comment]
It might be good to build the wasm module, and call a few functions using `wasmer-runtime`. I did some tests here: https://github.com/windelbouwman/pzn/blob/master/pzn/src/main.rs#L140

On the other hand, a headless browser like phantomjs might be good to check browser integration.

**Comment by windelbouwman** [comment]
@coolreader18 can this issue be closed now? We have wasm tests. Or is this a discussion? Then we should label it as question.

**Comment by coolreader18** [comment]
Yeah, I guess so.
