### ISSUE TITLE
Build fails on i386: error[E0412]: cannot find type `u512` in this scope

### ISSUE THREAD

**Issue by yurivict** [RustPython/RustPython#5318]
## Summary

```
error[E0412]: cannot find type `u512` in this scope
     --> /wrkdirs/usr/ports/lang/rustpython/work/target/release/build/unicode_names2-fc074b82fe4b3d20/out/generated.rs:13939:43
      |
13939 | pub static PHRASEBOOK_OFFSETS2: &'static [u512] = &[
      |                                           ^^^^ not found in this scope

```

unicode_names2's last release is 1.2.2, but some other tag  is used, which might be a cause of this problem.

[log](https://pkg-status.freebsd.org/beefy15/data/132i386-default/fbd796535d84/logs/rustpython-0.3.1.log)

rust-1.77.0
FreeBSD 13.2

**Comment by youknowone** [comment]
Rust target used in the log is `i686-unknown-freebsd`.
I tried to build both unicode_names2 master and RustPython main with the target, RustPython main + unicdoe_names2 1.2.2 with the target, but not reproducible.
How do I reproduce the problem?
