### ISSUE TITLE
Can rustpython use pip to download libraries that rely on C extensions?

### ISSUE THREAD

**Issue by carrt123** [RustPython/RustPython#5335]
Can rustpython use pip to download libraries that rely on C extensions?
I encountered the error"ModuleNotFoundError: No module named '_ctypes'when downloading some libraries that rely on C extensions. For example, download: ujson, markupsafe.
but, those libraries written by pure cpython I can download normally.

**Comment by youknowone** [comment]
No, not yet.
But ctypes issue and c extension support is a bit different issue.

ctypes: #1217 #2364

implementing ctypes itself doesn't guarantee C extension compatibiltity.

**Comment by carrt123** [comment]
thank you.
