### ISSUE TITLE
Get Attributes Dynamically

### ISSUE THREAD

**Issue by Luzzotica** [RustPython/RustPython#5353]
## Summary

Right now, the `get_attr` function requires a `'static` reference to a `&str` value.

I would like to be able to dynamically check for attributes at run time (such as functions on a loaded module) and call them, but currently this seems to be impossible.

## Expected use case

Dynamically get attributes without needing a static reference to the attribute name.

I'll also mention: I am new to Rust, so maybe there is a way to specify (elide?) the lifetime of the `&str` value I am passing. But right now I can't get around the requirement that it is static.

**Comment by youknowone** [comment]
`PyObject::get_attr` requires `impl AsPyStr<'a>`. Which can be either `&'static str` or `PyStr`.
To pass a dynamic value, create a PyStr first.

```rust
let attr_name = vm.ctx.new_str(some_dynamic_str);
let attr = obj.get_attr(attr_name)?;
```

**Comment by Luzzotica** [comment]
I had just discovered this when you posted about it. Thank you so so much for the response!
