### ISSUE TITLE
Make PyFunction.name() public

### ISSUE THREAD

**Issue by rockstar** [RustPython/RustPython#5357]
## Summary

Consider the following code:

```
def my_callback(arg1, arg2):
    print("hello world")

def my_setup_call(my_rust_class):
    my_rust_class.call_every(my_callback, 30)
```

`call_every_second` would take a `PyFunction`. We may want to tear down the interpreter and wait 30 seconds before we call that callback, fire up a new interpreter, get the function out of the module, and call it with arguments. Unfortunately, `PyFunction.name()` is private. It should be accessible so that we can find the symbol again in another environment.

**Comment by youknowone** [comment]
For python types, most of python-accessible fields are private.
Are you sure your callback always is a `PyFunction` type but never other types of callable like a class(PyType) or  builtin function(PyNativeFunction)?
If there is a chance, calling `let name = func_obj.get_attr("__name__", vm)` might be better idea.

**Comment by rockstar** [comment]
Using `.get_attr("__name__")` ended up being an acceptable api. Thanks for the response!
