### ISSUE TITLE
This calculation of fib(35) was too slow and took more than 13s

### ISSUE THREAD

**Issue by deliangyang** [RustPython/RustPython#5421]
## Summary

This calculation of fib(35) was too slow and took more than 13s

## Details

```
time cargo run --release /home/x/fab2.py
9227465

real	0m13.884s
user	0m13.373s
sys	0m0.175s
```
x@x-ubuntu:/home/x/RustPython$ cat /home/x/fab2.py
```python
def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)

print(fib(35))
```

**Comment by coolreader18** [comment]
On my machine I get
```
python  0.87s user 0.00s system 99% cpu 0.877 total
rustpython  9.50s user 0.01s system 99% cpu 9.566 total
```
Which is more or less in the expected range of RustPython being 10x slower than CPython. Given we have benchmarks in the repo that show this same result, I'm going to close this for now.
