### ISSUE TITLE
Difference between _string.formatter_parser in cpython and rustpython

### ISSUE THREAD

**Issue by kaanyalova** [RustPython/RustPython#5427]
The outputs of this script are different between rustpython and cpython
```py
import _string

format_string = "{title[:220]}"


for literal_text, field_name, format_spec, conv in _string.formatter_parser(
    format_string
):
    print(
        f"literal_text: '{literal_text}' field_name: '{field_name}, format_spec: '{format_spec}, conv: {conv}'"
    )
```

cpython prints correctly:
```
literal_text: '' field_name: 'title[:220], format_spec: ', conv: None'
```

while rustpython prints:
```
literal_text: '' field_name: 'title[, format_spec: '220], conv: None'
```

this seems to cause issues when using [gallery_dl](https://github.com/mikf/gallery-dl) as this is used for formatting file names in  [some extractors](https://github.com/mikf/gallery-dl/blob/061b27f32990d6fdce76455f3d60808d3e07e861/gallery_dl/extractor/reddit.py#L20)

**Comment by youknowone** [comment]
Thank you for the report.

`FormatString::parse_spec` which is in our https://github.com/RustPython/Parser repository seems to have a bug.
