### ISSUE TITLE
Support cargo-web

### ISSUE THREAD

**Issue by rickyhan** [RustPython/RustPython#543]
Fairly certain it's a bug with cargo-web but just in case anyone has encountered this I'll crosspost the issue here:

https://github.com/koute/cargo-web/issues/175

**Comment by coolreader18** [comment]
I think the reason for this is koute/cargo-web#92, i.e. wasm-bindgen (what RustPython uses for WASM interop) is not compatible with cargo-web (what you're using). If possible, I'd suggest switching your project to use wasm-bindgen/[wasm-pack](https://github.com/rustwasm/wasm-pack/).

**Comment by rickyhan** [comment]
I understand the concern but a crate I'm using depends on cargo-web.
