### ISSUE TITLE
Boolean methods cause interpreter panic when presented with the wrong type

### ISSUE THREAD

**Issue by Masterchef365** [RustPython/RustPython#5460]
## Summary
You can cause the latest version of the interpreter ([01f7536](https://github.com/RustPython/RustPython/commit/01f7536b36a94b1ab479253b8227c5151136bfff)) to panic with:
```
thread 'main' panicked at [...]rustpython-vm/src/builtins/bool.rs:212:28:
called `Option::unwrap()` on a `None` value
```
By running the following (invalid) code:
```python
x = min # Some type which isn't a boolean
x |= True # Perform a boolean operation
```
## Expected
I was hoping for an exception to be thrown, which I could possibly catch! Python 3 does this.

## Actual
Panics, see above

## Python Documentation
[TypeError exception](https://docs.python.org/3/library/exceptions.html#TypeError)

**Comment by theshubhamp** [comment]
Looks like the or, and & xor operators implemented in bool builtin were missing type check to int.

Sent a PR including tests.
