### ISSUE TITLE
panic with left shift

### ISSUE THREAD

**Issue by andrew-ld** [RustPython/RustPython#556]
```
n = 1
while True:
 n = n << 10 ** 100
```
**expected result:** 
> OverflowError: too many digits in integer

**current result:**
> thread 'main' panicked at 'Failed converting 10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 to rust usize', vm/src/obj/objint.rs:250:13

**Comment by windelbouwman** [comment]
Hello @andrew-ld , thank you for filing this issue. This is a very good confined issue, ideal for people starting to contribute to this project.

**Comment by holygits** [comment]
Related #276

**Comment by andrew-ld** [comment]
#564  has solved the problem, I close.
