### ISSUE TITLE
io module gets initialized multiple times when opening files

### ISSUE THREAD

**Issue by silmeth** [RustPython/RustPython#557]
When experimenting with file IO, I found out that when opening a file, one *always* initializes the `io` module from scratch (and then, when importing it, one initializes it exactly once, no matter how many times it’s been already initialized), making checking if objects are instances of given classes from that module impossible, as those classes are represented by different memory objects, eg.:

```
>>>>> file = open('/tmp/tst')
>>>>> file.buffer
<BufferedReader object at 0x55658e5c30e0>
>>>>> type(file.buffer)
<class 'BufferedReader'>
>>>>> import io
>>>>> io.BufferedReader
<class 'BufferedReader'>
>>>>> type(file.buffer) is io.BufferedReader
False
>>>>> type(file.buffer) == io.BufferedReader
False
>>>>> from io import BufferedReader  # subsequent imports from the module do not cause that
>>>>> BufferedReader is io.BufferedReader
True
>>>>> id(type(file.buffer))
93894668449408
>>>>> id(BufferedReader)
93894668474000
```

It seems this is the only module affected by this behaviour (all the other `mk_module(&ctx)` functions are afaik used only in the `module_inits` hash map used for import initialization).

**Comment by coolreader18** [comment]
You're on the right track with your fix, and that should fix the issue short-term, but I think the better solution would be to keep a `HashMap`  of stdlib modules that have already been initialized in the VM, next to the `stdlib_inits`  `HashMap` .

**Comment by silmeth** [comment]
It already kinda is in the `sys.modules` attribute, look at the [`import::import_module()`](https://github.com/RustPython/RustPython/blob/master/vm/src/import.rs#L52-L65) function, it first checks the `sys.module` attribute for the initialized module, only if it fails, it calls into [`import::import_uncached_module()`](https://github.com/RustPython/RustPython/blob/master/vm/src/import.rs#L14-L50) which initializes the module and returns.

The problem, as far as I can tell, was that any module should only be initialized by the import, never manually in any stdlib function.

**Comment by coolreader18** [comment]
Or better yet, held in the same HashMap with a 
`(StdlibInitFunc, Option<PyObjectRef>)` as the value

**Comment by coolreader18** [comment]
Alright, that's valid. I thought it was done that way to prevent someone from replacing a built-in module through `sys.modules`, but I just tried it in CPython and it works. So, yes, put a loaded built-in module into `sys.modules`.
