### ISSUE TITLE
Tracking issue for os module

### ISSUE THREAD

**Issue by rickyhan** [RustPython/RustPython#567]
https://docs.python.org/3/library/os.html

**Comment by dralley** [comment]
What's the story here?  I see source code for the OS module but I can't import it.

```
===== MODULES =====
Traceback (most recent call last):
  File "tests/snippets/whats_left_modules.py", line 8, in <module>
    import os
ModuleNotFoundError: No module named 'os'
```

**Comment by coolreader18** [comment]
Have you set your `RUSTPYTHONPATH` environment variable to `.../RustPython/Lib`? Other than that, `os` is fairly compatible I don't think an issue to track the whole module is necessary anymore.

**Comment by dralley** [comment]
I have not, I somehow missed that part of the readme.  Thanks!
