### ISSUE TITLE
Current sorting algorithm isn't stable

### ISSUE THREAD

**Issue by adrian17** [RustPython/RustPython#578]
Kinda missed that in #559. The algorithm needs to be changed to something stable.

**Comment by evilpie** [comment]
I think Python famously uses [Timsort](https://en.wikipedia.org/wiki/Timsort), so that sort algorithm should probably be used.

**Comment by OddCoincidence** [comment]
I don't think the particular sorting algorithm matters as long as it produces a stable sort and has roughly similar performance characteristics to python's. I wonder if we could get rust to add a `try_sort_by` method to slices so that we could just use the algo from `std`.

**Comment by dralley** [comment]
Rust uses a sorting algorithm that is basically a variation of Timsort.

https://doc.rust-lang.org/std/primitive.slice.html#method.sort

**Comment by youknowone** [comment]
#1072
