### ISSUE TITLE
Create converters from cpython bytecode

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#6]
We need converters from cpython's bytecode into rustpython bytecode. The sourcefile can be found in `py_code_object/src/convert.rs`. The idea is to take cpython bytecode (which differs per cpython version) and convert it into rustpython bytecode.

**Comment by thomasballinger** [comment]
In case it affects how this gets implemented, what's the purpose of this bytecode converter? Is this for testing RustPython bytecode generation? For swapping in the cpython bytecode compiler? Because we want to implement the full bytecode before a full parser/compiler is finished?

**Comment by coolreader18** [comment]
This is an old issue, and we're not as focused on a bytecode translator anymore. I can't speak to why this was originally needed (@windelbouwman?), but it's now more on the back burner and we do have a full parser/compiler/vm.

**Comment by windelbouwman** [comment]
I think we can close this issue. We do not need it anymore, since we now have own bytecode and parser.
