### ISSUE TITLE
Fail to build project

### ISSUE THREAD

**Issue by lili668668** [RustPython/RustPython#620]
I try to clone this project and build the master branch code.
Then there is an error:

```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
   --> vm/src/frame.rs:660:21
    |
3   | use self::rustpython_parser::ast;
    |     ---------------------------- not an extern crate passed with `--extern`
...
660 |                 use ast::ConversionFlag::*;
    |                     ^^^
    |
    = help: add #![feature(uniform_paths)] to the crate attributes to enable
note: this import refers to the module imported here
   --> vm/src/frame.rs:3:5
    |
3   | use self::rustpython_parser::ast;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `rustpython_vm`.

To learn more, run the command again with --verbose.
```

I try to fix `vm/src/frame.rs` line 660

```diff
- use ast::ConversionFlag::*;
+ use self::rustpython_parser::ast::ConversionFlag::*;
```

Then compile succeed and I can see the "Hello, RustPython!".

I don't know if this is a bug.

**Comment by adrian17** [comment]
Which rustc version are you building on?

**Comment by skinny121** [comment]
I had the same error, updating rust fixed it for me.

**Comment by OddCoincidence** [comment]
We could add a `rust-toolchain` file to prevent others from stumbling over this.

**Comment by lili668668** [comment]
@adrian17 

rustc version is `rustc 1.33.0-nightly (ddab10a69 2018-12-23)`

@skinny121 

I try to update rust version, but it seems to have no effect.

By the way, I am not sure how to update rust. Is it to use `curl https://sh.rustup.rs -sSf | sh` to update rust?

**Comment by lili668668** [comment]
I just found out how to update rust, and compile succeed.

The problem seems that I have not updated.

Thanks, each help.
