### ISSUE TITLE
Possible to restrict parsing to subset of syntax?

### ISSUE THREAD

**Issue by abagshaw** [RustPython/RustPython#663]
For security and performance reasons, if one was to parse untrusted python code with RustPython, is it possible to restrict the allowed syntax to a limited few aspects (i.e. just assignments, simple arithmetic and if/else statements)?

**Comment by adrian17** [comment]
Python standard library has `ast.literal_parse`; there are also external libraries like https://github.com/danthedeckie/simpleeval . Do you mean that, or something more specific?

**Comment by abagshaw** [comment]
Maybe I'm misunderstanding the purpose of this library, but I was hoping that I could pass an option to the RustPython interpreter to restrict the syntax that it will parse (i.e. only accept simple arithmetic and if/else statements).

simpleeval seems a little too stripped down, and _literal\_parse_ seems a little too broad without the option to lock down the accepted syntax more (unless I'm missing something). It also seems a little roundabout and redundant to have python code be interpreted in rust, then `eval`ed after that...

**Comment by coolreader18** [comment]
So you're looking for Python with only control flow and basic arithmetic?

**Comment by abagshaw** [comment]
That's it...and in Rust ideally. 😄 To be honest it might be easier just writing a parser for that purpose if this doesn't already exist.

**Comment by coolreader18** [comment]
That's a pretty interesting idea. If you wan to put time into it, feel free to fork RustPython and gut most of the parser, bytecode, etc. out, just leaving what you're looking for. It'd be easier than starting completely fresh :smile:

**Comment by coolreader18** [comment]
Alternatively, keep the parser, and add error messages for when a Python feature isn't supported. By the way, what are you planning on using this for?

**Comment by abagshaw** [comment]
That might work too. I'm wanting to allow simple scripting for a dynamic math problem generator (i.e. a problem can contain a small python script to populate the problem with random values making it unique).

One of the other things that would make my life easier is https://github.com/RustPython/RustPython/issues/745

**Comment by cthulahoops** [comment]
Another approach might be to do a full parse using ```ast.parse```, and then scan the ast for forbidden elements before executing the code.
