### ISSUE TITLE
Debug implementation changed: Trace output has become a lot less useful.

### ISSUE THREAD

**Issue by cthulahoops** [RustPython/RustPython#664]
Eg.:

TRACE 2019-03-12T10:29:07Z: rustpython_vm::vm: Invoke: [PyObj Any] PyFuncArgs { args: [[PyObj Any], [PyObj Any]], kwargs: [] }
TRACE 2019-03-12T10:29:07Z: rustpython_vm::vm: vm.call_method [PyObj Any] [PyObj Any] "__subclasscheck__" -> [PyObj Any]
TRACE 2019-03-12T10:29:07Z: rustpython_vm::vm: Invoke: [PyObj Any] PyFuncArgs { args: [[PyObj Any], [PyObj Any], [PyObj Any]], kwargs: [] }

**Comment by coolreader18** [comment]
This looks like it came about as a result of #653, where now the payload doesn't have its own debug implementation because it's just `Any`, and for whatever reason it's not properly writing the payload using its own Debug implementation.

**Comment by coolreader18** [comment]
Actually, wait, @OddCoincidence is [`PyObject.payload`](https://github.com/RustPython/RustPython/blob/a8c02105d1085cc73147dd76f32346a8b8989558/vm/src/pyobject.rs#L672) supposed to be a `dyn Any` or a `dyn PyValue`?

**Comment by OddCoincidence** [comment]
Ideally it would be `dyn PyValue`, but it currently cannot be because `PyValue` is not object safe. We may need to split off `required_type` into its own trait.

**Comment by coolreader18** [comment]
We could just add an `&self` parameter to `required_type()`.

**Comment by OddCoincidence** [comment]
The two uses for it are argument type checking and object construction, both of which need to know the required type of the payload _without_ already having in instance (otherwise it'd just use `TypeProtocol`).

**Comment by coolreader18** [comment]
Why do all the fns of a trait have to be methods anyway? Why can't a `dyn Trait` just ignore non-methods?

**Comment by coolreader18** [comment]
I think I'll try defining another trait, maybe `PyValuePayload`, that pretty just reimplements PyValue fns but can be turned into an object.
