### ISSUE TITLE
dict ordering not consistent

### ISSUE THREAD

**Issue by skinny121** [RustPython/RustPython#689]
The ordering of printed elements of a dict, isn't consistent at all. The below code produces different results each run:

```python
for _ in range(10):
    print({'a': 2, 'b': 10})
```
Example output:
```
{'a': 2, 'b': 10}
{'b': 10, 'a': 2}
{'a': 2, 'b': 10}
{'b': 10, 'a': 2}
{'a': 2, 'b': 10}
{'a': 2, 'b': 10}
{'a': 2, 'b': 10}
{'a': 2, 'b': 10}
{'b': 10, 'a': 2}
{'b': 10, 'a': 2}
```
My expectation was that all lines in the outpu would be the same and consistent across runs.

**Comment by jgirardet** [comment]
not relevant for python 3.5.
it's an implementation detail in cpython3.6 but a feature in cpython3.7.

**Comment by cthulahoops** [comment]
That's really surprising behaviour! I like it. If something is allowed to be inconsistent it should be as inconsistent as possible so people don't rely on it.

We have a new dictionary implementation pending which matches the python 3.6 dictionary. Once we have that in this should be resolved.

**Comment by windelbouwman** [comment]
With pull request #780 this should now be resolved. @skinny121 could you confirm this issue is solved, and can be closed?

**Comment by skinny121** [comment]
Yes, it consistently prints the same thing, but in the reverse order than expected. i.e. prints {'b': 10, 'a': 2}. :(

I suspect this is because the BuildMap bytecode instruction uses `self.pop_value()` which means it adds the values to the dict in reverse order. Should it use `self.get_elements(...)` instead? https://github.com/RustPython/RustPython/blob/master/vm/src/frame.rs#L390

**Comment by skinny121** [comment]
I have created a PR, to fix the above minor issue, but good work @cthulahoops and @windelbouwman for implementing proper dict support.
