### ISSUE TITLE
Should bytecode contain PyObjectRef references to constants?

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#70]
It could be argued that bytecode objects may refer to python objects which are immutable, such as tuples, None and integers.

This would mean that the bytecode::Constant enum would disappear:

https://github.com/RustPython/RustPython/blob/master/vm/src/bytecode.rs#L113

This would also mean that the bytecode class becomes depending upon the vm. This might be a downside, so we cannot separate the bytecode package into a seperate package, but on the other hand, I like the idea of referring to PyObjectRef objects straight from bytecode.

This is a voting issue, what do you think?

**Comment by cthulahoops** [comment]
I haven't thought about this a lot, but my first instinct would be not to - assuming that it's a small subset of python types that are valid constants.

Aside from the dependency issue, I'd rather use a more restrictive type and get as much out of the rust static typing as we can. I'd also rather avoid needing a full pycontext to generate bytecode.

**Comment by windelbouwman** [comment]
Closing this issue since we have the `rustpython-bytecode` crate now.
