### ISSUE TITLE
Create a webassembly demo

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#71]
Somehow it should be easy to port rustpython to the web using the wasm backend of rust. We require a sort of manual / script on how to do this and a nice website which is automatically updated with the latest version of rustpython.

**Comment by shinglyu** [comment]
I'm interested in this. Let me give it a try

**Comment by shinglyu** [comment]
@rmliddle I'll build a html page that shows RustPython-wasm running, instead of running in browser console. Also I can try to build a CI pipeline to build and push that to the github-page, so we have something easy for demo. Does these make sense to you?

**Comment by shinglyu** [comment]
As discussed with @windelbouwman , we'll build a travis CI pipeline to build wasm and push the page to https://github.com/RustPython/website

**Comment by shinglyu** [comment]
REPL demo idea from Brython: http://brython.info/tests/console.html
Code editor + stdout demo: http://brython.info/tests/editor.html

**Comment by shinglyu** [comment]
For the editor demo, this is where the python code actually get run: https://github.com/brython-dev/brython/blob/master/www/tests/editor.py#L112
The output are stored in the variable `output` and then flush the to textarea DOM element value.

**Comment by windelbouwman** [comment]
@shinglyu Can this issue be closed?

**Comment by Mec-iS** [comment]
nice job at FOSDEM :+1:
