### ISSUE TITLE
Store VirtualMachines in thead-local/static variables

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#712]
Instead of creating a whole VM, you would create a handle/reference to one. [As discussed on Gitter](https://gitter.im/rustpython/Lobby?at=5c8d1fd38aa66959b61e637e).

**Comment by youknowone** [comment]
I think this suggestion conflicts to subinterpreter suggestion of CPython

**Comment by youknowone** [comment]
#2128
