### ISSUE TITLE
add bytes missing method

### ISSUE THREAD

**Issue by jgirardet** [RustPython/RustPython#736]
A thread to add  missing bytes method :
I'll try to keep it up to date

- [x] `bytes . __add__`
- [x] `bytes . __contains__` 
- [x] `bytes . __getitem__` 
- [ ] `bytes . __getnewargs__` 
- [ ] `bytes . __init_subclass__` 
- [x] `bytes . __mod__` 
- [x] `bytes . __mul__` 
- [x] `bytes . __reduce__` 
- [x] `bytes . __reduce_ex__` 
- [x] `bytes . __rmod__` 
- [x] `bytes . __rmul__` 
- [x] `bytes . __sizeof__` 
- [x] `bytes . __subclasshook__` 
- [x] `bytes . capitalize` 
- [x] `bytes . center` 
- [x] `bytes . count` 
- [x] `bytes . decode` 
- [x] `bytes . endswith` 
- [x] `bytes . expandtabs` 
- [x] `bytes . find` 
- [x] `bytes . fromhex` 
- [x] `bytes . hex` 
- [x] `bytes . index` 
- [x] `bytes . isalnum` 
- [x] `bytes . isalpha` 
- [x] `bytes . isascii` 
- [x] `bytes . isdigit` 
- [x] `bytes . islower` 
- [x] `bytes . isspace` 
- [x] `bytes . istitle` 
- [x] `bytes . isupper` 
- [x] `bytes . join` 
- [x] `bytes . ljust` 
- [x] `bytes . lower` 
- [x] `bytes . lstrip` 
- [x] `bytes . maketrans` 
- [x] `bytes . partition` 
- [x] `bytes . replace` 
- [x] `bytes . rfind` 
- [x] `bytes . rindex` 
- [x] `bytes . rjust` 
- [x] `bytes . rpartition` 
- [x] `bytes . rsplit` 
- [x] `bytes . rstrip` 
- [x] `bytes . split` 
- [x] `bytes . splitlines` 
- [x] `bytes . startswith` 
- [x] `bytes . strip` 
- [x] `bytes . swapcase` 
- [x] `bytes . title` 
- [x] `bytes . translate` 
- [x] `bytes . upper` 
- [x] `bytes . zfill`

**Comment by jgirardet** [comment]
I start with  __add__, __contains__, __getitem__

**Comment by coolreader18** [comment]
I made your list into checkboxes, so you can check each one off as you do it. Thanks for helping with this!

**Comment by jgirardet** [comment]
thinking about it I think we should implement first the buffer protocol https://docs.python.org/3.7/glossary.html#term-bytes-like-object and then write bytes, memoryview and bytearray in top of that.
It would add some simplicity regarding type checking since `b"abcd" == bytearray(b"abcd") == memoryview(b"abcd")`
What do you think ?

**Comment by coolreader18** [comment]
That sounds good. Would you do it with a trait á la #765?

**Comment by jgirardet** [comment]
Yes thats the idea

Le 31 mars 2019 à 04:11, à 04:11, coolreader18 <notifications@github.com> a écrit:

**Comment by isidentical** [comment]
for `bytes.__init_subclass__`, check out #1346

**Comment by dralley** [comment]
Current status, only these are missing

```
bytes.__getnewargs__
bytes.__init_subclass__
bytes.__mod__
bytes.__rmod__
```

**Comment by xarus01** [comment]
bytes.__sizeof__ seems to be missing.

**Comment by youknowone** [comment]
This is practically done. `__init_subclass__` will be covered by #1346. `__getnewargs__` by pickle.
