### ISSUE TITLE
Possible to get all variables in scope after script executes?

### ISSUE THREAD

**Issue by abagshaw** [RustPython/RustPython#745]
After `run_code_obj` executes, is it possible to get a map of all variables and their corresponding values that are in scope at the end of a script's execution?

**Comment by cthulahoops** [comment]
Any new variables should be created inside the Scope passed to run_code_obj, so you should be able to inspect that to get the variables.

From python:

```
>>>>> globals = {}
>>>>> exec("x = 5", globals)
>>>>> globals
{'x': 5}
```

Is that what you need?

**Comment by abagshaw** [comment]
I'm super new to this, sorry if I'm missing the point...but I don't think that's quite what I'm looking for. I'm wanting to get a representation of the globals that exist after my python script executes, in rust:

```rust
let vars = vm.ctx.new_scope();
let res = vm.run_code_obj(code_obj, vars);
println!("{:?}", res.unwrap().get_globals()) // What I'm looking for
```

Obviously, `get_globals()` doesn't exist, but I'm looking for something like it that would give me a vector of the globals defined once the script finishes. Does that make sense?

**Comment by coolreader18** [comment]
You can just get it from the `vars` variable, `vars.get_locals()`.

**Comment by abagshaw** [comment]
Perfect, thanks!
