### ISSUE TITLE
super().__new__(...)  doesn't work

### ISSUE THREAD

**Issue by skinny121** [RustPython/RustPython#778]
The following doesn't work, but should:

```python
class A(type):
    def __new__(cls):
        super().__new__(cls, "A", (), {})

A()
```
This complains that type_new is getting too many parameters. The extra parameter is a copy of the class of A, that is getting bound within super(), which is not meant to occur.
The parameters to `type.__new__` are `<class "A">, <class "A">, "A", (), {}`. 
Replacing `super()` with `type` does solve the problem.

**Comment by Lynskylate** [comment]
I met same trouble as you when I try to import enum.py. I simplify the code.
```python
class EnumMeta(type):
    def __new__(metacls, cls, bases, classdict):
        enum_class = super().__new__(metacls, cls, bases, classdict)
        return enum_class

class Test(metaclass=EnumMeta):
    def __init__(self):
        pass
"""
>>> t = Test() 
# RustPython Output:
Traceback (most recent call last):
  File "/tmp/reproduce.py", line 17, in <module>
    class Test(metaclass=EnumMeta):
  File "/tmp/reproduce.py", line 14, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict)
TypeError: type() takes 1 or 3 arguments,
"""
```

**Comment by windelbouwman** [comment]
I stumbled upon the implicit `__class__` variable. This page might be related: https://www.python.org/dev/peps/pep-3135/

**Comment by youknowone** [comment]
Both of the reported code works now.
