### ISSUE TITLE
Expand the standard library

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#8]
The standard library is now located in the `Lib` folder. Many modules are still missing (if not all).

If you would like to contribute, this is an easy start. Have a look at the cpython or pypy standard library. Take care about eventual copy rights.

**Comment by buhl** [comment]
I looked a little into this. It seems a lot of the files in the std library have these kind of licenses.
```
#Licensed to PSF under a Contributor Agreement.
#See http://www.python.org/psf/license for licensing details.
```
I am unsure if the files can just be copied with this license or someone needs to give approval?

**Comment by windelbouwman** [comment]
Please check what the license demands. Maybe the license must be copied along. The pypy project did something similar, maybe you can have a look at that?

**Comment by ncoghlan** [comment]
The standard library source files are distributed by the PSF under the PSF License in https://github.com/python/cpython/blob/master/LICENSE

The CLA references elsewhere in the standard library source code relate to the PSF's ability to relicense the given files under those terms.

TL:DR version: drop the PSF license file in your Lib directory, and make it clear that your stdlib implementation is licensed under those terms, and it's all good :)

(You can even apply patches if necessary, but for ease-of-future-updates reasons, it may be preferable to maintain those in a separate directory and apply them at build time)

**Comment by auvipy** [comment]
how much support is remain?

**Comment by youknowone** [comment]
Tip to work on new library: https://rustpython.github.io/guideline/2020/04/04/how-to-contribute-by-cpython-unittest.html

**Comment by youknowone** [comment]
Thank you everyone who worked on this issue for long time!
Because we now even can list the missing libraries, we can manage this better than before.
I'd like to replace this issue to #4564
