### ISSUE TITLE
First release?

### ISSUE THREAD

**Issue by j209** [RustPython/RustPython#838]
Hi
When will we have the first release?

**Comment by windelbouwman** [comment]
Unsure, we have to set proper goals for what would be a proper versioning scheme and also what would be worthy of a release. Ideas welcome!

**Comment by windelbouwman** [comment]
Hi all,

I would like to start releasing crates with the rustpython-parser crate. What is the proper name for this crate on crates.io? Is it `rustpython-parser`, `rustpython_parser`, `python_parser`?

**Comment by coolreader18** [comment]
I think `rustpython-parser` is correct; it's still up for debate the exact naming convention for packages, but I think the hyphen is good to signify that it's the parser part of the rustpython project, e.g. tokio-core, *-derive, *-sys.

**Comment by windelbouwman** [comment]
One can now install rustpython with `cargo install rustpython`. @j209 can this issue be closed?
