### ISSUE TITLE
It is unclear what version of python standard is running

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [RustPython/RustPython#862]
I was about to file an issue concerning missing 3.6 features when I discovered that it is impossible to figure out which version is supported.

`rustpython -V` outputs rather useless `RustPython 0.0.1`. Compare this to pypy's output: 
```
Python 3.6.1 (de061d87e39c, Mar 24 2019, 22:18:21)
[PyPy 7.1.0-beta0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
``` 

`sys.version_info` doesn't exist either.

**Comment by sanxiyn** [comment]
I think you can assume current Python (hence Python 3.7) is targeted. Although so much is missing that it doesn't mean much.

**Comment by coolreader18** [comment]
I think we're sort of "officially" targeting Python 3.6, but yes, so much is missing that the actual standard version we're targeting doesn't matter very much.

**Comment by dmitriy-serdyuk** [comment]
I see, thanks! And keep it up with this great project!
