### ISSUE TITLE
Continue in except clause broken

### ISSUE THREAD

**Issue by skinny121** [RustPython/RustPython#867]
The following, raises an exception `TypeError: Unsupported method: __next__`:
```python
for _ in [1, 2]:
    try:
        raise ArithmeticError()
    except ArithmeticError as e:
        continue
```
The cause of this is that the exception is put on the top of the stack, but continue expects the iterator to be on the top of the stack.

**Comment by adrian17** [comment]
(indirectly related to https://github.com/RustPython/RustPython/pull/831#discussion_r275260542)

**Comment by palaviv** [comment]
Cpython has a stack of exceptions in `PyThreadState`. Do you think we should add something similar to the `VirtualMachine`?
