### ISSUE TITLE
repl-underscore not respect cpython implementation

### ISSUE THREAD

**Issue by andrew-ld** [RustPython/RustPython#921]
![Screenshot_20190505_113453](https://user-images.githubusercontent.com/43882924/57191803-ce7ab000-6f29-11e9-8df2-f8535afa1585.png)

cpython does not save the last result on a global variable named "_"

**Comment by nandhinianandj** [comment]
I'll take a shot at it this week.

**Comment by nandhinianandj** [comment]
@andrew-ld : tried to emulate it can't get any output for '_' to begin with. Think i am on the wrong branch `master` latest. Is there something i should switch to?
