### ISSUE TITLE
'del x' when x is not defined panics

### ISSUE THREAD

**Issue by Jongy** [RustPython/RustPython#929]
```
>>>>> del x
thread 'main' panicked ....
```

Expected (CPython 3.7)

```
>>> del x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined
```

**Comment by nandhinianandj** [comment]
Where do i find the `libcore.rs` file/module?? The error comes from there.

**Comment by coolreader18** [comment]
This is already being worked on, but the reason that it was saying `libcore.rs` was because the panic was coming from calling `.unwrap()` on an `Option`, which is a type from Rust's libcore.
