### ISSUE TITLE
Add support for optional arguments to arg_check!

### ISSUE THREAD

**Issue by OddBloke** [RustPython/RustPython#94]
At the moment, any functions which take a variable number of arguments haven't been updated to use `arg_check!` because it doesn't support it.

**Comment by cthulahoops** [comment]
Option 2 sounds best to me too.

At some point we have to deal with keyword arguments too, and the fact that the caller can pass positional arguments as keyword arguments.

**Comment by OddBloke** [comment]
Oh, oops, didn't mention this in the PR, I guess; I fixed this with #96 (using option 2!).
