### ISSUE TITLE
[RFC] Special markers for commented test snippets that should pass in the future

### ISSUE THREAD

**Issue by Jongy** [RustPython/RustPython#956]
When writing tests that check conformance with CPython, sometimes we find out that some expected features are not supported e.g by the implementation of a module, or even due to some deeper variance the Python VM.

In that case, the common practice I've observed around here is commenting out these tests and perhaps throwing a proceeding, explaining comment.

This is inconvenient because it's not easy to find all these "commented" tests. And why find them? Either because one wants to check for unimplemented issues (Sort of a "TODO "list) or because one wants to re-check them and perhaps enable the once written tests for now-supported features.

Also, if these were marked with something machine readable (I'm thinking something like linter comments) then we could have a script that automatically retries commented tests and enables them if they now pass (A process that's done manually now, e.g 857a7014c2fc341f91b6f86dabecc76056722c25)

What do you think?

If this whole process was made more standardized then it'd make a better incentive for people to write tests even when those *don't* pass at the moment.

**Comment by adrian17** [comment]
> If this whole process was made more standardized then it'd make a better incentive for people to write tests even when those don't pass at the moment.

Mark them as "expected failues" (https://docs.python.org/3/library/unittest.html#unittest.expectedFailure)? This way, once someone fixes the underlying issue (and forgets to update tests), the test will remind us of its existence by failing.

**Comment by Jongy** [comment]
Why yes, `xfail`s are exactly that...

So as disucssed in https://github.com/RustPython/RustPython/issues/196, it all boils down to supporting `unittest`.

**Comment by youknowone** [comment]
unittest now works
