### ISSUE TITLE
Implement import by using importlib

### ISSUE THREAD

**Issue by skinny121** [RustPython/RustPython#958]
The standard library for Python contains importlib, which contains a pure* Python implementation of the import machinery. This is lucky as we then don't have to implement it all in Rust. But we have to bootstrap it and implement all of the functionality it uses from builtin modules.

This is blocked by the following:
- [ ] compile should accept bytes as well as strings
- [x] _os.fspath - https://docs.python.org/3/library/os.html#os.fspath
- [x] sys.implementation.cache_tag  - This just needs to exist we don't support caching bytecode at the moment
- [ ] sys.pycache_prefix  - same as above
- [x] sys.flags
- [x] str.endswith needs to support tuple argument
- [ ] _io.FileIO \_\_enter\_\_ and \_\_exit\_\_ methods
- [x] sys.platform
- [x] os.getcwd
- [x] os.stat st_mtime attribute
- [ ] _warnings module
- possibly more

\* Uses built-in module _imp to actually create module objects.

**Comment by palaviv** [comment]
An initial implementation can be found in #1018.

**Comment by palaviv** [comment]
Another thing that would help this is supporting `{!r}` in string format.

**Comment by palaviv** [comment]
This can be closed not that #1018 was merged

**Comment by apatrushev** [comment]
`level` and `globals` argument is not provided and relative import is not working.
As example `import unittest` is broken at:
```python
from .result import TestResult
```

**Comment by apatrushev** [comment]
Additional investigation - CPython does level magic in compile:
```bash
python -c "import dis; dis.dis(compile('from .second import value', '', 'exec'))"
```
```
  1           0 LOAD_CONST               0 (1)
              2 LOAD_CONST               1 (('value',))
              4 IMPORT_NAME              0 (second)
              6 IMPORT_FROM              1 (value)
              8 STORE_NAME               1 (value)
[...skipped...]
```
(note second dot)
```bash
python -c "import dis; dis.dis(compile('from ..second import value', '', 'exec'))"
```
```
  1           0 LOAD_CONST               0 (2)
              2 LOAD_CONST               1 (('value',))
              4 IMPORT_NAME              0 (second)
              6 IMPORT_FROM              1 (value)
              8 STORE_NAME               1 (value)
[...skipped...]
```

**Comment by palaviv** [comment]
@apatrushev please look at the implementation of the relative import at #1050.

**Comment by apatrushev** [comment]
> @apatrushev please look at the implementation of the relative import at #1050.

I took a short look on the code in PR. Unfortunately I have no strong opinion on where to place this code in compile or in vm execution because I am not confident neither in CPython code nor in RustPython. And I have no idea why CPython doing this in compile time - I just put my investigations here for the history to save the time later.

Besides this disclaimer your code LGTM (and `import unittest` moved forward!).

**Comment by palaviv** [comment]
@skinny121, @apatrushev can we close this issue?
